"""Real PostgreSQL roster races in an explicitly selected, synthetic database.

Only notification delivery and the invitation response snapshot are replaced;
access checks, roster reads/writes, scheme serialization and transactions use
the original shared Web/Agent service and real PostgreSQL connections.
"""
from concurrent.futures import ThreadPoolExecutor
import os
from pathlib import Path
import threading
import time
import unittest
import uuid
from unittest.mock import patch

from fastapi import HTTPException

from classroom_app.db.postgres import LanSharePostgresConnection, sqlite_compatible_dict_row
from classroom_app.db.schema_study_group_scheme import ensure_study_group_scheme_schema
from classroom_app.db.schema_retake import ensure_retake_schema
from classroom_app.services import collaboration_service as service
from tools.assessment_postgres_rehearsal import connect_offline


@unittest.skipUnless(os.environ.get("ASSESSMENT_REHEARSAL_TEST_CLUSTER"), "Requires explicit offline PostgreSQL cluster")
class CollaborationMembershipPostgresTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.cluster = Path(os.environ["ASSESSMENT_REHEARSAL_TEST_CLUSTER"])
        cls.port = int(os.environ["ASSESSMENT_REHEARSAL_TEST_PORT"])
        cls.database = "lanshare_assessment_rehearsal_collaboration_" + uuid.uuid4().hex[:12]
        cls.admin = connect_offline(cluster_dir=cls.cluster, port=cls.port, database="lanshare_assessment_rehearsal")
        cls.admin.autocommit = True
        cls.admin.execute(f'CREATE DATABASE "{cls.database}" TEMPLATE template0')

    @classmethod
    def tearDownClass(cls):
        try:
            cls.admin.execute(f'DROP DATABASE "{cls.database}"')
        finally:
            cls.admin.close()

    def connection(self):
        conn = connect_offline(cluster_dir=self.cluster, port=self.port, database=self.database)
        conn.row_factory = sqlite_compatible_dict_row
        return LanSharePostgresConnection(conn)

    def setUp(self):
        for target, value in (
            ("classroom_app.db.connection.get_configured_db_engine", "postgres"),
            ("classroom_app.db.schema_study_group_scheme.get_configured_db_engine", "postgres"),
            ("classroom_app.db.schema_retake.get_configured_db_engine", "postgres"),
        ):
            item = patch(target, return_value=value)
            item.start()
            self.addCleanup(item.stop)
        ready = patch("classroom_app.db.schema_study_group_scheme._SCHEMA_READY", False)
        ready.start()
        self.addCleanup(ready.stop)
        retake_ready = patch("classroom_app.db.schema_retake._SCHEMA_READY", False)
        retake_ready.start()
        self.addCleanup(retake_ready.stop)
        for name in ("_notify", "_notify_teacher", "_notify_group_members", "load_collaboration_snapshot"):
            item = patch.object(service, name, return_value={})
            item.start()
            self.addCleanup(item.stop)
        self.conn = self.connection()
        self.addCleanup(self.conn.close)
        self.assertEqual(self.database, self.conn.execute("SELECT current_database()").fetchone()[0])
        self.conn.execute("DROP SCHEMA public CASCADE; CREATE SCHEMA public")
        self.conn.execute("""
          CREATE TABLE teachers(id BIGINT PRIMARY KEY, is_super_admin INTEGER, is_active INTEGER);
          CREATE TABLE courses(id BIGINT PRIMARY KEY, name TEXT);
          CREATE TABLE classes(id BIGINT PRIMARY KEY, name TEXT);
          CREATE TABLE students(id BIGINT PRIMARY KEY, class_id BIGINT, name TEXT, student_id_number TEXT,
            enrollment_status TEXT, avatar_file_hash TEXT);
          CREATE TABLE class_offerings(id BIGINT PRIMARY KEY, course_id BIGINT, class_id BIGINT, teacher_id BIGINT);
          CREATE TABLE class_offering_class_links(offering_id BIGINT,class_id BIGINT);
          CREATE TABLE assignments(id TEXT PRIMARY KEY,class_offering_id BIGINT,title TEXT,status TEXT,exam_paper_id BIGINT,due_at TEXT);
          CREATE TABLE peer_reviews(id BIGINT PRIMARY KEY);
          CREATE TABLE study_groups(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, class_offering_id BIGINT REFERENCES class_offerings(id),
            assignment_id TEXT,name TEXT,description TEXT DEFAULT '',status TEXT DEFAULT 'active',join_policy TEXT DEFAULT 'open',
            max_members INTEGER DEFAULT 2,leader_student_id BIGINT,created_by_role TEXT,created_by_user_pk BIGINT,
            created_at TEXT,updated_at TEXT,archived_at TEXT);
          CREATE TABLE study_group_members(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            group_id BIGINT REFERENCES study_groups(id) ON DELETE CASCADE,student_id BIGINT REFERENCES students(id),
            member_role TEXT,status TEXT,joined_at TEXT,left_at TEXT,added_by_role TEXT,added_by_user_pk BIGINT,
            UNIQUE(group_id,student_id));
          INSERT INTO teachers VALUES(1,0,1);
          INSERT INTO courses VALUES(1,'Synthetic course');
          INSERT INTO classes VALUES(30,'Synthetic class'),(31,'Other class');
          INSERT INTO class_offerings VALUES(1,1,30,1),(2,1,31,1);
          INSERT INTO students VALUES(7,30,'Leader','007','active',''),(8,30,'Peer A','008','active',''),
            (9,30,'Peer B','009','active',''),(10,30,'Peer C','010','active',''),(11,31,'Foreign','011','active','');
        """)
        ensure_study_group_scheme_schema(self.conn)
        ensure_retake_schema(self.conn)
        self.conn.commit()

    @staticmethod
    def student(pk):
        return {"id": pk, "role": "student", "name": "Synthetic student"}

    @staticmethod
    def teacher():
        return {"id": 1, "role": "teacher", "name": "Synthetic teacher"}

    def group(self, *, group_id=1, policy="open", cap=2, members=(7,), scheme=None, classroom=1):
        self.conn.execute("""INSERT INTO study_groups(id,class_offering_id,name,status,join_policy,max_members,leader_student_id,
            created_by_role,created_by_user_pk,created_at,updated_at,scheme_id,group_index)
            VALUES(?,?,'Synthetic group','active',?,?,?,'student',7,'2026-09-10','2026-09-10',?,?)""",
            (group_id, classroom, policy, cap, members[0] if members else None, scheme, group_id))
        for sid in members:
            service._upsert_member(self.conn, group_id=group_id, student_id=sid,
                member_role="leader" if sid == members[0] else "member")
        self.conn.commit()

    def scheme(self):
        self.conn.execute("""INSERT INTO group_schemes(id,class_offering_id,name,min_members,max_members,group_count,
            status,created_by_teacher_id) VALUES(1,1,'Synthetic scheme',1,2,2,'active',1)""")
        self.conn.commit()

    def race(self, first, second, *, gate_sql="INSERT INTO study_group_members", same_class=True):
        """Hold the first real transaction immediately before its roster write.

        Prove the contender is waiting on a real PostgreSQL lock before letting
        the first commit; a timing-only assertion would miss a broken guard.
        """
        entered, release, attempted = threading.Event(), threading.Event(), threading.Event()
        pids = {}

        class ConnectionGate:
            def __init__(inner, conn, index):
                inner.conn, inner.index, inner.gated = conn, index, False

            def __getattr__(inner, name):
                return getattr(inner.conn, name)

            def execute(inner, sql, params=()):
                normalized = " ".join(sql.split())
                if inner.index == 1 and normalized.startswith("UPDATE class_offerings SET id = id"):
                    attempted.set()
                if inner.index == 0 and not inner.gated and normalized.startswith(gate_sql):
                    inner.gated = True
                    entered.set()
                    if not release.wait(4):
                        raise TimeoutError("Synthetic roster gate timed out")
                return inner.conn.execute(sql, params)

        def run(fn, index):
            conn = self.connection()
            try:
                pids[index] = conn.execute("SELECT pg_backend_pid()").fetchone()[0]
                try:
                    result = fn(ConnectionGate(conn, index))
                    conn.commit()
                    return 200, result
                except HTTPException as exc:
                    conn.rollback()
                    return exc.status_code, exc.detail
            finally:
                conn.close()

        with ThreadPoolExecutor(max_workers=2) as pool:
            a = pool.submit(run, first, 0)
            try:
                self.assertTrue(entered.wait(3), "first operation did not reach the real roster write")
                b = pool.submit(run, second, 1)
                self.assertTrue(attempted.wait(3), "contender did not attempt the shared classroom lock")
                if same_class:
                    deadline = time.monotonic() + 1
                    while time.monotonic() < deadline:
                        blockers = self.admin.execute("SELECT pg_blocking_pids(%s)", (pids[1],)).fetchone()[0]
                        if pids[0] in blockers:
                            break
                        time.sleep(0.01)
                    self.assertIn(pids[0], blockers, "capacity contenders were not serialized by PostgreSQL")
                    self.assertFalse(b.done())
                else:
                    self.assertEqual(200, b.result(timeout=2)[0], "unrelated classrooms must not share a global lock")
            finally:
                release.set()
            return a.result(timeout=6), b.result(timeout=6)

    def members(self, group_id=1):
        return {r[0] for r in self.conn.execute(
            "SELECT student_id FROM study_group_members WHERE group_id=? AND status='active'", (group_id,)).fetchall()}

    def test_two_open_joins_compete_for_one_remaining_slot(self):
        self.group()
        a, b = self.race(lambda c: service.join_group(c, 1, self.student(8)),
                         lambda c: service.join_group(c, 1, self.student(9)))
        self.assertEqual((200, 400), (a[0], b[0]))
        self.assertEqual({7, 8}, self.members())

    def test_two_invite_acceptances_cannot_overfill_and_loser_remains_pending(self):
        self.group(policy="invite")
        self.conn.execute("INSERT INTO group_invitations(id,group_id,class_offering_id,inviter_student_id,invitee_student_id) VALUES(1,1,1,7,8),(2,1,1,7,9)")
        self.conn.commit()
        a, b = self.race(lambda c: service.respond_invitation(c, 1, self.student(8), accept=True),
                         lambda c: service.respond_invitation(c, 2, self.student(9), accept=True))
        self.assertEqual((200, 400), (a[0], b[0]))
        self.assertEqual({7, 8}, self.members())
        self.assertEqual(["accepted", "pending"], [r[0] for r in self.conn.execute("SELECT status FROM group_invitations ORDER BY id").fetchall()])

    def test_same_invitation_is_reloaded_after_lock_and_only_processed_once(self):
        self.group(policy="invite", cap=4)
        self.conn.execute("INSERT INTO group_invitations(id,group_id,class_offering_id,inviter_student_id,invitee_student_id) VALUES(1,1,1,7,8)")
        self.conn.commit()
        a, b = self.race(lambda c: service.respond_invitation(c, 1, self.student(8), accept=True),
                         lambda c: service.respond_invitation(c, 1, self.student(8), accept=False))
        self.assertEqual((200, 400), (a[0], b[0]))
        self.assertEqual("accepted", self.conn.execute("SELECT status FROM group_invitations WHERE id=1").fetchone()[0])

    def test_teacher_add_and_student_join_obey_the_same_capacity_lock(self):
        self.group()
        a, b = self.race(lambda c: service.add_group_member(c, 1, self.teacher(), 8),
                         lambda c: service.join_group(c, 1, self.student(9)))
        self.assertEqual((200, 400), (a[0], b[0]))
        self.assertEqual({7, 8}, self.members())

    def test_same_student_cannot_join_two_groups_for_the_same_assignment(self):
        self.group(cap=3)
        self.group(group_id=2, members=(8,), cap=3)
        a, b = self.race(lambda c: service.join_group(c, 1, self.student(10)),
                         lambda c: service.join_group(c, 2, self.student(10)))
        self.assertEqual((200, 400), (a[0], b[0]))
        self.assertEqual({7, 10}, self.members(1))
        self.assertEqual({8}, self.members(2))

    def test_scheme_assignment_competes_for_one_slot_without_overfill(self):
        self.scheme()
        self.group(policy=service.SCHEME_JOIN_POLICY, scheme=1)
        self.group(group_id=2, policy=service.SCHEME_JOIN_POLICY, scheme=1, members=())
        a, b = self.race(lambda c: service.teacher_assign_to_scheme_group(c, 1, self.teacher(), 8),
                         lambda c: service.teacher_assign_to_scheme_group(c, 1, self.teacher(), 9))
        self.assertEqual((200, 400), (a[0], b[0]))
        self.assertEqual({7, 8}, self.members())

    def test_random_joins_use_fresh_capacity_under_the_same_lock(self):
        self.scheme()
        self.group(policy=service.SCHEME_JOIN_POLICY, scheme=1)
        self.group(group_id=2, policy=service.SCHEME_JOIN_POLICY, scheme=1, members=(9, 10))
        # Add another eligible ungrouped actor so both contend for slot 2.
        self.conn.execute("INSERT INTO students VALUES(12,30,'Peer D','012','active','')")
        self.conn.commit()
        a, b = self.race(lambda c: service.random_join_scheme(c, 1, self.student(8)),
                         lambda c: service.random_join_scheme(c, 1, self.student(12)))
        self.assertEqual((200, 400), (a[0], b[0]))
        self.assertEqual({7, 8}, self.members())

    def test_classroom_access_is_rechecked_after_waiting(self):
        self.group()
        def first(conn):
            result = service.join_group(conn, 1, self.student(8))
            conn.execute("UPDATE students SET enrollment_status='inactive' WHERE id=9")
            return result
        a, b = self.race(first, lambda c: service.join_group(c, 1, self.student(9)))
        self.assertEqual((200, 403), (a[0], b[0]))
        self.assertEqual({7, 8}, self.members())

    def test_redistribution_and_member_removal_share_classroom_first_lock_order(self):
        self.scheme()
        self.group(policy=service.SCHEME_JOIN_POLICY, scheme=1, members=(7, 8))
        self.group(group_id=2, policy=service.SCHEME_JOIN_POLICY, scheme=1, members=(9, 10))
        a, b = self.race(lambda c: service.redistribute_scheme_groups(c, 1, self.teacher()),
                         lambda c: service.remove_group_member(c, 2, self.teacher(), 10),
                         gate_sql="UPDATE study_group_members SET status = 'removed'")
        self.assertEqual((200, 200), (a[0], b[0]))
        rows = self.conn.execute("""SELECT student_id,COUNT(*) AS c FROM study_group_members WHERE status='active'
            GROUP BY student_id HAVING COUNT(*)>1""").fetchall()
        self.assertEqual([], rows)
        for group_id in (1, 2):
            self.assertLessEqual(len(self.members(group_id)), 2)

    def test_different_classrooms_are_not_serialized(self):
        self.group()
        self.group(group_id=2, members=(), classroom=2)
        a, b = self.race(lambda c: service.join_group(c, 1, self.student(8)),
                         lambda c: service.join_group(c, 2, self.student(11)), same_class=False)
        self.assertEqual((200, 200), (a[0], b[0]))

    def test_initial_assignment_and_lowered_bound_cannot_create_overfull_group(self):
        with self.assertRaises(HTTPException) as caught:
            service.create_group(self.conn, 1, self.teacher(), {"name": "Overfull", "max_members": 2, "member_student_ids": [7, 8, 9]})
        self.assertEqual(400, caught.exception.status_code)
        self.conn.rollback()
        self.group(cap=3, members=(7, 8, 9))
        with self.assertRaises(HTTPException) as caught:
            service.update_group(self.conn, 1, self.teacher(), {"max_members": 2})
        self.assertEqual(400, caught.exception.status_code)
        self.conn.rollback()
        self.assertEqual(3, self.conn.execute("SELECT max_members FROM study_groups WHERE id=1").fetchone()[0])

    def test_file_upload_waits_for_membership_removal_and_rechecks_access(self):
        self.group(cap=3,members=(7,8))
        self.conn.execute('CREATE TABLE study_group_files(id BIGINT PRIMARY KEY)')
        self.conn.commit()
        first,second=self.race(lambda conn:service.remove_group_member(conn,1,self.teacher(),8),
            lambda conn:service.add_group_file(conn,1,self.student(8),file_hash='a'*64,original_filename='fixture.txt',mime_type='text/plain',file_size=1),
            gate_sql='UPDATE study_group_members')
        self.assertEqual((200,403),(first[0],second[0]))
        self.assertEqual({7},self.members())
        self.assertEqual(0,self.conn.execute('SELECT COUNT(*) FROM study_group_files').fetchone()[0])


if __name__ == "__main__":
    unittest.main()
