import json
import shutil
import sqlite3
import unittest
from pathlib import Path

from tools import db_postgres_export


class DatabasePostgresExportTests(unittest.TestCase):
    def setUp(self):
        self.runtime_root = db_postgres_export.TEMP_ROOT / "unit-db-postgres-export"
        self.source_root = db_postgres_export.TEMP_ROOT / "unit-db-postgres-export-source"
        for path in (self.runtime_root, self.source_root):
            if path.exists():
                shutil.rmtree(path)
        self.source_root.mkdir(parents=True, exist_ok=True)
        self.source_db = self.source_root / "source.db"
        self._make_source_db()

    def tearDown(self):
        for path in (self.runtime_root, self.source_root):
            if path.exists():
                shutil.rmtree(path)

    def _make_source_db(self):
        conn = sqlite3.connect(self.source_db)
        try:
            conn.execute("PRAGMA foreign_keys = ON")
            conn.execute(
                """
                CREATE TABLE teachers (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    name TEXT NOT NULL,
                    created_at TEXT DEFAULT CURRENT_TIMESTAMP
                )
                """
            )
            conn.execute(
                """
                CREATE TABLE assignments (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    teacher_id INTEGER NOT NULL REFERENCES teachers(id) ON DELETE CASCADE,
                    title TEXT NOT NULL,
                    sort_order INTEGER NOT NULL DEFAULT 0
                )
                """
            )
            conn.execute(
                """
                CREATE TABLE group_submissions (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    assignment_id TEXT REFERENCES assignments(id),
                    title TEXT
                )
                """
            )
            conn.execute("CREATE INDEX idx_assignments_teacher_title ON assignments (teacher_id, title COLLATE NOCASE)")
            conn.execute("INSERT INTO teachers (name) VALUES ('Teacher O''Neil')")
            conn.execute("INSERT INTO assignments (teacher_id, title, sort_order) VALUES (1, '网络实验', 2)")
            conn.execute("INSERT INTO group_submissions (assignment_id, title) VALUES ('1', 'Group')")
            conn.commit()
        finally:
            conn.close()

    def test_builds_offline_postgres_package_without_touching_source(self):
        report = db_postgres_export.build_postgres_export_package(
            self.runtime_root,
            source_db=self.source_db,
            batch_size=1,
        )

        self.assertEqual("ok", report["status"])
        self.assertEqual(3, report["table_count"])
        self.assertEqual(3, report["total_rows"])
        self.assertFalse(report["actual_postgres_data_load_executed"])
        self.assertFalse(report["safety"]["production_data_modified"])

        schema = Path(report["files"]["schema_sql"]).read_text(encoding="utf-8")
        data = Path(report["files"]["data_sql"]).read_text(encoding="utf-8")
        constraints = Path(report["files"]["constraints_indexes_sql"]).read_text(encoding="utf-8")
        verify = Path(report["files"]["verify_counts_sql"]).read_text(encoding="utf-8")

        self.assertIn('CREATE TABLE IF NOT EXISTS "teachers"', schema)
        self.assertIn("GENERATED BY DEFAULT AS IDENTITY", schema)
        self.assertIn('"assignment_id" BIGINT', schema)
        self.assertIn("'Teacher O''Neil'", data)
        self.assertIn('ALTER TABLE "assignments" ADD CONSTRAINT', constraints)
        self.assertIn("idx_assignments_teacher_title", constraints)
        self.assertNotIn("COLLATE NOCASE", constraints)
        self.assertIn("SELECT 'teachers' AS table_name", verify)

        conn = sqlite3.connect(self.source_db)
        try:
            self.assertEqual(1, conn.execute("SELECT COUNT(*) FROM teachers").fetchone()[0])
        finally:
            conn.close()

    def test_runtime_root_must_stay_under_codex_temp(self):
        unsafe = db_postgres_export.REPO_ROOT / "data" / "pg-export"

        with self.assertRaises(ValueError):
            db_postgres_export.resolve_runtime_root(unsafe)

    def test_main_writes_report(self):
        output = self.runtime_root / "reports" / "postgres-export-package.json"

        exit_code = db_postgres_export.main(
            [
                "--runtime-root",
                str(self.runtime_root),
                "--source-db",
                str(self.source_db),
                "--json-output",
                str(output),
            ]
        )

        self.assertEqual(0, exit_code)
        self.assertTrue(output.exists())
        payload = json.loads(output.read_text(encoding="utf-8"))
        self.assertEqual("ok", payload["status"])


if __name__ == "__main__":
    unittest.main()
