"""Real PostgreSQL locking of the original Web material handlers.

Explicit offline cluster, fresh synthetic DB. Only response decorations, Git
metadata refresh and organization labels are replaced; original permissions,
node mutations, revisions, delete impact/locks and transactions run unchanged.
"""
import asyncio
from concurrent.futures import ThreadPoolExecutor
from contextlib import contextmanager
import os
from pathlib import Path
import threading
import time
import unittest
from unittest.mock import patch
import uuid

from fastapi import HTTPException
from classroom_app.db.postgres import LanSharePostgresConnection, sqlite_compatible_dict_row
from classroom_app.routers.materials_parts import node_ops, library
from classroom_app.services import material_attributes_service as attributes
from classroom_app.services.material_delete_service import build_material_delete_impact
from tools.assessment_postgres_rehearsal import connect_offline
from tests.test_material_node_ops import _make_conn


@unittest.skipUnless(os.environ.get('ASSESSMENT_REHEARSAL_TEST_CLUSTER'), 'Requires explicit offline PostgreSQL cluster')
class MaterialTreePostgresTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.cluster = Path(os.environ['ASSESSMENT_REHEARSAL_TEST_CLUSTER'])
        cls.port = int(os.environ['ASSESSMENT_REHEARSAL_TEST_PORT'])
        cls.database = 'lanshare_assessment_rehearsal_material_' + uuid.uuid4().hex[:12]
        cls.admin = connect_offline(cluster_dir=cls.cluster, port=cls.port, database='lanshare_assessment_rehearsal')
        cls.admin.autocommit = True
        cls.admin.execute(f'CREATE DATABASE "{cls.database}" TEMPLATE template0')

    @classmethod
    def tearDownClass(cls):
        try: cls.admin.execute(f'DROP DATABASE "{cls.database}"')
        finally: cls.admin.close()

    def connection(self):
        raw = connect_offline(cluster_dir=self.cluster, port=self.port, database=self.database)
        raw.row_factory = sqlite_compatible_dict_row
        return LanSharePostgresConnection(raw)

    def setUp(self):
        self.conn = self.connection()
        self.addCleanup(self.conn.close)
        self.conn.execute('DROP SCHEMA public CASCADE; CREATE SCHEMA public')
        fixture = _make_conn()
        try:
            for row in fixture.execute("SELECT sql FROM sqlite_master WHERE type='table' AND name IN ('teachers','course_materials') ORDER BY name DESC"):
                sql = row[0].replace('INTEGER PRIMARY KEY AUTOINCREMENT','BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY')
                sql = sql.replace('INTEGER PRIMARY KEY','BIGINT PRIMARY KEY')
                sql = sql.replace('parent_id INTEGER,','parent_id BIGINT REFERENCES course_materials(id) ON DELETE CASCADE,')
                self.conn.execute(sql)
        finally: fixture.close()
        self.conn.execute("""
            INSERT INTO teachers(id) VALUES(1),(2);
            CREATE TABLE courses(id BIGINT PRIMARY KEY,name TEXT);
            CREATE TABLE classes(id BIGINT PRIMARY KEY,name TEXT);
            CREATE TABLE class_offerings(id BIGINT PRIMARY KEY,course_id BIGINT,class_id BIGINT,semester TEXT,home_learning_material_id BIGINT);
            CREATE TABLE course_material_assignments(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                material_id BIGINT REFERENCES course_materials(id) ON DELETE CASCADE,
                class_offering_id BIGINT,assigned_by_teacher_id BIGINT,created_at TEXT);
            CREATE TABLE course_doc_packs(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                root_material_id BIGINT,teacher_id BIGINT,status TEXT,updated_at TEXT);
            INSERT INTO courses VALUES(1,'Synthetic course');
            INSERT INTO classes VALUES(1,'Class A'),(2,'Class B');
            INSERT INTO class_offerings VALUES(1,1,1,'2026',NULL),(2,1,2,'2026',NULL);
        """)
        self.conn.commit()
        self.local = threading.local()
        for target in ('classroom_app.db.connection.get_configured_db_engine',
                       'classroom_app.services.materials_service.get_configured_db_engine',
                       'classroom_app.services.material_tree_service.get_configured_db_engine',
                       'classroom_app.services.material_attributes_service.get_configured_db_engine',
                       'classroom_app.services.material_delete_service.get_configured_db_engine',
                       'classroom_app.routers.materials_parts.library.get_configured_db_engine',
                       'classroom_app.routers.materials_parts.generation_helpers.get_configured_db_engine'):
            self.guarded(target, return_value='postgres')
        for module in (node_ops, library): self.guarded(module.__name__+'.get_db_connection', self.web_connection)
        self.guarded('classroom_app.routers.materials_parts.node_ops.refresh_root_git_metadata', return_value={})
        self.guarded('classroom_app.routers.materials_parts.node_ops._fetch_material_response_item',
            side_effect=lambda conn,mid,user: dict(conn.execute('SELECT * FROM course_materials WHERE id=?',(mid,)).fetchone()))
        self.guarded('classroom_app.routers.materials_parts.node_ops.load_teacher_org_scope', return_value={
            'school_code':'A','school_name':'Synthetic','college':'C','department':'D'})

    def guarded(self,*args,**kwargs):
        item = patch(*args,**kwargs)
        result = item.start()
        self.addCleanup(item.stop)
        return result

    @contextmanager
    def web_connection(self):
        yield getattr(self.local,'conn',self.conn)

    def create(self,name,parent=None,owner=1):
        return asyncio.run(node_ops.create_material_folder(node_ops.MaterialFolderCreateRequest(name=name,parent_id=parent),
            {'id':owner,'role':'teacher','name':'Synthetic'}))

    def row(self,mid):
        return dict(self.conn.execute('SELECT * FROM course_materials WHERE id=?',(mid,)).fetchone())

    def move(self,mid,target,source_version=None,target_version=None):
        return asyncio.run(node_ops.move_material_node(mid,node_ops.MaterialMoveRequest(target_parent_id=target,
            expected_updated_at=source_version,expected_target_updated_at=target_version),{'id':1,'role':'teacher'}))

    def race(self,first,second,*,gate_sql,wait_sql='UPDATE teachers SET id=id',parallel=False):
        entered,release,attempted = threading.Event(),threading.Event(),threading.Event()
        pids = {}
        class Gate:
            def __init__(inner,conn,index): inner.conn,inner.index,inner.gated=conn,index,False
            def __getattr__(inner,name): return getattr(inner.conn,name)
            def execute(inner,sql,params=()):
                normalized = ' '.join(sql.split())
                if inner.index == 1 and normalized.startswith(wait_sql): attempted.set()
                if inner.index == 0 and not inner.gated and normalized.startswith(gate_sql):
                    inner.gated=True
                    entered.set()
                    if not release.wait(5): raise TimeoutError('Synthetic material gate timed out')
                return inner.conn.execute(sql,params)
        def run(fn,index):
            conn = self.connection()
            try:
                pids[index]=conn.execute('SELECT pg_backend_pid()').fetchone()[0]
                self.local.conn=Gate(conn,index)
                result=fn(self.local.conn)
                conn.commit()
                return result
            except HTTPException as exc:
                conn.rollback()
                return {'http_status':exc.status_code,'detail':str(exc.detail)}
            except BaseException:
                conn.rollback()
                raise
            finally:
                del self.local.conn
                conn.close()
        self.conn.commit()
        with ThreadPoolExecutor(max_workers=2) as pool:
            a=pool.submit(run,first,0)
            self.assertTrue(entered.wait(4))
            b=pool.submit(run,second,1)
            try:
                if parallel:
                    result_b=b.result(timeout=2)
                else:
                    self.assertTrue(attempted.wait(3))
                    blocked=False
                    deadline=time.monotonic()+3
                    while time.monotonic()<deadline:
                        blocked=pids.get(0) in self.admin.execute('SELECT pg_blocking_pids(%s)',(pids[1],)).fetchone()[0]
                        if blocked: break
                        time.sleep(.01)
                    self.assertTrue(blocked,'Contender did not wait on the actual PostgreSQL row lock')
            finally: release.set()
            result_a=a.result(timeout=5)
            if not parallel: result_b=b.result(timeout=5)
        return result_a,result_b

    def test_two_creates_same_folder_name_wait_then_choose_distinct_names(self):
        root=self.create('Root')['material']['id']
        first,second=self.race(lambda _:self.create('Lesson',root),lambda _:self.create('Lesson',root),gate_sql='INSERT INTO course_materials')
        self.assertEqual({'Lesson','Lesson (2)'},{first['material']['name'],second['material']['name']})
        self.assertEqual(2,self.conn.execute('SELECT COUNT(*) FROM course_materials WHERE parent_id=?',(root,)).fetchone()[0])

    def test_reciprocal_moves_cannot_create_cycle_or_mixed_root(self):
        a=self.create('A')['material']['id'];b=self.create('B')['material']['id']
        first,second=self.race(lambda _:self.move(a,b),lambda _:self.move(b,a),gate_sql='UPDATE course_materials SET material_path')
        self.assertEqual('success',first['status'])
        self.assertIn(second['http_status'],(400,409))
        self.assertEqual((b,b),(self.row(a)['parent_id'],self.row(a)['root_id']))
        self.assertIsNone(self.row(b)['parent_id'])

    def test_stale_concurrent_move_has_409_and_does_not_move_latest_location(self):
        a=self.create('A')['material']['id'];b=self.create('B')['material']['id'];c=self.create('C')['material']['id']
        version=self.row(a)['updated_at']
        first,second=self.race(lambda _:self.move(a,b,version),lambda _:self.move(a,c,version),gate_sql='UPDATE course_materials SET material_path')
        self.assertEqual('success',first['status'])
        self.assertEqual(409,second['http_status'])
        self.assertEqual(b,self.row(a)['parent_id'])

    def test_rename_shares_create_lock_and_rechecks_sibling_collision(self):
        root=self.create('Root')['material']['id'];child=self.create('Existing',root)['material']['id']
        first,second=self.race(lambda _:self.create('New',root),lambda conn:attributes.update_material_attributes(conn,
            material_id=child,teacher_id=1,payload={'name':'New'}),gate_sql='INSERT INTO course_materials')
        self.assertEqual('New',first['material']['name'])
        self.assertEqual(409,second['http_status'])
        self.assertEqual('Existing',self.row(child)['name'])

    def test_parent_renamed_while_creator_waits_uses_fresh_parent_path(self):
        root=self.create('Root')['material']['id']
        first,second=self.race(lambda conn:attributes.update_material_attributes(conn,material_id=root,teacher_id=1,payload={'name':'Renamed'}),
            lambda _:self.create('Child',root),gate_sql='UPDATE course_materials SET name')
        self.assertEqual('Renamed/Child',second['material']['material_path'])

    def test_delete_old_impact_rejects_same_count_reference_changed_while_waiting(self):
        root=self.create('Root')['material']['id']
        self.conn.execute("INSERT INTO course_material_assignments(material_id,class_offering_id,assigned_by_teacher_id,created_at) VALUES(?,1,1,'now')",(root,))
        self.conn.commit()
        token=build_material_delete_impact(self.conn,self.row(root))['impact_token']
        def change(conn):
            conn.execute('UPDATE course_material_assignments SET class_offering_id=2 WHERE material_id=?',(root,))
            conn.execute('SELECT 42')
            return 'changed'
        first,second=self.race(change,lambda _:asyncio.run(library.delete_material(root,unlink_references=True,impact_token=token,
            user={'id':1,'role':'teacher'})),gate_sql='SELECT 42',wait_sql='SELECT * FROM course_material_assignments')
        self.assertEqual('changed',first)
        self.assertEqual(409,second['http_status'])
        self.assertEqual(root,self.row(root)['id'])
        self.assertEqual(2,self.conn.execute('SELECT class_offering_id FROM course_material_assignments').fetchone()[0])

    def test_unrelated_owner_can_create_while_first_owner_transaction_is_held(self):
        first,second=self.race(lambda _:self.create('A',owner=1),lambda _:self.create('B',owner=2),
            gate_sql='INSERT INTO course_materials',parallel=True)
        self.assertEqual(1,first['material']['teacher_id'])
        self.assertEqual(2,second['material']['teacher_id'])

    def test_registered_editor_pack_first_lock_cannot_deadlock_material_delete(self):
        root=self.create('Registered root')['material']['id']
        self.conn.execute("INSERT INTO course_doc_packs(root_material_id,teacher_id,status,updated_at) VALUES(?,1,'active','before')",(root,))
        self.conn.commit()
        token=build_material_delete_impact(self.conn,self.row(root))['impact_token']
        def edit(conn):
            conn.execute("UPDATE course_doc_packs SET updated_at='editor' WHERE root_material_id=?",(root,))
            conn.execute("UPDATE course_materials SET file_hash='changed' WHERE id=?",(root,))
            return 'edited'
        first,second=self.race(edit,lambda _:asyncio.run(library.delete_material(root,unlink_references=False,impact_token=token,
            user={'id':1,'role':'teacher'})),gate_sql='UPDATE course_materials SET file_hash',
            wait_sql='UPDATE course_doc_packs SET updated_at=updated_at')
        self.assertEqual('edited',first)
        self.assertEqual(409,second['http_status'])
        self.assertEqual('active',self.conn.execute('SELECT status FROM course_doc_packs').fetchone()[0])
