"""Native plan locks/FK preservation, in an exclusively created synthetic DB.

Normal HTTP/B policy and complete save CAS are covered by the SQLite teaching
suite. Here real PostgreSQL validates the shared row locks and domain SQL.
"""
from concurrent.futures import ThreadPoolExecutor
from contextlib import closing
import re
import sqlite3
import unittest
from unittest.mock import patch

from classroom_app.db.schema_foundation import ensure_foundation_schema
from classroom_app.db.schema_classroom_activity import ensure_classroom_activity_schema
from classroom_app.db.schema_assignments import ensure_assignment_schema
from classroom_app.db.schema_materials_integrations import ensure_materials_integrations_schema
from classroom_app.db.schema_learning_blog import ensure_learning_blog_signature_schema
from classroom_app.db.schema_offering_class_links import ensure_offering_class_links_schema
from classroom_app.db.schema_session_learning_materials import ensure_session_learning_materials_schema
from classroom_app.services.course_planning_service import replace_course_lessons, replace_offering_sessions
from classroom_app.services.offering_plan_edit_service import lock_plan_row, offering_edit_snapshot
from tests.test_agent_authority_postgres import AgentAuthorityPostgresTests as OfflineFixture


class OfferingPlanPostgresTests(OfflineFixture):
    def setUp(self):
        self.conn = self.connection()
        self.addCleanup(self.conn.close)
        self.conn.execute('DROP SCHEMA public CASCADE; CREATE SCHEMA public')
        for table in ('teachers','courses','classes','academic_semesters','textbooks','course_materials',
                      'teacher_academic_course_session_occurrences','teacher_academic_course_sync_items','students','smart_classroom_schedule_items'):
            self.conn.execute(f'CREATE TABLE {table}(id BIGINT PRIMARY KEY)')
        # Actual schema definitions retain all production FK/delete behavior;
        # only the primary-key dialect is converted from the SQLite fixture.
        with closing(sqlite3.connect(':memory:')) as fixture:
            ensure_foundation_schema(fixture)
            ensure_classroom_activity_schema(fixture)
            ensure_assignment_schema(fixture)
            ensure_materials_integrations_schema(fixture)
            ensure_learning_blog_signature_schema(fixture)
            with patch('classroom_app.db.schema_offering_class_links.get_configured_db_engine', return_value='sqlite'):
                ensure_offering_class_links_schema(fixture, force=True)
            with patch('classroom_app.db.schema_session_learning_materials._SCHEMA_READY', False), patch('classroom_app.db.schema_session_learning_materials.get_configured_db_engine', return_value='sqlite'):
                ensure_session_learning_materials_schema(fixture)
            for table in ('course_lessons','class_offerings','class_offering_sessions','class_offering_class_links',
                          'class_offering_learning_materials','learning_material_progress','session_material_generation_tasks',
                          'smart_classroom_checkin_sessions','smart_classroom_checkin_students'):
                sql=fixture.execute("SELECT sql FROM sqlite_master WHERE type='table' AND name=?",(table,)).fetchone()[0]
                sql=re.sub(r'INTEGER\s+PRIMARY\s+KEY\s+AUTOINCREMENT', 'BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY', sql, flags=re.I)
                self.conn.execute(sql)
        self.conn.execute("""
          INSERT INTO teachers VALUES(7); INSERT INTO students VALUES(7); INSERT INTO classes VALUES(30);
          INSERT INTO courses VALUES(20); INSERT INTO course_materials VALUES(800);
          INSERT INTO class_offerings(id,course_id,class_id,teacher_id) VALUES(40,20,30,7);
          INSERT INTO course_lessons(id,course_id,order_index,title,content,section_count) VALUES(50,20,1,'Original','Original content',2);
          INSERT INTO class_offering_sessions(id,class_offering_id,course_lesson_id,order_index,title,content,section_count,session_date,weekday)
             VALUES(60,40,50,1,'Original','Original content',2,'2026-09-10',3);
          INSERT INTO class_offering_class_links(offering_id,class_id,teacher_id,is_primary) VALUES(40,30,7,1);
        """)
        self.conn.commit()
        guard=patch('classroom_app.services.session_learning_materials_service.get_configured_db_engine',return_value='postgres')
        guard.start(); self.addCleanup(guard.stop)

    def snapshot(self, conn=None):
        conn=conn or self.conn
        return offering_edit_snapshot(conn, conn.execute('SELECT * FROM class_offerings WHERE id=40').fetchone())

    def test_course_template_replacement_waits_for_the_shared_plan_source_lock(self):
        lock_plan_row(self.conn,'courses',20)
        def replace():
            with self.connection() as conn:
                replace_course_lessons(conn,course_id=20,lessons=[{'order_index':1,'title':'New content','content':'Revised','section_count':2}])
                conn.commit()
        with ThreadPoolExecutor(max_workers=1) as pool:
            future=pool.submit(replace)
            try:
                self._assert_native_waiting(future)
                self.assertEqual('Original',self.conn.execute('SELECT title FROM course_lessons WHERE id=50').fetchone()[0])
                self.conn.commit()
            finally: self.conn.rollback()
            future.result(timeout=5)
        self.assertEqual('New content',self.conn.execute('SELECT title FROM course_lessons WHERE course_id=20').fetchone()[0])
        self.assertEqual('Original',self.conn.execute('SELECT title FROM class_offering_sessions WHERE id=60').fetchone()[0])

    def test_session_guard_blocks_new_learning_fk_until_plan_transaction_finishes(self):
        lock_plan_row(self.conn,'courses',20)
        lock_plan_row(self.conn,'class_offerings',40)
        lock_plan_row(self.conn,'class_offering_sessions',60)
        def learn():
            with self.connection() as conn:
                conn.execute('INSERT INTO learning_material_progress(class_offering_id,session_id,student_id,material_id) VALUES(40,60,7,800)')
                conn.commit()
        with ThreadPoolExecutor(max_workers=1) as pool:
            future=pool.submit(learn)
            try:
                self._assert_native_waiting(future)
                self.assertEqual([],self.snapshot()['protected_session_ids'])
                self.conn.commit()
            finally: self.conn.rollback()
            future.result(timeout=5)
        self.assertEqual([60],self.snapshot()['protected_session_ids'])

    def test_cancel_keeps_generation_and_learning_bindings_and_rolls_back_atomically(self):
        self.conn.execute("""
          INSERT INTO class_offering_learning_materials(class_offering_id,session_id,material_id) VALUES(40,60,800);
          INSERT INTO learning_material_progress(class_offering_id,session_id,student_id,material_id) VALUES(40,60,7,800);
          INSERT INTO session_material_generation_tasks(class_offering_id,session_id,teacher_id,status,result_payload_json)
             VALUES(40,60,7,'completed','{"artifact":800}');
        """)
        self.conn.commit()
        before=self.snapshot()
        lock_plan_row(self.conn,'courses',20)
        lock_plan_row(self.conn,'class_offerings',40)
        lock_plan_row(self.conn,'class_offering_sessions',60)
        result=replace_offering_sessions(self.conn,offering_id=40,sessions=[],preserve_removed=True,removal_note='Manual plan canceled')
        self.assertEqual(1,result['preserved_count'])
        self.assertEqual('cancelled',self.snapshot()['sessions'][0]['schedule_status'])
        self.assertEqual('{"artifact":800}',self.conn.execute('SELECT result_payload_json FROM session_material_generation_tasks').fetchone()[0])
        self.conn.rollback()
        self.assertEqual(before,self.snapshot())
        replace_offering_sessions(self.conn,offering_id=40,sessions=[],preserve_removed=True)
        self.conn.commit()
        self.assertEqual([60],self.snapshot()['protected_session_ids'])
        self.assertEqual(1,self.conn.execute('SELECT COUNT(*) FROM session_material_generation_tasks').fetchone()[0])


def load_tests(loader, tests, pattern):
    return unittest.TestSuite(OfferingPlanPostgresTests(name) for name,value in OfferingPlanPostgresTests.__dict__.items()
                             if name.startswith('test_') and callable(value))
