"""Opt-in native teaching lock races in an exclusively created loopback DB.

Real domain create/delete/relink SQL is exercised. The small fixture reuses
production root/assignment/document definitions; unrelated parent/lookup tables
contain only their required keys. It is not a full migration or HTTP rehearsal.
"""
from concurrent.futures import ThreadPoolExecutor
from contextlib import closing
import re
import sqlite3
import time
import unittest
from unittest.mock import patch

from fastapi import HTTPException

from classroom_app.db.schema_foundation import ensure_foundation_schema
from classroom_app.db.schema_assignments import ensure_assignment_schema
from classroom_app.db.schema_classroom_activity import ensure_classroom_activity_schema
from classroom_app.db.schema_materials_integrations import ensure_materials_integrations_schema
from classroom_app.db import schema_lesson_plans
from classroom_app.services import teaching_lifecycle_service as lifecycle
from classroom_app.services import lesson_plan_service as plans
from classroom_app.services.assignment_creation_service import create_assignment_record
from tests.test_agent_authority_postgres import AgentAuthorityPostgresTests as OfflineFixture


class TeachingLifecyclePostgresTests(OfflineFixture):
    observations = []
    server_version = ''

    def setUp(self):
        self.conn = self.connection()
        self.addCleanup(self.conn.close)
        self.assertEqual(self.database, self.conn.execute('SELECT current_database()').fetchone()[0])
        type(self).server_version = self.conn.execute('SHOW server_version').fetchone()[0]
        self.conn.execute('DROP SCHEMA public CASCADE; CREATE SCHEMA public')
        for table in ('academic_semesters', 'textbooks', 'course_materials'):
            self.conn.execute(f'CREATE TABLE {table}(id BIGINT PRIMARY KEY)')
        # No application database or lifespan is used to obtain these definitions.
        with closing(sqlite3.connect(':memory:')) as fixture:
            ensure_foundation_schema(fixture)
            ensure_classroom_activity_schema(fixture)
            ensure_assignment_schema(fixture)
            ensure_materials_integrations_schema(fixture)
            with patch.object(schema_lesson_plans, '_SCHEMA_READY', False), patch.object(schema_lesson_plans, 'get_configured_db_engine', return_value='sqlite'):
                schema_lesson_plans.ensure_lesson_plan_schema(fixture)
            for table in ('teachers','courses','classes','class_offerings','assignments',
                          'assignment_classification_revisions','lesson_plans'):
                sql = fixture.execute("SELECT sql FROM sqlite_master WHERE type='table' AND name=?", (table,)).fetchone()[0]
                sql = re.sub(r'INTEGER\s+PRIMARY\s+KEY\s+AUTOINCREMENT', 'BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY', sql, flags=re.I)
                self.conn.execute(sql)
        self.conn.execute('CREATE TABLE learning_stage_exam_attempts(id BIGINT PRIMARY KEY,assignment_id BIGINT)')
        self.conn.execute("""
            INSERT INTO teachers(id,name,email,hashed_password,school_code,school_name,college,department)
                VALUES(7,'Synthetic teacher','synthetic@example.invalid','unused','offline','Offline school','College','Department');
            INSERT INTO courses(id,name,created_by_teacher_id) VALUES(20,'Empty course',7),(21,'Offering course',7);
            INSERT INTO classes(id,name,created_by_teacher_id) VALUES(30,'Synthetic class',7);
            INSERT INTO class_offerings(id,course_id,class_id,teacher_id) VALUES(40,21,30,7);
        """)
        self.conn.commit()
        self.enterContext(patch('classroom_app.db.connection.get_configured_db_engine', return_value='postgres'))
        self.enterContext(patch.object(lifecycle, 'get_configured_db_engine', return_value='postgres'))
        self.enterContext(patch('classroom_app.services.organization_scope_service.get_configured_db_engine', return_value='postgres'))
        # Schema is actually created above, never lazily rewritten by a racer.
        self.enterContext(patch.object(schema_lesson_plans, '_SCHEMA_READY', True))
        self.user = {'id':7, 'role':'teacher', 'name':'Synthetic teacher'}

    def write(self, conn, kind, *, offering=False):
        course_id, offering_id = (21,40) if offering else (20,None)
        if kind == 'document':
            return plans.create_lesson_plan(conn, teacher=self.user, title='Native document',
                course_id=course_id, class_offering_id=offering_id)
        return create_assignment_record(conn, teacher_id=7, course_id=course_id,
            data={'title':'Native assignment', 'class_offering_id':offering_id})['id']

    def review(self):
        return lifecycle.build_teaching_delete_review(self.conn, kind='course', resource_id=20, user=self.user)

    def delete(self, conn, review):
        return lifecycle.delete_unused_teaching_resource(conn, kind='course', resource_id=20, user=self.user,
            expected_review_hash=review['review_hash'], confirmation_text=review['expected_confirmation_text'])

    def run_write(self, kind, *, offering=False):
        with self.connection() as conn:
            try:
                result = self.write(conn, kind, offering=offering)
                conn.commit()
                return {'id':result}
            except HTTPException as error:
                conn.rollback()
                return {'status':error.status_code}

    def assert_native_waiting_on_owner(self, future):
        owner = self.conn.execute('SELECT pg_backend_pid()').fetchone()[0]
        with self.connection() as observer:
            deadline = time.monotonic() + 2
            while time.monotonic() < deadline:
                observer.execute('SELECT pg_stat_clear_snapshot()')
                rows = observer.execute("""SELECT pid,pg_blocking_pids(pid) AS blockers FROM pg_stat_activity
                    WHERE datname=? AND ? = ANY(pg_blocking_pids(pid))""", (self.database,owner)).fetchall()
                if rows:
                    type(self).observations.append({'test':self._testMethodName,'holder_pid':owner,
                        'blocked_pids':[row['pid'] for row in rows], 'proof':'pg_blocking_pids'})
                    self.assertFalse(future.done())
                    return
                if future.done():
                    self.fail(f'The real writer did not wait: {future.result()}')
                time.sleep(.01)
        self.fail('No native PostgreSQL blocking evidence observed')

    def deletion_first(self, kind):
        review = self.review()
        self.assertTrue(review['can_execute'])
        self.delete(self.conn, review)  # Actual DELETE, deliberately not committed.
        with ThreadPoolExecutor(max_workers=1) as pool:
            future = pool.submit(self.run_write, kind)
            try:
                self.assert_native_waiting_on_owner(future)
                self.conn.commit()
            finally:
                self.conn.rollback()
            self.assertEqual({'status':404}, future.result(timeout=5))
        table = 'lesson_plans' if kind == 'document' else 'assignments'
        self.assertEqual(0,self.conn.execute(f'SELECT COUNT(*) FROM {table} WHERE course_id=20').fetchone()[0])
        self.assertIsNone(self.conn.execute('SELECT id FROM courses WHERE id=20').fetchone())

    def writer_first(self, kind):
        review = self.review()
        written = self.write(self.conn, kind)  # Actual domain rows + parent lock.
        def delete_after_writer():
            with self.connection() as conn:
                try:
                    self.delete(conn, review)
                    conn.commit()
                    return 200
                except HTTPException as error:
                    conn.rollback()
                    return error.status_code
        with ThreadPoolExecutor(max_workers=1) as pool:
            future = pool.submit(delete_after_writer)
            try:
                self.assert_native_waiting_on_owner(future)
                self.conn.commit()
            finally:
                self.conn.rollback()
            self.assertEqual(409, future.result(timeout=5))
        table = 'lesson_plans' if kind == 'document' else 'assignments'
        self.assertIsNotNone(self.conn.execute(f'SELECT id FROM {table} WHERE id=?',(written,)).fetchone())
        self.assertIsNotNone(self.conn.execute('SELECT id FROM courses WHERE id=20').fetchone())

    def stale_offering(self, kind):
        lifecycle.lock_teaching_context(self.conn, course_id=21, class_offering_id=40)
        # Same source-removal boundary as merge: course -> offering held until
        # commit. Full merge migration is covered by the existing domain suite.
        self.conn.execute('DELETE FROM class_offerings WHERE id=40')
        with ThreadPoolExecutor(max_workers=1) as pool:
            future = pool.submit(self.run_write, kind, offering=True)
            try:
                self.assert_native_waiting_on_owner(future)
                self.conn.commit()
            finally:
                self.conn.rollback()
            self.assertEqual({'status':409},future.result(timeout=5))
        table = 'lesson_plans' if kind == 'document' else 'assignments'
        self.assertEqual(0,self.conn.execute(f'SELECT COUNT(*) FROM {table} WHERE class_offering_id=40').fetchone()[0])

    def test_course_delete_committed_first_rejects_waiting_document(self): self.deletion_first('document')
    def test_course_delete_committed_first_rejects_waiting_assignment(self): self.deletion_first('assignment')
    def test_real_document_committed_first_invalidates_waiting_delete(self): self.writer_first('document')
    def test_real_assignment_committed_first_invalidates_waiting_delete(self): self.writer_first('assignment')
    def test_document_rechecks_offering_after_course_lock_wait(self): self.stale_offering('document')
    def test_assignment_rechecks_offering_after_course_lock_wait(self): self.stale_offering('assignment')

    def test_metadata_relink_holding_document_exits_nowait_without_deadlock(self):
        plan = self.write(self.conn,'document',offering=True)
        self.conn.commit()
        lifecycle.lock_teaching_parent(self.conn,'course',20)
        with self.connection() as other:
            other.execute('SELECT id FROM lesson_plans WHERE id=? FOR UPDATE',(plan,)).fetchone()
            started = time.monotonic()
            with self.assertRaises(HTTPException) as failure:
                plans.update_attributes(other,plan,course_id=20,class_offering_id=0)
            self.assertEqual(409,failure.exception.status_code)
            self.assertLess(time.monotonic()-started,2)
            other.rollback()
        self.conn.rollback()
        row=self.conn.execute('SELECT course_id,class_offering_id FROM lesson_plans WHERE id=?',(plan,)).fetchone()
        self.assertEqual((21,40),(row['course_id'],row['class_offering_id']))
        type(self).observations.append({'test':self._testMethodName,'proof':'real NOWAIT conflict returns HTTP409; domain row unchanged'})


def load_tests(loader, tests, pattern):
    return unittest.TestSuite(TeachingLifecyclePostgresTests(name) for name,value in TeachingLifecyclePostgresTests.__dict__.items()
                             if name.startswith('test_') and callable(value))
