"""Classroom AI configuration API contracts, using isolated application data."""
import sqlite3
import tempfile
import unittest
from pathlib import Path
from unittest.mock import AsyncMock, patch

import httpx
from fastapi import FastAPI
from fastapi.testclient import TestClient

from classroom_app.db.schema_offering_class_links import ensure_offering_class_links_schema
from classroom_app.routers.manage_parts import classes_courses_offerings as routes
from classroom_app.services.psych_profile_service import load_ai_class_config


SCHEMA_SQL = [
    "CREATE TABLE teachers (id INTEGER PRIMARY KEY, name TEXT, is_active INTEGER DEFAULT 1, is_super_admin INTEGER DEFAULT 0)",
    "CREATE TABLE classes (id INTEGER PRIMARY KEY, name TEXT, description TEXT)",
    "CREATE TABLE courses (id INTEGER PRIMARY KEY, name TEXT, description TEXT, credits REAL)",
    "CREATE TABLE academic_semesters (id INTEGER PRIMARY KEY, name TEXT, start_date TEXT, end_date TEXT, week_count INTEGER)",
    """CREATE TABLE textbooks (id INTEGER PRIMARY KEY, teacher_id INTEGER, title TEXT,
        authors_json TEXT, publisher TEXT, publication_date TEXT, introduction TEXT, catalog_text TEXT,
        tags_json TEXT, attachment_name TEXT, attachment_path TEXT, attachment_size INTEGER,
        attachment_mime_type TEXT, scope_level TEXT DEFAULT 'private')""",
    """CREATE TABLE class_offerings (id INTEGER PRIMARY KEY, teacher_id INTEGER, class_id INTEGER,
        course_id INTEGER, semester_id INTEGER, semester TEXT, schedule_info TEXT,
        textbook_id INTEGER REFERENCES textbooks(id))""",
    "CREATE TABLE students (id INTEGER PRIMARY KEY, class_id INTEGER, enrollment_status TEXT)",
    "CREATE TABLE course_materials (id INTEGER PRIMARY KEY, name TEXT, updated_at TEXT)",
    "CREATE TABLE course_material_assignments (id INTEGER PRIMARY KEY, material_id INTEGER, class_offering_id INTEGER, created_at TEXT)",
    "CREATE TABLE assignments (id INTEGER PRIMARY KEY, title TEXT, class_offering_id INTEGER, created_at TEXT)",
    """CREATE TABLE ai_class_configs (id INTEGER PRIMARY KEY, class_offering_id INTEGER NOT NULL UNIQUE
        REFERENCES class_offerings(id), system_prompt TEXT, syllabus TEXT,
        created_at TEXT DEFAULT CURRENT_TIMESTAMP, updated_at TEXT DEFAULT CURRENT_TIMESTAMP)""",
]


def seed_fixture(conn, *, engine="sqlite"):
    for statement in SCHEMA_SQL:
        if engine == "postgres":
            statement = statement.replace("INTEGER PRIMARY KEY", "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY")
        conn.execute(statement)
    conn.execute("INSERT INTO teachers (id, name) VALUES (1, 'Teacher A'), (2, 'Teacher B')")
    conn.execute("INSERT INTO classes (id, name) VALUES (1, 'Class A'), (2, 'Class B')")
    conn.execute("INSERT INTO courses (id, name) VALUES (1, 'Course A')")
    conn.execute("INSERT INTO academic_semesters (id, name) VALUES (1, 'Semester A')")
    conn.execute("""INSERT INTO textbooks (id, teacher_id, title, introduction, catalog_text) VALUES
        (1, 1, 'OLD BOOK', 'old introduction', 'old chapters'),
        (2, 1, 'NEW BOOK', 'new introduction', 'new chapters'),
        (3, 2, 'PRIVATE BOOK', 'private introduction', 'private chapters')""")
    conn.execute("""INSERT INTO class_offerings (id, teacher_id, class_id, course_id, semester_id, textbook_id)
        VALUES (11, 1, 1, 1, 1, 1), (12, 1, 2, 1, 1, NULL), (13, 2, 2, 1, 1, 3)""")
    ensure_offering_class_links_schema(conn, force=True, engine=engine)
    conn.commit()


def build_app():
    app = FastAPI()
    app.include_router(routes.router, prefix="/api/manage")
    app.dependency_overrides[routes.get_current_teacher] = lambda: {"id": 1, "role": "teacher", "name": "Teacher A"}
    return app


class ClassroomAIConfigTests(unittest.TestCase):
    def setUp(self):
        self.temp = tempfile.TemporaryDirectory(prefix="lanshare-ai-config-")
        self.addCleanup(self.temp.cleanup)
        self.db_path = Path(self.temp.name) / "test.db"
        with self.connect() as conn:
            seed_fixture(conn)
        self.db_patch = patch.object(routes, "get_db_connection", self.connect)
        self.db_patch.start()
        self.addCleanup(self.db_patch.stop)
        self.client = TestClient(build_app())
        self.addCleanup(self.client.close)

    def connect(self):
        conn = sqlite3.connect(self.db_path, check_same_thread=False)
        self.addCleanup(conn.close)
        conn.row_factory = sqlite3.Row
        conn.execute("PRAGMA foreign_keys=ON")
        return conn

    def save(self, **overrides):
        payload = {"class_offering_id": 11, "system_prompt": "Saved prompt", "syllabus": "Saved syllabus", "textbook_id": "2"}
        payload.update(overrides)
        return self.client.post("/api/manage/ai/configure", data=payload)

    def read(self, offering_id=11):
        return self.client.get(f"/api/manage/ai/config/{offering_id}")

    def test_save_reload_update_and_runtime_reader(self):
        self.assertFalse(self.read().json()["has_config"])
        self.assertEqual(self.save().status_code, 200)
        loaded = self.read().json()
        self.assertTrue(loaded["has_config"])
        self.assertEqual(loaded["system_prompt"], "Saved prompt")
        self.assertEqual(loaded["textbook_id"], 2)
        self.assertIn("NEW BOOK", loaded["textbook_summary"])
        self.assertEqual(self.save(system_prompt="Updated prompt").status_code, 200)
        with self.connect() as conn:
            self.assertEqual(conn.execute("SELECT COUNT(*) FROM ai_class_configs").fetchone()[0], 1)
            self.assertEqual(load_ai_class_config(conn, 11)["system_prompt"], "Updated prompt")
            self.assertEqual(load_ai_class_config(conn, 12)["system_prompt"], "")

    def test_explicit_empty_unbinds_but_omitted_preserves(self):
        response = self.client.post("/api/manage/ai/configure", data={"class_offering_id": 11, "system_prompt": "Prompt"})
        self.assertEqual(response.status_code, 200)
        self.assertEqual(self.read().json()["textbook_id"], 1)
        self.assertEqual(self.save(textbook_id="", system_prompt="", syllabus="").status_code, 200)
        loaded = self.read().json()
        self.assertIsNone(loaded["textbook_id"])
        self.assertTrue(loaded["has_config"])
        self.assertEqual(loaded["system_prompt"], "")
        self.assertEqual(loaded["syllabus"], "")

    def test_invalid_textbook_ids_leave_both_tables_unchanged(self):
        for value in ("abc", "0", "-1", "1.5", "[]", "9" * 24):
            with self.subTest(value=value):
                self.assertEqual(self.save(textbook_id=value).status_code, 400)
        self.assertEqual(self.read().json()["textbook_id"], 1)
        self.assertFalse(self.read().json()["has_config"])
        self.assertEqual(self.save(class_offering_id="9" * 24).status_code, 400)
        self.assertEqual(self.read("9" * 24).status_code, 400)

    def test_foreign_classroom_and_private_textbook_are_rejected(self):
        self.assertEqual(self.read(13).status_code, 404)
        self.assertEqual(self.save(class_offering_id=13).status_code, 404)
        self.assertEqual(self.save(textbook_id="3").status_code, 404)
        self.assertEqual(self.save(textbook_id="999").status_code, 404)
        self.assertFalse(self.read().json()["has_config"])

    def test_database_failure_rolls_back_textbook_and_is_logged(self):
        with self.connect() as conn:
            conn.execute("DROP TABLE ai_class_configs")
        with self.assertLogs(routes.logger, level="ERROR") as logs:
            response = self.save()
        self.assertEqual(response.status_code, 500)
        self.assertNotIn("no such table", response.text)
        self.assertIn("offering_id=11", "\n".join(logs.output))
        with self.connect() as conn:
            self.assertEqual(conn.execute("SELECT textbook_id FROM class_offerings WHERE id=11").fetchone()[0], 1)

    def generate(self, payload=None):
        return self.client.post("/api/manage/ai/ai-generate", json=payload if payload is not None else {"class_offering_id": 11, "textbook_id": 2})

    def upstream(self, payload, status=200):
        return patch.object(routes.ai_client, "post", new=AsyncMock(return_value=httpx.Response(
            status, json=payload, request=httpx.Request("POST", "http://ai/api/ai/chat"))))

    def test_generation_uses_selected_textbook_without_saving(self):
        with self.upstream({"status": "success", "response_text": '```json\n{"system_prompt":"AI prompt","syllabus":"AI syllabus"}\n```'}) as upstream:
            response = self.generate()
        self.assertEqual(response.status_code, 200, response.text)
        prompt = upstream.call_args.kwargs["json"]["new_message"]
        self.assertIn("NEW BOOK", prompt)
        self.assertIn("new chapters", prompt)
        self.assertNotIn("OLD BOOK", prompt)
        self.assertEqual(self.read().json()["textbook_id"], 1)
        self.assertFalse(self.read().json()["has_config"])

    def test_generation_rejects_invalid_requests_before_ai_call(self):
        with patch.object(routes.ai_client, "post", new=AsyncMock()) as upstream:
            for payload in ([], 1, {}, {"class_offering_id": True, "textbook_id": 2}, {"class_offering_id": 11, "textbook_id": 1.5}):
                with self.subTest(payload=payload):
                    self.assertEqual(self.generate(payload).status_code, 400)
            self.assertEqual(self.generate({"class_offering_id": 13, "textbook_id": 2}).status_code, 404)
            self.assertEqual(self.generate({"class_offering_id": 11, "textbook_id": 3}).status_code, 404)
            upstream.assert_not_called()

    def test_generation_rejects_malformed_or_incomplete_ai_content(self):
        for content in ("[]", "null", "not json", '{}', '{"system_prompt":"only prompt"}',
                        '{"system_prompt":{},"syllabus":[]}', '{"system_prompt":" ","syllabus":"ok"}'):
            with self.subTest(content=content), self.upstream({"status": "success", "response_text": content}):
                self.assertEqual(self.generate().status_code, 502)
        for payload in ([], None, {"status": "error", "detail": "private upstream error"}):
            with self.subTest(payload=payload), self.upstream(payload):
                response = self.generate()
                self.assertEqual(response.status_code, 502)
                self.assertNotIn("private upstream", response.text)

    def test_generation_service_failures_have_actionable_status(self):
        for status, expected in ((401, 502), (429, 429), (500, 502)):
            with self.subTest(status=status), self.upstream({"detail": "secret upstream details"}, status):
                response = self.generate()
                self.assertEqual(response.status_code, expected)
                self.assertNotIn("secret upstream", response.text)
        for exception, expected in ((httpx.ConnectError("down"), 503), (httpx.ReadTimeout("slow"), 504)):
            with patch.object(routes.ai_client, "post", new=AsyncMock(side_effect=exception)):
                self.assertEqual(self.generate().status_code, expected)


if __name__ == "__main__":
    unittest.main()
