"""Real exam row locks on the explicit offline cluster; never app DATABASE_URL."""
import copy
from concurrent.futures import ThreadPoolExecutor
import unittest
from unittest.mock import Mock, patch

from fastapi import HTTPException

from tests.test_agent_authority_postgres import AgentAuthorityPostgresTests, NOW
from classroom_app.db import schema_scheduler
from classroom_app.services import exam_paper_management_service as exams
from classroom_app.services import agent_platform_write_service as writes
from classroom_app.services.exam_json_service import EXAM_JSON_TEMPLATE
from classroom_app.services.agent_delegation_service import issue_task_delegation


class AgentExamPostgresTests(AgentAuthorityPostgresTests):
    def setUp(self):
        super().setUp()
        self.conn.execute("""
            CREATE TABLE courses(id BIGINT PRIMARY KEY,name TEXT,created_by_teacher_id BIGINT REFERENCES teachers(id));
            CREATE TABLE classes(id BIGINT PRIMARY KEY,name TEXT);
            CREATE TABLE class_offerings(id BIGINT PRIMARY KEY,course_id BIGINT REFERENCES courses(id),class_id BIGINT REFERENCES classes(id),teacher_id BIGINT REFERENCES teachers(id));
            CREATE TABLE exam_papers(id TEXT PRIMARY KEY,teacher_id BIGINT REFERENCES teachers(id),title TEXT,description TEXT,
                questions_json TEXT,exam_config_json TEXT,status TEXT,owner_role TEXT,owner_user_pk BIGINT,scope_level TEXT,
                school_code TEXT,school_name TEXT,college TEXT,department TEXT,tags_json TEXT,created_at TEXT,updated_at TEXT);
            CREATE TABLE assignments(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,course_id BIGINT REFERENCES courses(id),
                title TEXT,status TEXT,requirements_md TEXT,rubric_md TEXT,grading_mode TEXT,exam_paper_id TEXT REFERENCES exam_papers(id),
                class_offering_id BIGINT REFERENCES class_offerings(id),created_at TEXT,allowed_file_types_json TEXT,
                availability_mode TEXT,starts_at TEXT,due_at TEXT,duration_minutes INTEGER,auto_close INTEGER,closed_at TEXT,
                late_submission_enabled INTEGER,late_submission_until TEXT,late_penalty_strategy TEXT,
                late_penalty_interval_hours REAL,late_penalty_points REAL,late_penalty_min_score REAL,late_score_cap REAL,learning_stage_key TEXT,
                assessment_kind TEXT,assessment_kind_version INTEGER DEFAULT 0,assessment_kind_source TEXT DEFAULT '',
                assessment_kind_updated_at TEXT,assessment_kind_updated_by_teacher_id BIGINT);
            CREATE TABLE assignment_classification_revisions(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                assignment_id TEXT,class_offering_id BIGINT,previous_kind TEXT,assessment_kind TEXT,previous_version INTEGER,
                version INTEGER,source TEXT,changed_by_teacher_id BIGINT,changed_at TEXT,reason TEXT DEFAULT '',UNIQUE(assignment_id,version));
            CREATE TABLE learning_stage_exam_attempts(id BIGINT PRIMARY KEY,assignment_id BIGINT,exam_paper_id TEXT);
            CREATE TABLE submissions(id BIGINT PRIMARY KEY,assignment_id BIGINT REFERENCES assignments(id));
            CREATE TABLE submission_drafts(id BIGINT PRIMARY KEY,assignment_id BIGINT REFERENCES assignments(id));
            INSERT INTO courses VALUES(20,'Synthetic course',7);
            INSERT INTO classes VALUES(30,'Synthetic class');
            INSERT INTO class_offerings VALUES(40,20,30,7);
        """)
        with patch.object(schema_scheduler, '_SCHEMA_READY', False), patch.object(schema_scheduler, 'get_configured_db_engine', return_value='postgres'):
            schema_scheduler.ensure_scheduler_schema(self.conn)
        ready = patch.object(schema_scheduler, '_SCHEMA_READY', True)
        ready.start()
        self.addCleanup(ready.stop)
        hook = patch.object(exams, 'create_assignment_published_notifications', Mock())
        hook.start()
        self.addCleanup(hook.stop)
        self.questions = copy.deepcopy(EXAM_JSON_TEMPLATE)
        self.paper_id = exams.create_exam_paper_record(self.conn, teacher_id=7,
            data={'title': 'Synthetic exam', 'questions': self.questions})['paper_id']
        self.conn.commit()
        self.params = {'paper_id': self.paper_id, 'class_offering_id': 40, 'assessment_kind': 'final',
                       'expected_paper_revision': exams.get_exam_review(self.conn, teacher_id=7, paper_id=self.paper_id)['paper_revision']}
        self.issued = issue_task_delegation(self.conn, task_id=10, attempt_id=self.attempt['id'],
            fencing_token=self.attempt['fencing_token'], purpose='tools', scopes=['platform:write'],
            source_session_id='teacher-session', now=NOW)
        self.conn.commit()

    def test_native_agent_and_web_same_paper_assignment_serialize_to_one_business_and_receipt(self):
        first = writes.dispatch_write(self.conn, self.issued['token'], 'exam-assignment', 'assign_exam_paper', self.params)
        def ordinary_assign():
            with self.connection() as conn:
                try:
                    exams.assign_exam_paper_record(conn, teacher_id=7, paper_id=self.paper_id,
                        data={'class_offering_id': 40, 'assessment_kind': 'final'})
                    conn.commit()
                    return 200
                except HTTPException as error:
                    conn.rollback()
                    return error.status_code
        with ThreadPoolExecutor(max_workers=1) as pool:
            future = pool.submit(ordinary_assign)
            try:
                self._assert_native_waiting(future)
                self.conn.commit()
            finally:
                self.conn.rollback()
            self.assertEqual(409, future.result(timeout=5))
        self.assertEqual(1, self.conn.execute('SELECT COUNT(*) FROM assignments').fetchone()[0])
        self.assertEqual(1, self.conn.execute('SELECT COUNT(*) FROM assignment_classification_revisions').fetchone()[0])
        self.assertEqual(1, self.conn.execute('SELECT COUNT(*) FROM agent_action_executions').fetchone()[0])
        self.assertEqual(first['result'], writes.dispatch_write(self.conn, self.issued['token'], 'exam-assignment', 'assign_exam_paper', self.params)['result'])

    def test_native_authoring_commit_invalidates_waiting_agent_assignment_review(self):
        exams.update_exam_content_record(self.conn, teacher_id=7, paper_id=self.paper_id,
            payload={'title': 'New exam title', 'questions': self.questions})
        def assign():
            with self.connection() as conn:
                try:
                    writes.dispatch_write(conn, self.issued['token'], 'stale-exam-assignment', 'assign_exam_paper', self.params)
                    conn.commit()
                    return 200
                except HTTPException as error:
                    conn.rollback()
                    return error.status_code
        with ThreadPoolExecutor(max_workers=1) as pool:
            future = pool.submit(assign)
            try:
                self._assert_native_waiting(future)
                self.conn.commit()
            finally:
                self.conn.rollback()
            self.assertEqual(409, future.result(timeout=5))
        self.assertEqual(0, self.conn.execute('SELECT COUNT(*) FROM assignments').fetchone()[0])
        self.assertEqual(0, self.conn.execute('SELECT COUNT(*) FROM agent_action_executions').fetchone()[0])

    def test_native_receipt_failure_rolls_back_real_paper_reference_and_classification(self):
        with patch.object(writes, 'complete_agent_operation', side_effect=RuntimeError('synthetic receipt failure')):
            with self.assertRaises(RuntimeError):
                writes.dispatch_write(self.conn, self.issued['token'], 'rollback-exam', 'assign_exam_paper', self.params)
        self.conn.rollback()
        for table in ('assignments', 'assignment_classification_revisions', 'agent_action_executions'):
            self.assertEqual(0, self.conn.execute('SELECT COUNT(*) FROM ' + table).fetchone()[0])
        self.assertEqual(self.params['expected_paper_revision'], exams.get_exam_review(self.conn, teacher_id=7, paper_id=self.paper_id)['paper_revision'])


def load_tests(loader, tests, pattern):
    # Reuse the restricted fixture, not the parent's already-covered tests.
    return unittest.TestSuite(AgentExamPostgresTests(name) for name, value in AgentExamPostgresTests.__dict__.items()
        if name.startswith('test_') and callable(value))
