"""Schema for the generic approval workflow (通用审批流).

One ``approval_requests`` row is a request of some registered *type* (for
example ``submission_withdraw``) raised by an applicant against a business
subject. Reviewers live in ``approval_request_reviewers``; any single reviewer's
decision is final. Every state change is appended to
``approval_request_events`` for audit.

Type-specific data stays in ``payload_json`` / ``decision_payload_json`` and is
interpreted by the type's hooks in ``approval_workflow_service`` — the tables
themselves never change when a new request type is registered.

The DDL is engine-aware and idempotent (``CREATE TABLE IF NOT EXISTS`` on both
SQLite and PostgreSQL) and is ensured lazily at runtime, mirroring
``schema_polls``. Timestamps are ISO-8601 TEXT, booleans INTEGER 0/1.
"""

from __future__ import annotations

from typing import Any

from ..db.connection import get_configured_db_engine

_SCHEMA_READY = False

APPROVAL_STATUS_PENDING = "pending"
APPROVAL_STATUS_APPROVED = "approved"
APPROVAL_STATUS_REJECTED = "rejected"
APPROVAL_STATUS_CANCELLED = "cancelled"
APPROVAL_STATUS_EXPIRED = "expired"
APPROVAL_TERMINAL_STATUSES = frozenset({
    APPROVAL_STATUS_APPROVED, APPROVAL_STATUS_REJECTED, APPROVAL_STATUS_CANCELLED, APPROVAL_STATUS_EXPIRED,
})


def ensure_approval_workflow_schema(conn: Any) -> None:
    """Create the approval workflow tables on either engine (idempotent)."""
    global _SCHEMA_READY
    if _SCHEMA_READY:
        return
    engine = get_configured_db_engine()
    id_column = (
        "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
        if engine == "postgres"
        else "id INTEGER PRIMARY KEY AUTOINCREMENT"
    )

    conn.execute(
        f"""
        CREATE TABLE IF NOT EXISTS approval_requests (
            {id_column},
            request_type TEXT NOT NULL,
            status TEXT NOT NULL DEFAULT 'pending',
            applicant_role TEXT NOT NULL,
            applicant_user_pk INTEGER NOT NULL,
            applicant_name TEXT NOT NULL DEFAULT '',
            subject_type TEXT NOT NULL DEFAULT '',
            subject_id TEXT NOT NULL DEFAULT '',
            assignment_id TEXT,
            class_offering_id INTEGER,
            title TEXT NOT NULL DEFAULT '',
            reason TEXT NOT NULL DEFAULT '',
            payload_json TEXT NOT NULL DEFAULT '{{}}',
            decision_note TEXT NOT NULL DEFAULT '',
            decision_payload_json TEXT NOT NULL DEFAULT '{{}}',
            decided_by_role TEXT NOT NULL DEFAULT '',
            decided_by_user_pk INTEGER,
            decided_by_name TEXT NOT NULL DEFAULT '',
            decided_at TEXT,
            expires_at TEXT,
            dedupe_key TEXT NOT NULL DEFAULT '',
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
        )
        """
    )
    # One live request per business subject; decided requests keep their key.
    conn.execute(
        "CREATE UNIQUE INDEX IF NOT EXISTS uq_approval_requests_pending_dedupe "
        "ON approval_requests (dedupe_key) WHERE status = 'pending' AND dedupe_key <> ''"
    )
    conn.execute(
        "CREATE INDEX IF NOT EXISTS idx_approval_requests_applicant "
        "ON approval_requests (applicant_role, applicant_user_pk, status, created_at DESC)"
    )
    conn.execute(
        "CREATE INDEX IF NOT EXISTS idx_approval_requests_assignment "
        "ON approval_requests (assignment_id, status, created_at DESC)"
    )
    conn.execute(
        "CREATE INDEX IF NOT EXISTS idx_approval_requests_subject "
        "ON approval_requests (request_type, subject_type, subject_id, status)"
    )

    conn.execute(
        f"""
        CREATE TABLE IF NOT EXISTS approval_request_reviewers (
            {id_column},
            request_id INTEGER NOT NULL,
            reviewer_role TEXT NOT NULL,
            reviewer_user_pk INTEGER NOT NULL,
            reviewer_name TEXT NOT NULL DEFAULT '',
            notified_at TEXT,
            reminded_at TEXT,
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            UNIQUE (request_id, reviewer_role, reviewer_user_pk)
        )
        """
    )
    conn.execute(
        "CREATE INDEX IF NOT EXISTS idx_approval_request_reviewers_reviewer "
        "ON approval_request_reviewers (reviewer_role, reviewer_user_pk, request_id)"
    )

    conn.execute(
        f"""
        CREATE TABLE IF NOT EXISTS approval_request_events (
            {id_column},
            request_id INTEGER NOT NULL,
            event_type TEXT NOT NULL,
            actor_role TEXT NOT NULL DEFAULT '',
            actor_user_pk INTEGER,
            actor_name TEXT NOT NULL DEFAULT '',
            note TEXT NOT NULL DEFAULT '',
            payload_json TEXT NOT NULL DEFAULT '{{}}',
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
        )
        """
    )
    conn.execute(
        "CREATE INDEX IF NOT EXISTS idx_approval_request_events_request "
        "ON approval_request_events (request_id, id)"
    )
    _SCHEMA_READY = True
