"""个人日历订阅（iCal feed）。

给每个学生/教师一个 token 化的只读 .ics 订阅链接，手机/电脑日历 App
订阅后自动看到：上课安排、作业/考试截止、教务考试和自建待办。
数据复用 ``todo_service.build_classroom_todo_overview``，与站内"待办与提醒"
完全同源，不另造一套口径。

Token 是 128-bit URL-safe 随机串，仅授权"读取本人日程"这一件事；
学生可随时重置让旧链接失效。
（区别于 ``academic_calendar_sync_service``：那是教务日历事件的入库同步。）
"""

from __future__ import annotations

import secrets
from datetime import datetime, timedelta
from typing import Any

from ..config import PUBLIC_SITE_BASE_URL, SITE_DISPLAY_NAME
from ..db.connection import get_configured_db_engine
from .academic_service import china_now
from .todo_service import build_classroom_todo_overview, parse_datetime_input

# 只输出这个时间窗内的日程，避免 feed 无限膨胀。
FEED_PAST_DAYS = 7
FEED_FUTURE_DAYS = 120

_SCHEMA_READY = False


def ensure_calendar_feed_schema(conn: Any) -> None:
    global _SCHEMA_READY
    if _SCHEMA_READY:
        return
    engine = get_configured_db_engine()
    id_column = (
        "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
        if engine == "postgres"
        else "id INTEGER PRIMARY KEY AUTOINCREMENT"
    )
    conn.execute(
        f"""
        CREATE TABLE IF NOT EXISTS calendar_feed_tokens (
            {id_column},
            user_role TEXT NOT NULL,
            user_pk INTEGER NOT NULL,
            token TEXT NOT NULL UNIQUE,
            created_at TEXT NOT NULL,
            revoked_at TEXT
        )
        """
    )
    conn.execute(
        """
        CREATE INDEX IF NOT EXISTS idx_calendar_feed_tokens_user
        ON calendar_feed_tokens (user_role, user_pk)
        """
    )
    _SCHEMA_READY = True


def _now_iso() -> str:
    return china_now().replace(tzinfo=None).isoformat(timespec="seconds")


def get_or_create_feed_token(conn: Any, *, role: str, user_pk: int) -> str:
    ensure_calendar_feed_schema(conn)
    normalized_role = str(role or "").strip().lower()
    row = conn.execute(
        """
        SELECT token FROM calendar_feed_tokens
        WHERE user_role = ? AND user_pk = ? AND revoked_at IS NULL
        ORDER BY id DESC LIMIT 1
        """,
        (normalized_role, int(user_pk)),
    ).fetchone()
    if row is not None:
        return str(row["token"])
    token = secrets.token_urlsafe(24)
    conn.execute(
        """
        INSERT INTO calendar_feed_tokens (user_role, user_pk, token, created_at)
        VALUES (?, ?, ?, ?)
        """,
        (normalized_role, int(user_pk), token, _now_iso()),
    )
    return token


def reset_feed_token(conn: Any, *, role: str, user_pk: int) -> str:
    """吊销旧链接并签发新 token（学生怀疑链接泄露时一键重置）。"""
    ensure_calendar_feed_schema(conn)
    normalized_role = str(role or "").strip().lower()
    conn.execute(
        """
        UPDATE calendar_feed_tokens SET revoked_at = ?
        WHERE user_role = ? AND user_pk = ? AND revoked_at IS NULL
        """,
        (_now_iso(), normalized_role, int(user_pk)),
    )
    token = secrets.token_urlsafe(24)
    conn.execute(
        """
        INSERT INTO calendar_feed_tokens (user_role, user_pk, token, created_at)
        VALUES (?, ?, ?, ?)
        """,
        (normalized_role, int(user_pk), token, _now_iso()),
    )
    return token


def resolve_feed_token(conn: Any, token: str) -> dict[str, Any] | None:
    ensure_calendar_feed_schema(conn)
    cleaned = str(token or "").strip()
    if not cleaned or len(cleaned) > 128:
        return None
    row = conn.execute(
        """
        SELECT user_role, user_pk FROM calendar_feed_tokens
        WHERE token = ? AND revoked_at IS NULL
        LIMIT 1
        """,
        (cleaned,),
    ).fetchone()
    if row is None:
        return None
    return {"role": str(row["user_role"]), "user_pk": int(row["user_pk"])}


def _load_user_offerings(conn: Any, *, role: str, user_pk: int) -> list[dict[str, Any]]:
    if role == "student":
        rows = conn.execute(
            """
            SELECT o.id, c.name AS course_name
            FROM class_offerings o
            JOIN students s ON (s.class_id = o.class_id OR EXISTS (SELECT 1 FROM class_offering_class_links cocl_m WHERE cocl_m.offering_id = o.id AND cocl_m.class_id = s.class_id))
            JOIN courses c ON c.id = o.course_id
            WHERE s.id = ?
              AND COALESCE(s.enrollment_status, 'active') = 'active'
            ORDER BY o.id
            """,
            (int(user_pk),),
        ).fetchall()
    else:
        rows = conn.execute(
            """
            SELECT o.id, c.name AS course_name
            FROM class_offerings o
            JOIN courses c ON c.id = o.course_id
            WHERE o.teacher_id = ?
            ORDER BY o.id
            """,
            (int(user_pk),),
        ).fetchall()
    return [dict(row) for row in rows]


def _ics_escape(value: Any) -> str:
    text = str(value or "")
    return (
        text.replace("\\", "\\\\")
        .replace(";", "\\;")
        .replace(",", "\\,")
        .replace("\r\n", "\\n")
        .replace("\n", "\\n")
    )


def _fold_line(line: str) -> str:
    """RFC5545 行折叠：每物理行 ≤75 字节，续行以空格开头。
    按字符累积字节预算，绝不切开多字节 UTF-8 字符。"""
    if len(line.encode("utf-8")) <= 75:
        return line
    parts: list[str] = []
    current = ""
    for char in line:
        candidate = current + char
        if len(candidate.encode("utf-8")) > 75:
            parts.append(current)
            current = " " + char
        else:
            current = candidate
    if current:
        parts.append(current)
    return "\r\n".join(parts)


def _format_local_dt(value: datetime) -> str:
    return value.strftime("%Y%m%dT%H%M%S")


def _absolute_url(link_url: str) -> str:
    raw = str(link_url or "").strip()
    if not raw:
        return ""
    if raw.startswith(("http://", "https://")):
        return raw
    base = str(PUBLIC_SITE_BASE_URL or "").rstrip("/")
    return f"{base}{raw if raw.startswith('/') else '/' + raw}" if base else raw


def build_ics_for_user(conn: Any, *, role: str, user_pk: int) -> str:
    normalized_role = str(role or "").strip().lower()
    user = {"id": int(user_pk), "role": normalized_role}
    now = china_now().replace(tzinfo=None)
    window_start = now - timedelta(days=FEED_PAST_DAYS)
    window_end = now + timedelta(days=FEED_FUTURE_DAYS)
    dtstamp = datetime.utcnow().strftime("%Y%m%dT%H%M%SZ")

    lines: list[str] = [
        "BEGIN:VCALENDAR",
        "VERSION:2.0",
        f"PRODID:-//{SITE_DISPLAY_NAME}//calendar-feed//CN",
        "CALSCALE:GREGORIAN",
        "METHOD:PUBLISH",
        f"X-WR-CALNAME:{_ics_escape(str(SITE_DISPLAY_NAME) + ' 我的日程')}",
        "X-WR-TIMEZONE:Asia/Shanghai",
    ]

    for offering in _load_user_offerings(conn, role=normalized_role, user_pk=user_pk):
        offering_id = int(offering["id"])
        course_name = str(offering.get("course_name") or "课程")
        try:
            overview = build_classroom_todo_overview(
                conn, class_offering_id=offering_id, user=user
            )
        except Exception:
            # 单个课堂的数据问题不应拖垮整个 feed。
            continue
        for item in overview.get("items") or []:
            due = parse_datetime_input(item.get("due_at")) if item.get("due_at") else None
            if due is None or not (window_start <= due <= window_end):
                continue
            source_type = str(item.get("source_type") or "item")
            # 截止类事件：已完成的不再打扰；上课安排始终保留。
            if source_type != "lesson" and item.get("is_completed"):
                continue
            title = str(item.get("title") or "日程")
            subtitle = str(item.get("subtitle") or "截止")
            status_label = str(item.get("status_label") or "")
            url = _absolute_url(str(item.get("link_url") or ""))
            uid = (
                f"lanshare-{normalized_role}{user_pk}-{offering_id}"
                f"-{source_type}-{item.get('source_id')}@lanshare"
            )
            lines.append("BEGIN:VEVENT")
            lines.append(f"UID:{_ics_escape(uid)}")
            lines.append(f"DTSTAMP:{dtstamp}")
            if source_type == "lesson":
                lines.append(f"DTSTART;VALUE=DATE:{due.strftime('%Y%m%d')}")
                lines.append(f"SUMMARY:{_ics_escape(f'【{course_name}】{title}')}")
            else:
                lines.append(f"DTSTART:{_format_local_dt(due)}")
                lines.append(f"SUMMARY:{_ics_escape(f'【{course_name}】{title}（{subtitle}）')}")
            description_parts = [part for part in (status_label, url) if part]
            if description_parts:
                lines.append(f"DESCRIPTION:{_ics_escape('；'.join(description_parts))}")
            if url:
                lines.append(f"URL:{_ics_escape(url)}")
            lines.append("END:VEVENT")

    lines.append("END:VCALENDAR")
    return "\r\n".join(_fold_line(line) for line in lines) + "\r\n"
