"""学生学分币（可消费积分）与兑换商店。

与修为分严格分离：修为是成绩性数值（只增，不可消费）；学分币是行为激励
货币，账本式记账（余额 = SUM(delta)），赚取按 (kind, ref) 幂等，消费需余额充足。

扩展方式：
- 赚取规则：调用 ``award_points_once``（新场景只需选好幂等 ref）；
- 商店商品：往 ``SHOP_ITEMS`` 加定义 + 在 ``EFFECT_HANDLERS`` 注册效果函数，
  效果失败不扣费（先执行效果、后记账，同一事务内）。
"""

from __future__ import annotations

from typing import Any, Callable

from ..db.connection import get_configured_db_engine
from .academic_service import china_now

_SCHEMA_READY = False

# 赚取规则（展示与实现共用一份口径）。
EARN_RULES: tuple[dict[str, Any], ...] = (
    {"kind": "daily_active", "amount": 10, "label": "每日首次学习", "description": "当天第一次在平台学习自动 +10"},
    {"kind": "badge_unlock", "amount": 50, "label": "解锁成就徽章", "description": "每解锁一枚徽章 +50"},
)
EARN_AMOUNTS = {rule["kind"]: int(rule["amount"]) for rule in EARN_RULES}

SHOP_ITEMS: tuple[dict[str, Any], ...] = (
    {
        "key": "streak_repair_card",
        "name": "补签卡",
        "icon": "🩹",
        "cost": 100,
        "description": "缝合最近 7 天内的一个断签缺口，把断掉的连续学习天数接回来。",
        "effect": "streak_repair",
    },
)
SHOP_INDEX = {item["key"]: item for item in SHOP_ITEMS}


def ensure_points_schema(conn: Any) -> None:
    global _SCHEMA_READY
    if _SCHEMA_READY:
        return
    id_column = (
        "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
        if get_configured_db_engine() == "postgres"
        else "id INTEGER PRIMARY KEY AUTOINCREMENT"
    )
    conn.execute(
        f"""
        CREATE TABLE IF NOT EXISTS student_point_ledger (
            {id_column},
            student_id INTEGER NOT NULL,
            delta INTEGER NOT NULL,
            reason_kind TEXT NOT NULL,
            reason_ref TEXT NOT NULL DEFAULT '',
            note TEXT NOT NULL DEFAULT '',
            created_at TEXT NOT NULL
        )
        """
    )
    conn.execute(
        """
        CREATE INDEX IF NOT EXISTS idx_student_point_ledger_student
        ON student_point_ledger (student_id, id)
        """
    )
    _SCHEMA_READY = True


def _now_iso() -> str:
    return china_now().replace(tzinfo=None).isoformat(timespec="seconds")


def get_points_balance(conn: Any, student_id: int) -> int:
    ensure_points_schema(conn)
    row = conn.execute(
        "SELECT COALESCE(SUM(delta), 0) AS balance FROM student_point_ledger WHERE student_id = ?",
        (int(student_id),),
    ).fetchone()
    return int(row["balance"] or 0)


def award_points_once(conn: Any, student_id: int, *, kind: str, ref: str, amount: int | None = None, note: str = "") -> bool:
    """按 (student, kind, ref) 幂等地加分；已加过返回 False。"""
    ensure_points_schema(conn)
    normalized_kind = str(kind or "").strip()
    normalized_ref = str(ref or "").strip()
    if not normalized_kind or not normalized_ref:
        return False
    value = int(amount if amount is not None else EARN_AMOUNTS.get(normalized_kind, 0))
    if value <= 0:
        return False
    existing = conn.execute(
        "SELECT 1 FROM student_point_ledger WHERE student_id = ? AND reason_kind = ? AND reason_ref = ? LIMIT 1",
        (int(student_id), normalized_kind, normalized_ref),
    ).fetchone()
    if existing is not None:
        return False
    conn.execute(
        """
        INSERT INTO student_point_ledger (student_id, delta, reason_kind, reason_ref, note, created_at)
        VALUES (?, ?, ?, ?, ?, ?)
        """,
        (int(student_id), value, normalized_kind, normalized_ref, str(note or ""), _now_iso()),
    )
    return True


def _spend_points(conn: Any, student_id: int, *, amount: int, kind: str, ref: str, note: str) -> dict[str, Any]:
    balance = get_points_balance(conn, student_id)
    if balance < amount:
        return {"ok": False, "message": f"学分币不足：需要 {amount}，当前 {balance}。", "balance": balance}
    conn.execute(
        """
        INSERT INTO student_point_ledger (student_id, delta, reason_kind, reason_ref, note, created_at)
        VALUES (?, ?, ?, ?, ?, ?)
        """,
        (int(student_id), -int(amount), str(kind), str(ref), str(note or ""), _now_iso()),
    )
    return {"ok": True, "balance": balance - int(amount)}


def _effect_streak_repair(conn: Any, student_id: int) -> dict[str, Any]:
    from .student_streak_service import repair_missed_day

    result = repair_missed_day(conn, student_id)
    if not result.get("repaired"):
        return {"ok": False, "message": str(result.get("reason") or "当前没有可补的断签缺口。")}
    return {
        "ok": True,
        "message": f"已补签 {result.get('repaired_date')}，连续学习恢复为 {result.get('current_streak')} 天。",
        "detail": result,
    }


EFFECT_HANDLERS: dict[str, Callable[[Any, int], dict[str, Any]]] = {
    "streak_repair": _effect_streak_repair,
}


def redeem_shop_item(conn: Any, student_id: int, item_key: str) -> dict[str, Any]:
    """兑换商品：效果成功才扣费（同事务，调用方负责 commit/rollback）。"""
    ensure_points_schema(conn)
    item = SHOP_INDEX.get(str(item_key or "").strip())
    if item is None:
        return {"ok": False, "message": "商品不存在。"}
    balance = get_points_balance(conn, student_id)
    cost = int(item["cost"])
    if balance < cost:
        return {"ok": False, "message": f"学分币不足：需要 {cost}，当前 {balance}。", "balance": balance}

    handler = EFFECT_HANDLERS.get(str(item["effect"]))
    if handler is None:
        return {"ok": False, "message": "商品效果暂不可用。"}
    effect = handler(conn, int(student_id))
    if not effect.get("ok"):
        return {"ok": False, "message": str(effect.get("message") or "兑换条件不满足。"), "balance": balance}

    spend_ref = f"{item['key']}:{_now_iso()}"
    spend = _spend_points(
        conn,
        student_id,
        amount=cost,
        kind="shop_redeem",
        ref=spend_ref,
        note=f"兑换{item['name']}",
    )
    if not spend["ok"]:
        return spend
    return {
        "ok": True,
        "message": str(effect.get("message") or f"已兑换{item['name']}。"),
        "balance": spend["balance"],
        "item_key": item["key"],
    }


def list_point_ledger(conn: Any, student_id: int, *, limit: int = 30) -> list[dict[str, Any]]:
    ensure_points_schema(conn)
    rows = conn.execute(
        """
        SELECT delta, reason_kind, note, created_at
        FROM student_point_ledger
        WHERE student_id = ?
        ORDER BY id DESC
        LIMIT ?
        """,
        (int(student_id), max(1, min(int(limit), 100))),
    ).fetchall()
    kind_labels = {
        "daily_active": "每日学习",
        "badge_unlock": "成就徽章",
        "shop_redeem": "商店兑换",
    }
    return [
        {
            "delta": int(row["delta"]),
            "kind": str(row["reason_kind"]),
            "kind_label": kind_labels.get(str(row["reason_kind"]), str(row["reason_kind"])),
            "note": str(row["note"] or ""),
            "created_at": str(row["created_at"] or "")[:16].replace("T", " "),
        }
        for row in rows
    ]


def build_points_home(conn: Any, student_id: int) -> dict[str, Any]:
    """商店页数据：余额 + 赚取规则 + 商品 + 最近流水。"""
    balance = get_points_balance(conn, student_id)
    return {
        "balance": balance,
        "earn_rules": [dict(rule) for rule in EARN_RULES],
        "items": [
            {**{k: v for k, v in item.items() if k != "effect"}, "affordable": balance >= int(item["cost"])}
            for item in SHOP_ITEMS
        ],
        "ledger": list_point_ledger(conn, student_id),
    }
