"""学生成就徽章系统。

离散成就（徽章）与连续数值的修为体系互补：条件全部从既有数据表推导，
评定幂等（UNIQUE 约束 + 先查后插），解锁时发一条消息中心通知（按徽章去重）。

扩展方式：往 ``BADGES`` 注册表追加定义 + 在 ``_compute_facts`` 里补一个事实数字，
其余（评定/通知/成就墙/进度提示）自动生效。未来事件总线可在任何领域事件后
调用 ``evaluate_and_award`` 而无需改这里的结构。
"""

from __future__ import annotations

from typing import Any

from ..db.connection import get_configured_db_engine
from .academic_service import china_now
from .student_streak_service import ensure_streak_schema

_SCHEMA_READY = False

# 徽章注册表：threshold 作用于 facts[fact_key]，达到即解锁。
BADGES: tuple[dict[str, Any], ...] = (
    {"key": "streak_3", "name": "三日之约", "description": "连续学习 3 天", "icon": "🔥", "tier": "bronze", "fact_key": "longest_streak", "threshold": 3},
    {"key": "streak_7", "name": "七日筑基", "description": "连续学习 7 天", "icon": "⚡", "tier": "silver", "fact_key": "longest_streak", "threshold": 7},
    {"key": "streak_30", "name": "月度苦修", "description": "连续学习 30 天", "icon": "🌙", "tier": "gold", "fact_key": "longest_streak", "threshold": 30},
    {"key": "first_submission", "name": "初试锋芒", "description": "完成第一次作业/考试提交", "icon": "✍️", "tier": "bronze", "fact_key": "submission_count", "threshold": 1},
    {"key": "submissions_10", "name": "十全十美", "description": "累计提交 10 次任务", "icon": "📚", "tier": "silver", "fact_key": "submission_count", "threshold": 10},
    {"key": "high_score_90", "name": "一鸣惊人", "description": "单次成绩达到 90 分", "icon": "🏆", "tier": "silver", "fact_key": "best_score", "threshold": 90},
    {"key": "activity_100", "name": "课堂常客", "description": "课堂活跃动作累计 100 次", "icon": "💬", "tier": "bronze", "fact_key": "activity_count", "threshold": 100},
)

TIER_LABELS = {"bronze": "青铜", "silver": "白银", "gold": "黄金"}


def ensure_achievement_schema(conn: Any) -> None:
    global _SCHEMA_READY
    if _SCHEMA_READY:
        return
    id_column = (
        "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
        if get_configured_db_engine() == "postgres"
        else "id INTEGER PRIMARY KEY AUTOINCREMENT"
    )
    conn.execute(
        f"""
        CREATE TABLE IF NOT EXISTS student_achievements (
            {id_column},
            student_id INTEGER NOT NULL,
            badge_key TEXT NOT NULL,
            earned_at TEXT NOT NULL,
            UNIQUE (student_id, badge_key)
        )
        """
    )
    _SCHEMA_READY = True


def _compute_facts(conn: Any, student_id: int) -> dict[str, float]:
    """成就条件的事实数字，全部为便宜的单表聚合。"""
    ensure_streak_schema(conn)
    facts: dict[str, float] = {"longest_streak": 0, "submission_count": 0, "best_score": 0, "activity_count": 0}

    row = conn.execute(
        "SELECT longest_streak FROM student_activity_streaks WHERE student_id = ?",
        (int(student_id),),
    ).fetchone()
    if row is not None:
        facts["longest_streak"] = int(row["longest_streak"] or 0)

    row = conn.execute(
        """
        SELECT COUNT(*) AS n, MAX(CASE WHEN status = 'graded' THEN score END) AS best
        FROM submissions
        WHERE student_pk_id = ? AND COALESCE(is_absence_score, 0) = 0
        """,
        (int(student_id),),
    ).fetchone()
    if row is not None:
        facts["submission_count"] = int(row["n"] or 0)
        try:
            facts["best_score"] = float(row["best"]) if row["best"] is not None else 0
        except (TypeError, ValueError):
            facts["best_score"] = 0

    row = conn.execute(
        """
        SELECT COALESCE(SUM(total_activity_count), 0) AS total
        FROM classroom_behavior_states
        WHERE user_pk = ? AND user_role = 'student'
        """,
        (int(student_id),),
    ).fetchone()
    if row is not None:
        facts["activity_count"] = int(row["total"] or 0)
    return facts


def _earned_keys(conn: Any, student_id: int) -> dict[str, str]:
    rows = conn.execute(
        "SELECT badge_key, earned_at FROM student_achievements WHERE student_id = ?",
        (int(student_id),),
    ).fetchall()
    return {str(row["badge_key"]): str(row["earned_at"] or "") for row in rows}


def evaluate_and_award(conn: Any, student_id: int) -> list[dict[str, Any]]:
    """评定并颁发新达成的徽章；返回本次新解锁列表。幂等、best-effort 通知。"""
    ensure_achievement_schema(conn)
    earned = _earned_keys(conn, student_id)
    facts = _compute_facts(conn, student_id)
    now_iso = china_now().replace(tzinfo=None).isoformat(timespec="seconds")

    newly_awarded: list[dict[str, Any]] = []
    for badge in BADGES:
        if badge["key"] in earned:
            continue
        if facts.get(badge["fact_key"], 0) < badge["threshold"]:
            continue
        conn.execute(
            """
            INSERT INTO student_achievements (student_id, badge_key, earned_at)
            VALUES (?, ?, ?)
            """,
            (int(student_id), badge["key"], now_iso),
        )
        newly_awarded.append({**badge, "earned_at": now_iso})
        try:
            from .student_points_service import award_points_once

            award_points_once(
                conn,
                int(student_id),
                kind="badge_unlock",
                ref=str(badge["key"]),
                note=f"解锁徽章「{badge['name']}」",
            )
        except Exception as exc:
            print(f"[ACHIEVEMENT] badge points award failed: {exc}")
        try:
            from .message_center_service import create_achievement_notification

            create_achievement_notification(
                conn,
                student_id=int(student_id),
                badge_key=badge["key"],
                badge_name=f"{badge['icon']} {badge['name']}",
                badge_description=badge["description"],
            )
        except Exception as exc:
            # 通知失败不回滚徽章本身。
            print(f"[ACHIEVEMENT] badge notification failed: {exc}")
    return newly_awarded


def _progress_hint(badge: dict[str, Any], facts: dict[str, float]) -> str:
    value = facts.get(badge["fact_key"], 0)
    threshold = badge["threshold"]
    if value >= threshold:
        return "已达成"
    if badge["fact_key"] == "best_score":
        return f"当前最高 {value:g} 分 / 需要 {threshold} 分"
    return f"进度 {int(value)} / {threshold}"


def build_achievement_wall(conn: Any, student_id: int) -> dict[str, Any]:
    """成就墙数据：先评定补发，再合并注册表与已获得状态。"""
    newly_awarded = evaluate_and_award(conn, student_id)
    earned = _earned_keys(conn, student_id)
    facts = _compute_facts(conn, student_id)

    badges = []
    for badge in BADGES:
        earned_at = earned.get(badge["key"], "")
        badges.append(
            {
                "key": badge["key"],
                "name": badge["name"],
                "description": badge["description"],
                "icon": badge["icon"],
                "tier": badge["tier"],
                "tier_label": TIER_LABELS.get(badge["tier"], badge["tier"]),
                "earned": bool(earned_at),
                "earned_at": earned_at[:10],
                "progress_hint": _progress_hint(badge, facts),
            }
        )
    # 已获得的排前面，组内保持注册表顺序（稳定排序）。
    badges.sort(key=lambda item: (0 if item["earned"] else 1))
    return {
        "badges": badges,
        "earned_count": sum(1 for item in badges if item["earned"]),
        "total_count": len(badges),
        "newly_awarded": newly_awarded,
    }
