"""小程序订阅消息：持久化发送任务 + scheduler 发送 worker（批次 B / C07、C08）。

业务侧（截止扫描、批改完成、教师催交）只在自己的短事务里 ``enqueue``
一行任务，绝不在请求/批改事务内调用微信。scheduler 容器里的
``dispatch_subscribe_tasks`` 原子领取任务后在事务外发送。

状态机（``mp_subscribe_tasks.state``）::

    pending → processing → succeeded
                         → no_binding / no_grant / rejected   （可被同事件重新入队唤醒）
                         → expired                            （截止提醒过了截止时间）
                         → unknown                            （已发出但结果未知，不重发）
                         → failed                             （确定失败或重试耗尽）
    processing → pending（暂时失败，指数退避）

额度语义：领取时原子预扣一次授权（``remaining > 0``），只有"确定没送达"
才退还；结果未知按已用处理（微信侧大概率已扣）。同一用户同一模板只剩
一次授权时，两条任务不可能同时拿到额度。
"""

from __future__ import annotations

import hashlib
import json
import os
import socket
import uuid
from datetime import datetime, timedelta
from typing import Any, Callable, Optional

import httpx

from ..db.connection import get_configured_db_engine, get_db_connection
from .wechat_mp_subscribe_service import (
    TEMPLATES,
    _SUBSCRIBE_SEND_URL,
    _clear_grants,
    _find_openid,
    _get_access_token,
    ensure_mp_subscribe_schema,
)

DISPATCH_TASK_KIND = "mp_subscribe_dispatch"
DISPATCH_INTERVAL_SECONDS = 30
DISPATCH_BATCH_SIZE = 10
DISPATCH_TIME_BUDGET_SECONDS = 40
LEASE_SECONDS = 300
MAX_ATTEMPTS = 4
RETRY_BASE_SECONDS = 60

STATE_PENDING = "pending"
STATE_PROCESSING = "processing"
STATE_SUCCEEDED = "succeeded"
STATE_NO_BINDING = "no_binding"
STATE_NO_GRANT = "no_grant"
STATE_REJECTED = "rejected"
STATE_EXPIRED = "expired"
STATE_UNKNOWN = "unknown"
STATE_FAILED = "failed"

# 同一事件再次入队时可被唤醒的终态：原因可能已消除（用户新授权/新绑定）。
REARMABLE_STATES = (STATE_NO_BINDING, STATE_NO_GRANT, STATE_REJECTED)
# 微信"系统繁忙/频率"类错误码：退还额度后按退避重试。
TEMPORARY_ERRCODES = frozenset({-1, 45009, 45011})
TOKEN_ERRCODES = frozenset({40001, 42001})
REJECTED_ERRCODE = 43101

_SCHEMA_READY = False

Transport = Callable[[str, dict[str, Any]], dict[str, Any]]
TokenProvider = Callable[[bool], str]


class SendNotAttempted(Exception):
    """请求未离开本机（连接失败等），可安全重试且额度应退还。"""


class SendOutcomeUnknown(Exception):
    """请求可能已到达微信（读超时等），不得重发。"""


def _now() -> datetime:
    return datetime.now()


def _iso(value: datetime) -> str:
    return value.isoformat(timespec="seconds")


def ensure_mp_subscribe_task_schema(conn: Any) -> None:
    """任务表 + 授权上报幂等表（engine-aware、幂等，不进 REQUIRED 集）。"""
    global _SCHEMA_READY
    if _SCHEMA_READY:
        return
    ensure_mp_subscribe_schema(conn)
    engine = get_configured_db_engine()
    id_column = (
        "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
        if engine == "postgres"
        else "id INTEGER PRIMARY KEY AUTOINCREMENT"
    )
    conn.execute(
        f"""
        CREATE TABLE IF NOT EXISTS mp_subscribe_tasks (
            {id_column},
            event_key TEXT NOT NULL UNIQUE,
            group_key TEXT NOT NULL DEFAULT '',
            template_key TEXT NOT NULL,
            user_role TEXT NOT NULL,
            user_pk INTEGER NOT NULL,
            values_json TEXT NOT NULL,
            page TEXT NOT NULL,
            state TEXT NOT NULL,
            attempts INTEGER NOT NULL DEFAULT 0,
            next_attempt_at TEXT NOT NULL,
            expires_at TEXT,
            lease_owner TEXT,
            lease_until TEXT,
            last_error TEXT,
            created_at TEXT NOT NULL,
            updated_at TEXT NOT NULL,
            finished_at TEXT
        )
        """
    )
    conn.execute(
        "CREATE INDEX IF NOT EXISTS idx_mp_subscribe_tasks_due "
        "ON mp_subscribe_tasks (state, next_attempt_at)"
    )
    conn.execute(
        "CREATE INDEX IF NOT EXISTS idx_mp_subscribe_tasks_group "
        "ON mp_subscribe_tasks (group_key)"
    )
    conn.execute(
        f"""
        CREATE TABLE IF NOT EXISTS mp_subscribe_reports (
            {id_column},
            report_id TEXT NOT NULL UNIQUE,
            user_role TEXT NOT NULL,
            user_pk INTEGER NOT NULL,
            created_at TEXT NOT NULL
        )
        """
    )
    _SCHEMA_READY = True


def reset_task_schema_ready_for_tests() -> None:
    global _SCHEMA_READY
    _SCHEMA_READY = False


# ---------------------------------------------------------------------------
# 入队（业务事务内调用：只有少量读 + 一次写，不做网络）
# ---------------------------------------------------------------------------

def _insert_ignore(conn: Any, table: str, columns: tuple[str, ...], conflict_column: str, params: tuple) -> bool:
    """按引擎 insert-ignore，``?`` 占位走连接门面的 qmark 转换，返回是否插入。

    不能用 ``db.sql`` 里的 insert-ignore 生成器：它的 postgres 输出是 ``$n`` 占位，
    运行时连接门面执行会报 "0 placeholders"。批次 B 之前的去重占位正是因此在生产
    PostgreSQL 上每次抛错、被吞掉后返回"已发过"，订阅消息从未真正发出。
    """
    column_sql = ", ".join(columns)
    values_sql = ", ".join("?" for _ in columns)
    if get_configured_db_engine() == "postgres":
        sql = f"INSERT INTO {table} ({column_sql}) VALUES ({values_sql}) ON CONFLICT ({conflict_column}) DO NOTHING"
    else:
        sql = f"INSERT OR IGNORE INTO {table} ({column_sql}) VALUES ({values_sql})"
    return bool(conn.execute(sql, params).rowcount)


def _has_grant(conn: Any, user_role: str, user_pk: int, template_key: str) -> bool:
    row = conn.execute(
        """
        SELECT remaining FROM mp_subscribe_grants
        WHERE user_role = ? AND user_pk = ? AND template_key = ?
        """,
        (user_role, int(user_pk), template_key),
    ).fetchone()
    return bool(row) and int(row["remaining"] or 0) > 0


def enqueue_subscribe_message(
    conn: Any,
    *,
    event_key: str,
    user_role: str,
    user_pk: int,
    template_key: str,
    values: dict[str, str],
    page: str = "pages/home/index",
    group_key: str = "",
    expires_at: Optional[str] = None,
) -> str:
    """登记一条待发订阅消息，返回 queued / no_binding / no_grant / rearmed / duplicate。

    无绑定/无额度的直接记为对应终态（worker 不必再处理）；同一事件
    再次入队时，若先前停在可唤醒终态且原因已消除，则重新排队。
    """
    if template_key not in TEMPLATES:
        raise ValueError(f"unknown subscribe template: {template_key}")
    ensure_mp_subscribe_task_schema(conn)
    now = _iso(_now())
    if not _find_openid(conn, user_role, user_pk):
        initial = STATE_NO_BINDING
    elif not _has_grant(conn, user_role, user_pk, template_key):
        initial = STATE_NO_GRANT
    else:
        initial = STATE_PENDING
    values_json = json.dumps(values, ensure_ascii=False, sort_keys=True)
    inserted = _insert_ignore(
        conn,
        "mp_subscribe_tasks",
        (
            "event_key", "group_key", "template_key", "user_role", "user_pk", "values_json",
            "page", "state", "attempts", "next_attempt_at", "expires_at", "created_at",
            "updated_at", "finished_at",
        ),
        "event_key",
        (
            event_key, group_key, template_key, user_role, int(user_pk), values_json,
            page, initial, 0, now, expires_at, now, now,
            None if initial == STATE_PENDING else now,
        ),
    )
    if inserted:
        return "queued" if initial == STATE_PENDING else initial
    if initial != STATE_PENDING:
        return initial
    placeholders = ", ".join("?" for _ in REARMABLE_STATES)
    rearmed = conn.execute(
        f"""
        UPDATE mp_subscribe_tasks
        SET state = ?, attempts = 0, next_attempt_at = ?, values_json = ?, page = ?,
            expires_at = ?, last_error = NULL, finished_at = NULL, updated_at = ?
        WHERE event_key = ? AND state IN ({placeholders})
        """,
        (STATE_PENDING, now, values_json, page, expires_at, now, event_key, *REARMABLE_STATES),
    )
    return "rearmed" if rearmed.rowcount else "duplicate"


def graded_event_key(submission_id: Any, score: Any, feedback_md: Any) -> str:
    """同一份提交的同一批改结果只推一次；分数或评语变化才再推。"""
    digest = hashlib.sha256(
        json.dumps([str(score), str(feedback_md or "")], ensure_ascii=False).encode("utf-8")
    ).hexdigest()[:16]
    return f"graded:{submission_id}:{digest}"


def nudge_group_key(assignment_id: Any, day: Optional[str] = None) -> str:
    return f"nudge:{assignment_id}:{day or _now().date().isoformat()}"


# ---------------------------------------------------------------------------
# 授权上报幂等 + 额度查询
# ---------------------------------------------------------------------------

def claim_subscribe_report(conn: Any, *, report_id: str, user_role: str, user_pk: int) -> bool:
    """同一 report_id 只记一次授权（客户端重试/重复上报不虚增额度）。"""
    ensure_mp_subscribe_task_schema(conn)
    return _insert_ignore(
        conn,
        "mp_subscribe_reports",
        ("report_id", "user_role", "user_pk", "created_at"),
        "report_id",
        (report_id, user_role, int(user_pk), _iso(_now())),
    )


def load_subscribe_balances(conn: Any, *, user_role: str, user_pk: int) -> dict[str, int]:
    ensure_mp_subscribe_task_schema(conn)
    rows = conn.execute(
        "SELECT template_key, remaining FROM mp_subscribe_grants WHERE user_role = ? AND user_pk = ?",
        (user_role, int(user_pk)),
    ).fetchall()
    balances = {key: 0 for key in TEMPLATES}
    for row in rows:
        if row["template_key"] in balances:
            balances[row["template_key"]] = max(0, int(row["remaining"] or 0))
    return balances


# ---------------------------------------------------------------------------
# 状态汇总（教师催交结果）
# ---------------------------------------------------------------------------

def summarize_group(conn: Any, group_key: str) -> dict[str, Any]:
    ensure_mp_subscribe_task_schema(conn)
    rows = conn.execute(
        """
        SELECT state, COUNT(*) AS total, MAX(updated_at) AS last_update
        FROM mp_subscribe_tasks WHERE group_key = ?
        GROUP BY state
        """,
        (group_key,),
    ).fetchall()
    counts = {str(row["state"]): int(row["total"]) for row in rows}
    return {
        "group_key": group_key,
        "total": sum(counts.values()),
        "delivered": counts.get(STATE_SUCCEEDED, 0),
        "in_flight": counts.get(STATE_PENDING, 0) + counts.get(STATE_PROCESSING, 0),
        "no_grant": counts.get(STATE_NO_GRANT, 0) + counts.get(STATE_REJECTED, 0),
        "no_binding": counts.get(STATE_NO_BINDING, 0),
        "unknown": counts.get(STATE_UNKNOWN, 0),
        "failed": counts.get(STATE_FAILED, 0) + counts.get(STATE_EXPIRED, 0),
        "by_state": counts,
        "last_update": max((str(row["last_update"] or "") for row in rows), default=""),
    }


# ---------------------------------------------------------------------------
# 发送 worker
# ---------------------------------------------------------------------------

def _default_transport(token: str, body: dict[str, Any]) -> dict[str, Any]:
    try:
        response = httpx.post(f"{_SUBSCRIBE_SEND_URL}?access_token={token}", json=body, timeout=8.0)
    except (httpx.ConnectError, httpx.ConnectTimeout) as exc:
        raise SendNotAttempted(type(exc).__name__) from None
    except httpx.HTTPError as exc:
        # 读/写超时等：请求可能已被处理。异常文本含带 token 的 URL，绝不外泄。
        raise SendOutcomeUnknown(type(exc).__name__) from None
    try:
        return response.json()
    except ValueError:
        raise SendOutcomeUnknown(f"non-json http {response.status_code}") from None


def _default_token_provider(force_refresh: bool) -> str:
    return _get_access_token(force_refresh=force_refresh)


def _claim(limit: int, worker: str, now: datetime) -> list[dict[str, Any]]:
    now_text = _iso(now)
    lease_until = _iso(now + timedelta(seconds=LEASE_SECONDS))
    with get_db_connection() as conn:
        ensure_mp_subscribe_task_schema(conn)
        if get_configured_db_engine() == "postgres":
            rows = conn.execute(
                """
                UPDATE mp_subscribe_tasks
                SET state = ?, lease_owner = ?, lease_until = ?, updated_at = ?
                WHERE id IN (
                    SELECT id FROM mp_subscribe_tasks
                    WHERE (state = ? AND next_attempt_at <= ?)
                       OR (state = ? AND lease_until <= ?)
                    ORDER BY next_attempt_at ASC, id ASC
                    LIMIT ?
                    FOR UPDATE SKIP LOCKED
                )
                RETURNING *
                """,
                (STATE_PROCESSING, worker, lease_until, now_text,
                 STATE_PENDING, now_text, STATE_PROCESSING, now_text, limit),
            ).fetchall()
            conn.commit()
            return [dict(row) for row in rows]
        candidates = conn.execute(
            """
            SELECT id FROM mp_subscribe_tasks
            WHERE (state = ? AND next_attempt_at <= ?)
               OR (state = ? AND lease_until <= ?)
            ORDER BY next_attempt_at ASC, id ASC
            LIMIT ?
            """,
            (STATE_PENDING, now_text, STATE_PROCESSING, now_text, limit),
        ).fetchall()
        claimed = []
        for row in candidates:
            cursor = conn.execute(
                """
                UPDATE mp_subscribe_tasks
                SET state = ?, lease_owner = ?, lease_until = ?, updated_at = ?
                WHERE id = ? AND ((state = ? AND next_attempt_at <= ?) OR (state = ? AND lease_until <= ?))
                """,
                (STATE_PROCESSING, worker, lease_until, now_text, int(row["id"]),
                 STATE_PENDING, now_text, STATE_PROCESSING, now_text),
            )
            if cursor.rowcount:
                claimed.append(int(row["id"]))
        conn.commit()
        if not claimed:
            return []
        placeholders = ", ".join("?" for _ in claimed)
        return [
            dict(row)
            for row in conn.execute(
                f"SELECT * FROM mp_subscribe_tasks WHERE id IN ({placeholders}) ORDER BY id", claimed
            ).fetchall()
        ]


def _warn_if_lease_lost(cursor: Any, task: dict[str, Any], state: str) -> None:
    """租约已被他人接管（本 worker 停顿超过 LEASE_SECONDS）：结果写不回去，
    另一 worker 可能已重发。只在日志里留痕，供运维核对是否出现重复推送。"""
    if not cursor.rowcount:
        print(f"[MP_SUBSCRIBE] task {task['id']} lease lost before recording {state}; possible duplicate send")


def _finish(conn: Any, task: dict[str, Any], worker: str, state: str, error: str = "") -> None:
    now_text = _iso(_now())
    cursor = conn.execute(
        """
        UPDATE mp_subscribe_tasks
        SET state = ?, last_error = ?, lease_owner = NULL, lease_until = NULL,
            attempts = attempts + 1, updated_at = ?, finished_at = ?
        WHERE id = ? AND state = ? AND lease_owner = ?
        """,
        (state, error[:200] or None, now_text, now_text, int(task["id"]), STATE_PROCESSING, worker),
    )
    _warn_if_lease_lost(cursor, task, state)


def _retry_or_fail(conn: Any, task: dict[str, Any], worker: str, error: str) -> str:
    attempts = int(task.get("attempts") or 0) + 1
    if attempts >= MAX_ATTEMPTS:
        _finish(conn, task, worker, STATE_FAILED, error)
        return STATE_FAILED
    now = _now()
    delay = RETRY_BASE_SECONDS * (2 ** (attempts - 1))
    cursor = conn.execute(
        """
        UPDATE mp_subscribe_tasks
        SET state = ?, attempts = ?, next_attempt_at = ?, last_error = ?,
            lease_owner = NULL, lease_until = NULL, updated_at = ?
        WHERE id = ? AND state = ? AND lease_owner = ?
        """,
        (STATE_PENDING, attempts, _iso(now + timedelta(seconds=delay)), error[:200],
         _iso(now), int(task["id"]), STATE_PROCESSING, worker),
    )
    _warn_if_lease_lost(cursor, task, STATE_PENDING)
    return STATE_PENDING


def _reserve_grant(conn: Any, task: dict[str, Any]) -> bool:
    cursor = conn.execute(
        """
        UPDATE mp_subscribe_grants SET remaining = remaining - 1, updated_at = ?
        WHERE user_role = ? AND user_pk = ? AND template_key = ? AND remaining > 0
        """,
        (_iso(_now()), task["user_role"], int(task["user_pk"]), task["template_key"]),
    )
    return bool(cursor.rowcount)


def _refund_grant(conn: Any, task: dict[str, Any]) -> None:
    conn.execute(
        """
        UPDATE mp_subscribe_grants SET remaining = remaining + 1, updated_at = ?
        WHERE user_role = ? AND user_pk = ? AND template_key = ?
        """,
        (_iso(_now()), task["user_role"], int(task["user_pk"]), task["template_key"]),
    )


def _send(task: dict[str, Any], openid: str, transport: Transport, token_provider: TokenProvider) -> tuple[str, str]:
    """事务外调用微信。返回 (结果, 错误说明)；结果为终态或 "retry"。"""
    template = TEMPLATES[task["template_key"]]
    body = {
        "touser": openid,
        "template_id": template["template_id"],
        "page": task["page"],
        "data": {field: {"value": value} for field, value in json.loads(task["values_json"]).items()},
    }
    try:
        token = token_provider(False)
        if not token:
            return "retry", "no_token"
        payload = transport(token, body)
        errcode = int(payload.get("errcode") or 0)
        if errcode in TOKEN_ERRCODES:
            token = token_provider(True)
            if not token:
                return "retry", "no_token"
            payload = transport(token, body)
            errcode = int(payload.get("errcode") or 0)
    except SendNotAttempted as exc:
        return "retry", f"not sent: {exc}"
    except SendOutcomeUnknown as exc:
        return STATE_UNKNOWN, f"unknown: {exc}"
    except Exception as exc:  # 防御：任何意外都不能让任务永远卡在 processing
        return STATE_UNKNOWN, f"unexpected: {type(exc).__name__}"
    if errcode == 0:
        return STATE_SUCCEEDED, ""
    if errcode == REJECTED_ERRCODE:
        return STATE_REJECTED, f"errcode {errcode}"
    if errcode in TEMPORARY_ERRCODES or errcode in TOKEN_ERRCODES:
        return "retry", f"errcode {errcode}"
    return STATE_FAILED, f"errcode {errcode} {str(payload.get('errmsg') or '')[:80]}"


def _process_one(
    task: dict[str, Any], worker: str, transport: Transport, token_provider: TokenProvider, now: datetime
) -> str:
    expires_at = str(task.get("expires_at") or "")
    with get_db_connection() as conn:
        if expires_at and expires_at <= _iso(now):
            _finish(conn, task, worker, STATE_EXPIRED)
            conn.commit()
            return STATE_EXPIRED
        openid = _find_openid(conn, task["user_role"], int(task["user_pk"]))
        if not openid:
            _finish(conn, task, worker, STATE_NO_BINDING)
            conn.commit()
            return STATE_NO_BINDING
        if not _reserve_grant(conn, task):
            _finish(conn, task, worker, STATE_NO_GRANT)
            conn.commit()
            return STATE_NO_GRANT
        conn.commit()

    state, error = _send(task, openid, transport, token_provider)

    with get_db_connection() as conn:
        if state == STATE_REJECTED:
            _clear_grants(conn, task["user_role"], int(task["user_pk"]), task["template_key"])
            _finish(conn, task, worker, state, error)
        elif state in (STATE_SUCCEEDED, STATE_UNKNOWN):
            _finish(conn, task, worker, state, error)
        elif state == STATE_FAILED:
            _refund_grant(conn, task)
            _finish(conn, task, worker, state, error)
        else:
            _refund_grant(conn, task)
            state = _retry_or_fail(conn, task, worker, error)
        conn.commit()
    if error:
        print(f"[MP_SUBSCRIBE] task {task['id']} {task['template_key']} -> {state} ({error})")
    return state


def dispatch_subscribe_tasks(
    *,
    transport: Optional[Transport] = None,
    token_provider: Optional[TokenProvider] = None,
    batch_size: int = DISPATCH_BATCH_SIZE,
    time_budget_seconds: float = DISPATCH_TIME_BUDGET_SECONDS,
    clock: Callable[[], datetime] = _now,
) -> dict[str, int]:
    """领取到期任务并发送，直到队列空或用完时间预算。返回各结果计数。"""
    worker = f"{os.getenv('SCHEDULER_WORKER_ID') or socket.gethostname()}:{uuid.uuid4().hex[:12]}"
    send = transport or _default_transport
    tokens = token_provider or _default_token_provider
    started = clock()
    stats: dict[str, int] = {}
    while (clock() - started).total_seconds() < time_budget_seconds:
        now = clock()
        batch = _claim(max(1, int(batch_size)), worker, now)
        if not batch:
            break
        for task in batch:
            state = _process_one(task, worker, send, tokens, now)
            stats[state] = stats.get(state, 0) + 1
    return stats


def ensure_dispatch_task(conn: Any) -> int:
    from .scheduled_task_service import schedule_task

    ensure_mp_subscribe_task_schema(conn)
    return schedule_task(
        conn,
        task_kind=DISPATCH_TASK_KIND,
        run_at=_now() + timedelta(seconds=30),
        payload={},
        dedupe_key="mp:subscribe-dispatch",
        recurrence_seconds=DISPATCH_INTERVAL_SECONDS,
        title="MP subscribe message dispatch",
        priority=70,
        max_attempts=3,
        replace=False,
    )
