"""微信小程序订阅消息：模板注册表、授权额度、发送管线。

微信一次性订阅制：用户每点一次"允许"，对应模板获得一次下发额度。
本服务维护额度台账（``mp_subscribe_grants``，前端上报 accept 时 +1，
发送时 -1，用户拒收时清零），并用 ``mp_subscribe_sends`` 的
dedupe_key 保证同一事件绝不重复推送。

所有发送都是尽力而为：无额度/无绑定/接口失败只记日志，绝不阻断
上游业务（批改、截止扫描、催交）。模板 ID 非机密，默认值硬编码、
env 可覆盖（WECHAT_MP_TMPL_DEADLINE / _NUDGE / _GRADED）。
"""

from __future__ import annotations

import os
import threading
import time
from datetime import datetime
from typing import Any, Optional

import httpx

from ..db.connection import get_configured_db_engine
from ..db.sql import insert_ignore_sql
from .wechat_mp_service import get_wechat_mp_credentials

_STABLE_TOKEN_URL = "https://api.weixin.qq.com/cgi-bin/stable_token"
_SUBSCRIBE_SEND_URL = "https://api.weixin.qq.com/cgi-bin/message/subscribe/send"

# 模板注册表：key 是平台内部名，前端通过 /api/mp/subscribe/config 取 id。
TEMPLATES: dict[str, dict[str, str]] = {
    "deadline": {
        "template_id": os.getenv(
            "WECHAT_MP_TMPL_DEADLINE",
            "8LGiFyiqVLAntfn61aXwBZ2kChGXQseSq8eVaPGeafQ",
        ),
        "label": "作业截止提醒",
    },
    "nudge": {
        "template_id": os.getenv(
            "WECHAT_MP_TMPL_NUDGE",
            "1HlhCJsPfRfJwWCc4LBWmB0xiL28iVXZwM3VMBCUy2g",
        ),
        "label": "作业催交通知",
    },
    "graded": {
        "template_id": os.getenv(
            "WECHAT_MP_TMPL_GRADED",
            "Fft4anTP6EsGMTSSZ88x55iUsx4vIGUqU5xNpIYs4MM",
        ),
        "label": "作业批改完成通知",
    },
}

_SCHEMA_READY = False
_TOKEN_LOCK = threading.Lock()
_TOKEN_CACHE: dict[str, Any] = {"token": "", "expires_at": 0.0}


def _now_iso() -> str:
    return datetime.now().isoformat(timespec="seconds")


def ensure_mp_subscribe_schema(conn: Any) -> None:
    """两张 runtime 表（engine-aware、幂等，不进 REQUIRED 集）。"""
    global _SCHEMA_READY
    if _SCHEMA_READY:
        return
    engine = get_configured_db_engine()
    id_column = (
        "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
        if engine == "postgres"
        else "id INTEGER PRIMARY KEY AUTOINCREMENT"
    )
    conn.execute(
        f"""
        CREATE TABLE IF NOT EXISTS mp_subscribe_grants (
            {id_column},
            user_role TEXT NOT NULL,
            user_pk INTEGER NOT NULL,
            template_key TEXT NOT NULL,
            remaining INTEGER NOT NULL DEFAULT 0,
            updated_at TEXT NOT NULL,
            UNIQUE (user_role, user_pk, template_key)
        )
        """
    )
    conn.execute(
        f"""
        CREATE TABLE IF NOT EXISTS mp_subscribe_sends (
            {id_column},
            template_key TEXT NOT NULL,
            user_role TEXT NOT NULL,
            user_pk INTEGER NOT NULL,
            dedupe_key TEXT NOT NULL UNIQUE,
            sent_at TEXT NOT NULL
        )
        """
    )
    _SCHEMA_READY = True


def reset_schema_ready_for_tests() -> None:
    global _SCHEMA_READY
    _SCHEMA_READY = False


# ---------------------------------------------------------------------------
# 字段清洗：微信对每类字段有硬性长度/格式限制，超限整条发送失败。
# ---------------------------------------------------------------------------

def clamp_thing(value: Any, limit: int = 20) -> str:
    """thing.DATA：≤20 字符，超长截断加省略号；空值给占位符。"""
    text = str(value or "").strip().replace("\n", " ")
    if not text:
        return "—"
    if len(text) <= limit:
        return text
    return text[: limit - 1] + "…"


def clamp_phrase(value: Any) -> str:
    """phrase.DATA：≤5 字符的短语。"""
    text = str(value or "").strip()
    return (text[:5] or "已完成") if text else "已完成"


def clamp_number(value: Any) -> str:
    """number.DATA：纯数字字符串。"""
    try:
        number = float(value)
    except (TypeError, ValueError):
        return "0"
    return str(int(number)) if number == int(number) else f"{number:g}"


def format_wechat_datetime(value: Any) -> str:
    """date/time.DATA 接受 "2026年9月1日 23:59" 式格式。"""
    text = str(value or "").strip().replace("T", " ")
    try:
        parsed = datetime.fromisoformat(text)
    except ValueError:
        return text or "—"
    return f"{parsed.year}年{parsed.month}月{parsed.day}日 {parsed.hour:02d}:{parsed.minute:02d}"


# ---------------------------------------------------------------------------
# 授权额度台账
# ---------------------------------------------------------------------------

def record_subscribe_grants(
    conn: Any, *, user_role: str, user_pk: int, template_keys: list[str]
) -> dict[str, int]:
    """前端上报用户点了"允许"的模板，各自额度 +1。返回各 key 的最新余额。"""
    ensure_mp_subscribe_schema(conn)
    result: dict[str, int] = {}
    now = _now_iso()
    for key in template_keys:
        normalized = str(key or "").strip()
        if normalized not in TEMPLATES:
            continue
        row = conn.execute(
            """
            SELECT id, remaining FROM mp_subscribe_grants
            WHERE user_role = ? AND user_pk = ? AND template_key = ?
            """,
            (user_role, int(user_pk), normalized),
        ).fetchone()
        if row:
            remaining = int(row["remaining"]) + 1
            conn.execute(
                "UPDATE mp_subscribe_grants SET remaining = ?, updated_at = ? WHERE id = ?",
                (remaining, now, int(row["id"])),
            )
        else:
            remaining = 1
            conn.execute(
                """
                INSERT INTO mp_subscribe_grants (user_role, user_pk, template_key, remaining, updated_at)
                VALUES (?, ?, ?, ?, ?)
                """,
                (user_role, int(user_pk), normalized, remaining, now),
            )
        result[normalized] = remaining
    return result


def _consume_grant(conn: Any, user_role: str, user_pk: int, template_key: str) -> bool:
    """额度 -1；无余额返回 False（调用方跳过发送）。"""
    cursor = conn.execute(
        """
        UPDATE mp_subscribe_grants
        SET remaining = remaining - 1, updated_at = ?
        WHERE user_role = ? AND user_pk = ? AND template_key = ? AND remaining > 0
        """,
        (_now_iso(), user_role, int(user_pk), template_key),
    )
    return bool(cursor.rowcount)


def _clear_grants(conn: Any, user_role: str, user_pk: int, template_key: str) -> None:
    conn.execute(
        """
        UPDATE mp_subscribe_grants SET remaining = 0, updated_at = ?
        WHERE user_role = ? AND user_pk = ? AND template_key = ?
        """,
        (_now_iso(), user_role, int(user_pk), template_key),
    )


def _claim_dedupe(conn: Any, *, template_key: str, user_role: str, user_pk: int, dedupe_key: str) -> bool:
    """原子占位：同 dedupe_key 只允许一次发送（插入失败 = 已发过）。"""
    statement = insert_ignore_sql(
        get_configured_db_engine(),
        "mp_subscribe_sends",
        ("template_key", "user_role", "user_pk", "dedupe_key", "sent_at"),
        conflict_columns=("dedupe_key",),
    )
    try:
        cursor = conn.execute(
            statement.sql,
            (template_key, user_role, int(user_pk), dedupe_key, _now_iso()),
        )
    except Exception:
        return False
    return bool(cursor.rowcount)


# ---------------------------------------------------------------------------
# access_token 与发送
# ---------------------------------------------------------------------------

def _get_access_token(force_refresh: bool = False) -> str:
    """stable_token（多进程各自缓存互不失效）。失败返回空串。"""
    with _TOKEN_LOCK:
        if not force_refresh and _TOKEN_CACHE["token"] and time.time() < _TOKEN_CACHE["expires_at"]:
            return str(_TOKEN_CACHE["token"])
        appid, secret = get_wechat_mp_credentials()
        if not appid or not secret:
            print("[MP_SUBSCRIBE] 缺少小程序凭据，跳过发送")
            return ""
        try:
            response = httpx.post(
                _STABLE_TOKEN_URL,
                json={
                    "grant_type": "client_credential",
                    "appid": appid,
                    "secret": secret,
                    **({"force_refresh": True} if force_refresh else {}),
                },
                timeout=8.0,
            )
            payload = response.json()
        except Exception as exc:
            print(f"[MP_SUBSCRIBE] stable_token 请求失败: {exc}")
            return ""
        token = str(payload.get("access_token") or "")
        if not token:
            print(f"[MP_SUBSCRIBE] stable_token 错误: {payload.get('errcode')} {payload.get('errmsg')}")
            return ""
        expires_in = int(payload.get("expires_in") or 7200)
        _TOKEN_CACHE["token"] = token
        _TOKEN_CACHE["expires_at"] = time.time() + max(60, expires_in - 300)
        return token


def _find_openid(conn: Any, user_role: str, user_pk: int) -> str:
    row = conn.execute(
        """
        SELECT openid FROM wechat_bindings
        WHERE user_role = ? AND user_pk = ? AND status = 'active'
        ORDER BY id DESC LIMIT 1
        """,
        (user_role, int(user_pk)),
    ).fetchone()
    return str(row["openid"]) if row else ""


def send_subscribe_message(
    conn: Any,
    *,
    user_role: str,
    user_pk: int,
    template_key: str,
    values: dict[str, str],
    page: str = "pages/home/index",
    dedupe_key: Optional[str] = None,
) -> str:
    """发送一条订阅消息。返回状态：sent / no_grant / no_binding /
    duplicate / no_token / rejected / failed。永不抛异常。"""
    try:
        ensure_mp_subscribe_schema(conn)
        template = TEMPLATES.get(template_key)
        if not template:
            return "failed"
        if dedupe_key and not _claim_dedupe(
            conn,
            template_key=template_key,
            user_role=user_role,
            user_pk=user_pk,
            dedupe_key=dedupe_key,
        ):
            return "duplicate"
        openid = _find_openid(conn, user_role, user_pk)
        if not openid:
            return "no_binding"
        if not _consume_grant(conn, user_role, user_pk, template_key):
            return "no_grant"
        token = _get_access_token()
        if not token:
            return "no_token"

        body = {
            "touser": openid,
            "template_id": template["template_id"],
            "page": page,
            "data": {field: {"value": value} for field, value in values.items()},
        }
        payload: dict[str, Any] = {}
        for attempt in range(2):
            try:
                response = httpx.post(
                    f"{_SUBSCRIBE_SEND_URL}?access_token={token}",
                    json=body,
                    timeout=8.0,
                )
                payload = response.json()
            except Exception as exc:
                print(f"[MP_SUBSCRIBE] send 请求失败: {exc}")
                return "failed"
            errcode = int(payload.get("errcode") or 0)
            if errcode in (40001, 42001) and attempt == 0:
                token = _get_access_token(force_refresh=True)
                if not token:
                    return "no_token"
                continue
            break

        errcode = int(payload.get("errcode") or 0)
        if errcode == 0:
            return "sent"
        if errcode == 43101:
            # 用户拒收/取消订阅：清空余额，避免持续无效尝试
            _clear_grants(conn, user_role, user_pk, template_key)
            return "rejected"
        print(f"[MP_SUBSCRIBE] send 错误 template={template_key}: {errcode} {payload.get('errmsg')}")
        return "failed"
    except Exception as exc:
        print(f"[MP_SUBSCRIBE] send_subscribe_message 异常: {exc}")
        return "failed"


# ---------------------------------------------------------------------------
# 业务载荷构建（纯函数，单测覆盖）
# ---------------------------------------------------------------------------

def build_graded_values(assignment_title: Any, score: Any, feedback_preview: Any) -> dict[str, str]:
    """作业批改完成通知：thing6 标题 / number7 评分 / phrase3 结果 / thing4 备注。"""
    return {
        "thing6": clamp_thing(assignment_title),
        "number7": clamp_number(score),
        "phrase3": clamp_phrase("已批改"),
        "thing4": clamp_thing(feedback_preview or "点击查看批改详情"),
    }


def build_deadline_values(
    assignment_title: Any, class_name: Any, due_at: Any, hours_left: int
) -> dict[str, str]:
    """班级作业提醒：thing10 标题 / thing11 班级 / date8 截止 / thing3 提醒。"""
    if hours_left <= 2:
        tip = "即将截止，请尽快提交"
    else:
        tip = f"距截止约{hours_left}小时，别忘了提交"
    return {
        "thing10": clamp_thing(assignment_title),
        "thing11": clamp_thing(class_name),
        "date8": format_wechat_datetime(due_at),
        "thing3": clamp_thing(tip),
    }


def build_nudge_values(assignment_title: Any, course_name: Any, due_at: Any) -> dict[str, str]:
    """作业催交通知：thing1 标题 / thing4 科目 / time2 截止 / thing3 备注。"""
    return {
        "thing1": clamp_thing(assignment_title),
        "thing4": clamp_thing(course_name),
        "time2": format_wechat_datetime(due_at),
        "thing3": clamp_thing("老师提醒：请尽快提交作业"),
    }


def deadline_stage(remaining_seconds: float) -> Optional[str]:
    """截止扫描分档：≤2h → stage2；≤24h → stage24；其余不提醒。"""
    if remaining_seconds <= 0:
        return None
    hours = remaining_seconds / 3600
    if hours <= 2:
        return "stage2"
    if hours <= 24:
        return "stage24"
    return None


# ---------------------------------------------------------------------------
# 截止扫描（scheduler handler 调用）
# ---------------------------------------------------------------------------

DEADLINE_SCAN_TASK_KIND = "mp_deadline_reminder_scan"
DEADLINE_SCAN_INTERVAL_SECONDS = 1800


def run_deadline_reminder_scan(conn: Any) -> dict[str, int]:
    """扫描 24h 内截止的作业，给未提交且有额度的学生推截止提醒。

    合班课堂口径：学生属于 offering 的主班或 class_offering_class_links
    任一挂链班级即计入。dedupe = 作业×学生×档位，天然幂等。
    """
    from .offering_membership_service import offering_student_where

    ensure_mp_subscribe_schema(conn)
    now = datetime.now()
    rows = conn.execute(
        f"""
        SELECT a.id AS assignment_id, a.title, a.due_at,
               s.id AS student_id, cl.name AS class_name
        FROM assignments a
        JOIN class_offerings o ON o.id = a.class_offering_id
        JOIN students s ON {offering_student_where()}
        JOIN classes cl ON cl.id = s.class_id
        WHERE a.status = 'published'
          AND a.due_at IS NOT NULL AND a.due_at != ''
          AND COALESCE(s.enrollment_status, 'active') = 'active'
          AND NOT EXISTS (
              SELECT 1 FROM submissions sub
              WHERE sub.assignment_id = a.id
                AND sub.student_pk_id = s.id
                AND COALESCE(sub.is_absence_score, 0) = 0
          )
          AND NOT EXISTS (
              SELECT 1 FROM learning_stage_exam_attempts lsea
              WHERE lsea.assignment_id = a.id
          )
        """,
    ).fetchall()

    stats = {"candidates": 0, "sent": 0, "no_grant": 0, "skipped": 0}
    for row in rows:
        item = dict(row)
        due_text = str(item.get("due_at") or "").replace("T", " ")
        try:
            due_at = datetime.fromisoformat(due_text)
        except ValueError:
            continue
        remaining = (due_at - now).total_seconds()
        stage = deadline_stage(remaining)
        if stage is None:
            continue
        stats["candidates"] += 1
        hours_left = max(1, int(remaining // 3600))
        status = send_subscribe_message(
            conn,
            user_role="student",
            user_pk=int(item["student_id"]),
            template_key="deadline",
            values=build_deadline_values(item["title"], item["class_name"], due_text, hours_left),
            page="pages/tasks/index",
            dedupe_key=f"deadline:{item['assignment_id']}:{item['student_id']}:{stage}",
        )
        if status == "sent":
            stats["sent"] += 1
        elif status == "no_grant":
            stats["no_grant"] += 1
        else:
            stats["skipped"] += 1
    return stats


def ensure_deadline_scan_task(conn: Any) -> int:
    from datetime import timedelta

    from .scheduled_task_service import schedule_task

    return schedule_task(
        conn,
        task_kind=DEADLINE_SCAN_TASK_KIND,
        run_at=datetime.now() + timedelta(seconds=120),
        payload={},
        dedupe_key="mp:deadline-reminder-scan",
        recurrence_seconds=DEADLINE_SCAN_INTERVAL_SECONDS,
        title="MP assignment deadline reminder scan",
        priority=80,
        max_attempts=3,
        replace=False,
    )
