// One allowlist, generated SVG paths from the installed ISC-licensed Lucide.
import { readFile, mkdir, writeFile } from 'node:fs/promises';
import { createRequire } from 'node:module';
import { dirname, resolve } from 'node:path';
import { pathToFileURL } from 'node:url';
const require = createRequire(import.meta.url);
const root = resolve(import.meta.dirname, '../..');
const packageRoot = resolve(dirname(require.resolve('lucide-react')), '../..');
const pkg = JSON.parse(await readFile(resolve(packageRoot, 'package.json'), 'utf8'));
const names = ['arrow-left', 'arrow-right', 'bell', 'book-open', 'calendar', 'check', 'chevron-down', 'chevron-left', 'chevron-right', 'chevron-up', 'circle', 'circle-alert', 'circle-check', 'circle-question-mark', 'clock', 'download', 'ellipsis', 'external-link', 'file-text', 'folder', 'info', 'layout-dashboard', 'link', 'list', 'loader-circle', 'lock', 'menu', 'message-circle', 'paperclip', 'pencil', 'plus', 'refresh-cw', 'search', 'send', 'settings', 'smile', 'trash-2', 'triangle-alert', 'upload', 'user', 'users', 'x'];
const aliases = { 'circle-help': 'circle-question-mark', refresh: 'refresh-cw', edit: 'pencil', delete: 'trash-2', close: 'x', warning: 'triangle-alert', error: 'circle-alert', success: 'circle-check' };
const nodes = {};
const escape = value => String(value).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
for (const name of names) {
  const source = await import(pathToFileURL(resolve(packageRoot, 'dist/esm/icons', `${name}.mjs`)));
  if (!Array.isArray(source.__iconNode)) throw new Error(`Lucide icon node unavailable: ${name}`);
  nodes[name] = source.__iconNode.map(([tag, attrs]) => {
    if (!['path', 'circle', 'ellipse', 'line', 'polyline', 'polygon', 'rect'].includes(tag)) throw new Error(`Unsupported SVG node ${tag}`);
    const result = {};
    for (const [key, value] of Object.entries(attrs)) {
      if (key === 'key') continue;
      if (!['d','cx','cy','r','rx','ry','x','y','x1','x2','y1','y2','width','height','points'].includes(key)) throw new Error(`Unsupported SVG attr ${key}`);
      result[key] = String(value);
    }
    return [tag, result];
  });
}
const banner = `Generated by tools/ui/generate_lq_icons.mjs from lucide-react ${pkg.version} (ISC/MIT); license: ./lucide-LICENSE.txt; do not hand-edit paths.`;
const license = await readFile(resolve(root, 'node_modules/lucide-react/LICENSE'), 'utf8');
const js = `/*! ${banner} */\nexport const ICON_NODES = Object.freeze(Object.fromEntries(Object.entries(${JSON.stringify(nodes)}).map(([name, nodes]) => [name, Object.freeze(nodes.map(([tag, attrs]) => Object.freeze([tag, Object.freeze(attrs)])))])));\nexport const ICON_ALIASES = Object.freeze(${JSON.stringify(aliases)});\n`;
const svg = name => `<svg class="lq-icon" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true" focusable="false">${nodes[name].map(([tag, attrs]) => `<${tag} ${Object.entries(attrs).map(([key,value])=>`${key}="${escape(value)}"`).join(' ')}/>`).join('')}</svg>`;
let macro = `{# ${banner}\n${license.trim()}\n#}\n{% macro lq_icon(name) -%}\n`;
names.filter(n => n !== 'circle-question-mark').forEach((name, index) => {
  const accepted = [name, ...Object.keys(aliases).filter(alias => aliases[alias] === name)];
  macro += `{% ${index ? 'elif' : 'if'} name in ${JSON.stringify(accepted)} %}${svg(name)}\n`;
});
macro += `{% else %}${svg('circle-question-mark')}\n{% endif %}\n{%- endmacro %}\n`;
for (const [name, text] of [['static/js/lq/icons.generated.js', js], ['templates/macros/lq/icons.generated.html', macro], ['static/js/lq/lucide-LICENSE.txt', license]]) {
  const file = resolve(root, name);
  if (process.argv.includes('--check')) {
    if (await readFile(file, 'utf8') !== text) throw new Error(`Stale icon registry: ${name}`);
  } else { await mkdir(dirname(file), {recursive:true}); await writeFile(file, text, 'utf8'); }
}
console.log(JSON.stringify({icons: names.length, aliases: Object.keys(aliases).length, source: `lucide-react@${pkg.version}`, check: process.argv.includes('--check')}));
