"""Generate semantic state levels from the existing canonical CSS aliases.

This is an authoring/check command, not a Python step in the npm build.
Identity palettes (course, attachment, agenda, monitor) are not status levels.
"""
import argparse
import json
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[2]
FAMILIES = ("assignment", "submission", "submission-flag", "score", "deadline", "save", "job", "agent", "signature")


def registry():
    source = (ROOT / "static/css/lq/tokens.css").read_text(encoding="utf-8")
    declarations = dict(re.findall(r"(--[\w-]+)\s*:\s*([^;{}]+);", source))
    result = {family: {} for family in FAMILIES}
    for name, value in declarations.items():
        match = re.fullmatch(r"var\(--ls-tone-(success|warning|danger|info|neutral)-base\)", value.strip())
        if value.strip() == "var(--ls-primary)":
            level = "primary"
        elif match:
            level = match[1]
        else:
            continue
        for family in sorted(FAMILIES, key=len, reverse=True):
            prefix = f"--tone-{family}-"
            if name.startswith(prefix):
                state = name[len(prefix):]
                # Every semantic base must have its pair aliases; this also
                # prevents accidentally treating a suffix token as a state.
                if all(name + suffix in declarations for suffix in ("-fg", "-soft", "-on-base", "-solid", "-on-solid")):
                    result[family][state] = level
                break
    if any(not states for states in result.values()):
        raise ValueError("A semantic family has no complete CSS aliases")
    return {family: dict(sorted(states.items())) for family, states in sorted(result.items())}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    data = registry()
    payload = json.dumps(data, ensure_ascii=False, indent=2) + "\n"
    js = "// Generated by tools/ui/generate_lq_tones.py from tokens.css; do not hand edit.\n"
    js += "const registry = " + json.dumps(data, ensure_ascii=False, separators=(",", ":")) + ";\n"
    js += "Object.values(registry).forEach(Object.freeze);\nexport const toneLevels = Object.freeze(registry);\n"
    for relative, content in (("classroom_app/lq_tones.generated.json", payload), ("static/js/lq/tones.generated.js", js)):
        path = ROOT / relative
        if args.check:
            if not path.exists() or path.read_text(encoding="utf-8") != content:
                raise SystemExit(f"Outdated LQ tone registry: {relative}")
        else:
            path.write_text(content, encoding="utf-8")
    print(f'LQ tones: {len(data)} families, {sum(map(len, data.values()))} states; {"verified" if args.check else "generated"}')


if __name__ == "__main__":
    main()
