"""Synthetic teaching fixtures and real in-app reminder instrumentation.

Only used by the isolated PG load tool. No production schema, SMTP, Office or
external delivery worker is opened. The application scheduler/handler/notification
SQL remain real; measurements wrap them and preserve their return values.
"""
from __future__ import annotations

import asyncio
from datetime import datetime, timedelta
import threading
import time
from unittest.mock import patch

from classroom_app.db import schema_scheduler
from classroom_app.routers.ui_parts import dashboard as teaching_routes
from classroom_app.services import assignment_reminder_service as reminders
from classroom_app.services import scheduled_task_service as scheduler
from classroom_app.services import scheduled_task_handlers as handlers
from classroom_app.services import message_center_service as messages
from classroom_app.services.academic_service import china_now


def seed_teaching(conn):
    """Match the real read-only student deck SQL, with nonempty authorized data."""
    conn.execute("ALTER TABLE classes ADD COLUMN description TEXT DEFAULT ''")
    conn.execute("CREATE TABLE teachers(id BIGINT PRIMARY KEY,name TEXT,is_active INTEGER)")
    conn.execute("CREATE TABLE courses(id BIGINT PRIMARY KEY,name TEXT,description TEXT,credits INTEGER)")
    conn.execute("""CREATE TABLE class_offerings(id BIGINT PRIMARY KEY,class_id BIGINT,course_id BIGINT,teacher_id BIGINT,
        semester TEXT,semester_id BIGINT,combined_class_names TEXT,schedule_info TEXT,created_at TEXT)""")
    conn.execute("CREATE TABLE class_offering_class_links(offering_id BIGINT,class_id BIGINT,PRIMARY KEY(offering_id,class_id))")
    conn.execute("""CREATE TABLE academic_semesters(id BIGINT PRIMARY KEY,teacher_id BIGINT,school_code TEXT,school_name TEXT,name TEXT,
        start_date TEXT,end_date TEXT,week_count INTEGER,calendar_sync_status TEXT,calendar_sync_at TEXT,
        calendar_sync_message TEXT,calendar_source_summary_json TEXT,created_at TEXT,updated_at TEXT)""")
    conn.execute("""CREATE TABLE academic_semester_calendar_days(semester_id BIGINT,date TEXT,week_index INTEGER,weekday INTEGER,
        day_type TEXT,label TEXT,source TEXT,source_url TEXT,confidence REAL,metadata_json TEXT)""")
    conn.execute("""CREATE TABLE class_offering_sessions(id BIGINT PRIMARY KEY,class_offering_id BIGINT,session_date TEXT,order_index INTEGER,
        academic_section_text TEXT,academic_location TEXT,schedule_metadata_json TEXT,schedule_status TEXT,week_index INTEGER,weekday INTEGER)""")
    conn.execute("CREATE INDEX probe_sessions_offering ON class_offering_sessions(class_offering_id,session_date)")
    conn.execute("CREATE INDEX probe_students_class ON students(class_id)")
    conn.execute("CREATE INDEX probe_offerings_class ON class_offerings(class_id)")
    today = china_now().date()
    monday = today - timedelta(days=today.weekday())
    term = f"{today.year}-{today.year+1}第一学期"
    conn.execute("INSERT INTO academic_semesters VALUES(1,1,'career-probe','合成大学',?,?,?,20,'','','','[]','','')",
                 (term,monday.isoformat(),(monday+timedelta(days=139)).isoformat()))
    conn.executemany("INSERT INTO teachers VALUES(?,?,1)",[(i,f"合成教师{i}") for i in range(1,11)])
    for offering_id in range(1,31):
        class_id = (offering_id-1)//3+1
        conn.execute("INSERT INTO courses VALUES(?,?,?,2)",(offering_id,f"合成专业课程{offering_id}","隔离负载测试课程"))
        conn.execute("INSERT INTO class_offerings VALUES(?,?,?,?,?,1,?,'','')",
                     (offering_id,class_id,offering_id,class_id,term,f"合成班{class_id}"))
        conn.executemany("INSERT INTO class_offering_sessions VALUES(?,?,?,?,?,?,?,'scheduled',?,?)",[
            (offering_id*1000+week*2+day+1,offering_id,(monday+timedelta(days=week*7+day*2)).isoformat(),week*2+day+1,
             "2-3",f"合成教室{class_id}","{}",week+1,day*2+1) for week in range(20) for day in range(2)])
    # Additional controls never enter the 1..users load generator cohort.
    conn.execute("INSERT INTO classes(id,name) VALUES(99,'隔离其他班级')")
    conn.execute("UPDATE students SET class_id=99 WHERE id=100001")
    conn.execute("INSERT INTO students(id,name,class_id,enrollment_status) VALUES(100002,'停学合成对照',1,'suspended')")
    conn.execute("""CREATE TABLE assignments(id BIGINT PRIMARY KEY,course_id BIGINT,class_offering_id BIGINT,title TEXT,
        status TEXT,due_at TEXT,closed_at TEXT,exam_paper_id BIGINT)""")
    conn.execute("ALTER TABLE submissions ADD COLUMN assignment_id BIGINT")
    conn.execute("ALTER TABLE submissions ADD COLUMN student_pk_id BIGINT")
    conn.execute("CREATE INDEX probe_submission_assignment_student ON submissions(assignment_id,student_pk_id)")
    conn.execute("""CREATE TABLE message_center_notifications(
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, recipient_identity TEXT NOT NULL,
        recipient_role TEXT NOT NULL,recipient_user_pk BIGINT NOT NULL,category TEXT NOT NULL,severity TEXT DEFAULT 'normal',
        actor_identity TEXT DEFAULT '',actor_role TEXT DEFAULT '',actor_user_pk BIGINT,actor_display_name TEXT DEFAULT '',
        title TEXT NOT NULL,body_preview TEXT DEFAULT '',link_url TEXT DEFAULT '',class_offering_id BIGINT,
        ref_type TEXT DEFAULT '',ref_id TEXT DEFAULT '',metadata_json TEXT DEFAULT '{}',
        email_status TEXT DEFAULT 'not_required',email_job_id BIGINT,email_queued_at TEXT,email_sent_at TEXT,read_at TEXT,created_at TEXT)""")
    conn.execute("CREATE INDEX probe_notifications_ref ON message_center_notifications(ref_type,ref_id,recipient_role,recipient_user_pk)")
    schema_scheduler._SCHEMA_READY = False
    schema_scheduler.ensure_scheduler_schema(conn)
    conn.commit()
    return {"teachers":10,"courses":30,"offerings":30,"sessions":1200,"semesters":1,
            "read_endpoint":"/api/dashboard/course-schedule/overview","expected_lessons_per_student":120}


class ReminderMeasurements:
    def __init__(self, connect, label, *, poll_seconds=20):
        self.connect,self.label = connect,label
        self.poll_seconds = poll_seconds
        self.records = {}
        self.errors = []
        self.stop = threading.Event()
        self.thread = None

    def prepare(self, duration, interval, offset):
        if abs((datetime.now()-china_now().replace(tzinfo=None)).total_seconds()) > 5:
            raise RuntimeError("Reminder probe requires the same Asia/Shanghai local clock as the application's naive scheduler timestamps")
        beginning = china_now().replace(tzinfo=None)
        with self.connect() as conn:
            sequence = 0
            # Admit only reminders with one full polling interval remaining;
            # do not count a task scheduled after the measurement window as lost.
            while offset+sequence*interval <= duration-self.poll_seconds:
                assignment_id = 900000+sequence
                offering_id = (sequence%10)*3+1
                class_id = sequence%10+1
                due = beginning+timedelta(hours=2,seconds=offset+sequence*interval)
                due_text = due.isoformat(timespec="seconds")
                conn.execute("INSERT INTO assignments VALUES(?,?,?,?, 'published',?,'',NULL)",
                             (assignment_id,offering_id,offering_id,f"合成临期作业{sequence}",due_text))
                submitted = conn.execute("SELECT MIN(id) AS id FROM students WHERE class_id=? AND id<=1000",(class_id,)).fetchone()["id"]
                conn.execute("INSERT INTO submissions(id,assignment_id,student_pk_id) VALUES(?,?,?)",(assignment_id,assignment_id,submitted))
                reminders.sync_assignment_due_reminders(conn,assignment_id,status="published",due_at=due_text,class_offering_id=offering_id,title="合成临期作业")
                task = conn.execute("SELECT id,run_at FROM scheduled_tasks WHERE dedupe_key=?",(f"assignment-due-reminder:{assignment_id}:2h",)).fetchone()
                if not task:
                    raise AssertionError("Real reminder sync failed to schedule the synthetic assignment")
                expected = {int(row["id"]) for row in conn.execute("SELECT id FROM students WHERE class_id=? AND COALESCE(enrollment_status,'active')='active' AND id!=?",(class_id,submitted))}
                self.records[int(task["id"])] = {"task_id":int(task["id"]),"assignment_id":assignment_id,"run_at":task["run_at"],
                    "due_epoch":datetime.fromisoformat(task["run_at"]).timestamp(),"expected_recipients":sorted(expected),"submitted_control":submitted}
                sequence += 1
            conn.commit()

    def install(self, stack):
        # Students receive real in-app notifications only. Do not enqueue any
        # external email or run an outbox worker during this isolated probe.
        stack.enter_context(patch.object(messages,"queue_notification_email_if_applicable",return_value=False))
        original_claim = scheduler._claim_due_tasks
        original_dispatch = scheduler._dispatch_task
        original_success = scheduler._mark_success

        def claim(limit):
            tasks = original_claim(limit)
            for task in tasks:
                if int(task["id"]) in self.records:
                    self.records[int(task["id"])]["claim_epoch"] = time.time()
            return tasks

        async def dispatch(task):
            record = self.records.get(int(task["id"]))
            if record is not None:
                record["handler_start_epoch"] = time.time()
            result = await original_dispatch(task)
            if record is not None:
                record["handler_return_epoch"] = time.time()
                # The real handler committed its transaction before returning.
                # A second pooled connection proves recipient rows are visible.
                with self.connect() as conn:
                    rows = conn.execute("SELECT recipient_user_pk FROM message_center_notifications WHERE ref_type='assignment_due' AND ref_id=?",(f"{record['assignment_id']}:2h",)).fetchall()
                record["notification_visible_epoch"] = time.time()
                record["actual_recipients"] = sorted(int(row["recipient_user_pk"]) for row in rows)
            return result

        def success(task,result):
            original_success(task,result)
            if int(task["id"]) in self.records:
                self.records[int(task["id"])]["done_epoch"] = time.time()

        stack.enter_context(patch.object(scheduler,"_claim_due_tasks",claim))
        stack.enter_context(patch.object(scheduler,"_dispatch_task",dispatch))
        stack.enter_context(patch.object(scheduler,"_mark_success",success))

    def start(self):
        def loop():
            token = self.label.set("assignment_reminder_scheduler")
            try:
                while not self.stop.is_set():
                    asyncio.run(scheduler.process_due_scheduled_tasks_once())
                    scheduler.update_scheduler_heartbeat("isolated-mixed-reminder",status="running")
                    self.stop.wait(self.poll_seconds)
            except BaseException as exc:
                self.errors.append(repr(exc))
            finally:
                self.label.reset(token)
        self.thread = threading.Thread(target=loop,name="isolated-real-reminder-scheduler",daemon=True)
        self.thread.start()

    async def finish(self):
        self.stop.set()
        if self.thread:
            await asyncio.to_thread(self.thread.join,30)
            if self.thread.is_alive():
                self.errors.append("Scheduler thread did not stop")
        return self.report()

    def verify_duplicate_replay(self):
        """Outside latency samples, replay the real handler and verify dedupe."""
        for record in self.records.values():
            if "done_epoch" not in record:
                continue
            with self.connect() as conn:
                task = dict(conn.execute("SELECT * FROM scheduled_tasks WHERE id=?",(record["task_id"],)).fetchone())
                before = conn.execute("SELECT COUNT(*) AS n FROM message_center_notifications WHERE ref_type='assignment_due' AND ref_id=?",(f"{record['assignment_id']}:2h",)).fetchone()["n"]
            import json
            task["payload"] = json.loads(task["payload_json"])
            handlers.handle_assignment_due_reminder(task)
            with self.connect() as conn:
                after = conn.execute("SELECT COUNT(*) AS n FROM message_center_notifications WHERE ref_type='assignment_due' AND ref_id=?",(f"{record['assignment_id']}:2h",)).fetchone()["n"]
            record["duplicate_replay_no_new_notifications"] = before == after
            if before != after:
                self.errors.append(f"Duplicate reminder notifications for task {record['task_id']}")
        return self.report()

    def report(self):
        records = list(self.records.values())
        for row in records:
            for event in ("claim","handler_start","notification_visible","done"):
                if event+"_epoch" in row:
                    row[event+"_delay_ms"] = round((row[event+"_epoch"]-row["due_epoch"])*1000,3)
            if "handler_return_epoch" in row:
                row["handler_duration_ms"] = round((row["handler_return_epoch"]-row["handler_start_epoch"])*1000,3)
        incomplete = [r["task_id"] for r in records if "done_epoch" not in r]
        wrong_recipients = [r["task_id"] for r in records if r.get("actual_recipients") != r["expected_recipients"]]
        return {"ok":not self.errors and not incomplete and not wrong_recipients,"exercised":bool(records),"scheduled":len(records),
                "completed":sum("done_epoch" in r for r in records),"incomplete":incomplete,"recipient_mismatch":wrong_recipients,
                "errors":self.errors,"poll_seconds":self.poll_seconds,"records":records,
                "scope":"Real assignment reminder arm/claim/dispatch/recipient filtering/deduplication/in-app notification commit. Dedicated scheduler thread shares the bounded pool, unlike separate production scheduler processes. No SMTP queue/delivery. Timing due timestamps has one-second storage precision; successful notification visibility is measured on a second connection."}
