from __future__ import annotations

import argparse
import datetime as dt
import json
import shutil
import sqlite3
from pathlib import Path
from typing import Any, Iterable, Sequence


REPO_ROOT = Path(__file__).resolve().parents[1]
TEMP_ROOT = REPO_ROOT / ".codex-temp"
DEFAULT_RUNTIME_ROOT = TEMP_ROOT / "db-postgres-export"
DEFAULT_SOURCE_DB = REPO_ROOT / "data" / "classroom.db"


def _now() -> str:
    return dt.datetime.now(dt.timezone.utc).replace(microsecond=0).isoformat()


def _is_relative_to(path: Path, parent: Path) -> bool:
    try:
        path.relative_to(parent)
        return True
    except ValueError:
        return False


def resolve_runtime_root(raw: str | Path | None = None) -> Path:
    runtime_root = Path(raw) if raw else DEFAULT_RUNTIME_ROOT
    if not runtime_root.is_absolute():
        runtime_root = REPO_ROOT / runtime_root
    runtime_root = runtime_root.resolve()
    temp_root = TEMP_ROOT.resolve()
    if runtime_root != temp_root and not _is_relative_to(runtime_root, temp_root):
        raise ValueError(f"postgres export runtime root must stay under {temp_root}; got {runtime_root}")
    return runtime_root


def source_db_path(raw: str | Path | None = None) -> Path:
    source = Path(raw) if raw else DEFAULT_SOURCE_DB
    if not source.is_absolute():
        source = REPO_ROOT / source
    source = source.resolve()
    if not source.is_file():
        raise FileNotFoundError(f"source database not found: {source}")
    return source


def _copy_sqlite_database(source_db: Path, target_db: Path) -> None:
    target_db.parent.mkdir(parents=True, exist_ok=True)
    if target_db.exists():
        target_db.unlink()
    source_uri = source_db.resolve().as_uri() + "?mode=ro"
    source_conn = sqlite3.connect(source_uri, uri=True)
    target_conn = sqlite3.connect(target_db)
    try:
        source_conn.backup(target_conn)
    finally:
        target_conn.close()
        source_conn.close()


def _quote_ident(identifier: str) -> str:
    return '"' + str(identifier).replace('"', '""') + '"'


def _sql_literal(value: Any) -> str:
    if value is None:
        return "NULL"
    if isinstance(value, bool):
        return "1" if value else "0"
    if isinstance(value, int):
        return str(value)
    if isinstance(value, float):
        return "NULL" if value != value else repr(value)
    if isinstance(value, bytes):
        return "decode('" + value.hex() + "', 'hex')"
    text = str(value)
    if "\x00" in text:
        text = text.replace("\x00", "")
    return "'" + text.replace("'", "''") + "'"


def _table_names(conn: sqlite3.Connection) -> list[str]:
    return [
        str(row["name"])
        for row in conn.execute(
            "SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%' ORDER BY name"
        ).fetchall()
    ]


def _columns(conn: sqlite3.Connection, table: str) -> list[dict[str, Any]]:
    return [dict(row) for row in conn.execute(f"PRAGMA table_info({_quote_ident(table)})").fetchall()]


def _indexes(conn: sqlite3.Connection) -> list[dict[str, Any]]:
    rows = conn.execute(
        """
        SELECT name, tbl_name, sql
        FROM sqlite_master
        WHERE type='index'
          AND name NOT LIKE 'sqlite_%'
          AND sql IS NOT NULL
        ORDER BY name
        """
    ).fetchall()
    return [dict(row) for row in rows]


def _normalize_default(value: Any) -> str:
    if value is None:
        return ""
    raw = str(value).strip()
    if not raw:
        return ""
    upper = raw.upper()
    if upper in {"CURRENT_TIMESTAMP", "CURRENT_DATE", "CURRENT_TIME"}:
        return upper
    if upper.startswith("DATETIME(") or upper.startswith("STRFTIME("):
        return ""
    return raw


def _postgres_type(sqlite_type: str, *, is_integer_pk: bool, identity: bool = True) -> str:
    raw = str(sqlite_type or "").upper()
    if is_integer_pk:
        return "BIGINT GENERATED BY DEFAULT AS IDENTITY" if identity else "BIGINT"
    if "INT" in raw:
        return "BIGINT"
    if any(token in raw for token in ("CHAR", "CLOB", "TEXT", "JSON", "DATE", "TIME")):
        return "TEXT"
    if any(token in raw for token in ("REAL", "FLOA", "DOUB")):
        return "DOUBLE PRECISION"
    if any(token in raw for token in ("NUM", "DEC")):
        return "NUMERIC"
    if "BLOB" in raw:
        return "BYTEA"
    return "TEXT"


def _column_lookup(conn: sqlite3.Connection, table: str) -> dict[str, dict[str, Any]]:
    return {str(column["name"]): column for column in _columns(conn, table)}


def _foreign_key_type_overrides(conn: sqlite3.Connection, table: str) -> dict[str, str]:
    overrides: dict[str, str] = {}
    parent_cache: dict[str, dict[str, dict[str, Any]]] = {}
    for row in conn.execute(f"PRAGMA foreign_key_list({_quote_ident(table)})").fetchall():
        child_column = str(row["from"])
        parent_table = str(row["table"])
        parent_column = str(row["to"] or "id")
        if parent_table not in parent_cache:
            parent_cache[parent_table] = _column_lookup(conn, parent_table)
        parent = parent_cache[parent_table].get(parent_column)
        if not parent:
            continue
        parent_is_integer_pk = int(parent.get("pk") or 0) > 0 and "INT" in str(parent.get("type") or "").upper()
        overrides[child_column] = _postgres_type(
            str(parent.get("type") or ""),
            is_integer_pk=parent_is_integer_pk,
            identity=False,
        )
    return overrides


def _create_table_sql(
    table: str,
    columns: Sequence[dict[str, Any]],
    *,
    type_overrides: dict[str, str] | None = None,
) -> str:
    type_overrides = type_overrides or {}
    pk_columns = [column for column in sorted(columns, key=lambda item: int(item.get("pk") or 0)) if int(column.get("pk") or 0)]
    single_integer_pk = len(pk_columns) == 1 and "INT" in str(pk_columns[0].get("type") or "").upper()
    lines: list[str] = []
    for column in columns:
        name = str(column["name"])
        is_pk = single_integer_pk and name == str(pk_columns[0]["name"])
        column_type = type_overrides.get(name) if not is_pk else ""
        parts = [_quote_ident(name), column_type or _postgres_type(str(column.get("type") or ""), is_integer_pk=is_pk)]
        if int(column.get("notnull") or 0) and not is_pk:
            parts.append("NOT NULL")
        default = _normalize_default(column.get("dflt_value"))
        if default and not is_pk:
            parts.append(f"DEFAULT {default}")
        lines.append("  " + " ".join(parts))
    if pk_columns:
        pk_sql = ", ".join(_quote_ident(str(column["name"])) for column in pk_columns)
        lines.append(f"  PRIMARY KEY ({pk_sql})")
    return f"CREATE TABLE IF NOT EXISTS {_quote_ident(table)} (\n" + ",\n".join(lines) + "\n);"


def _foreign_key_constraints(conn: sqlite3.Connection, table: str) -> list[str]:
    rows = [dict(row) for row in conn.execute(f"PRAGMA foreign_key_list({_quote_ident(table)})").fetchall()]
    grouped: dict[int, list[dict[str, Any]]] = {}
    for row in rows:
        grouped.setdefault(int(row["id"]), []).append(row)
    constraints: list[str] = []
    for fkid, items in sorted(grouped.items()):
        items = sorted(items, key=lambda item: int(item.get("seq") or 0))
        from_cols = ", ".join(_quote_ident(str(item["from"])) for item in items)
        to_cols = ", ".join(_quote_ident(str(item["to"] or "id")) for item in items)
        parent = str(items[0]["table"])
        on_update = _fk_action(str(items[0].get("on_update") or "NO ACTION"))
        on_delete = _fk_action(str(items[0].get("on_delete") or "NO ACTION"))
        name = f"fk_{table}_{fkid}"
        constraints.append(
            f"ALTER TABLE {_quote_ident(table)} ADD CONSTRAINT {_quote_ident(name)} "
            f"FOREIGN KEY ({from_cols}) REFERENCES {_quote_ident(parent)} ({to_cols}) "
            f"ON UPDATE {on_update} ON DELETE {on_delete} DEFERRABLE INITIALLY DEFERRED;"
        )
    return constraints


def _fk_action(action: str) -> str:
    normalized = str(action or "NO ACTION").upper().replace("_", " ")
    return normalized if normalized in {"NO ACTION", "RESTRICT", "CASCADE", "SET NULL", "SET DEFAULT"} else "NO ACTION"


def _index_sql(index: dict[str, Any]) -> str:
    sql = str(index.get("sql") or "").strip().rstrip(";")
    # SQLite's NOCASE collation is not portable to PostgreSQL in the same form.
    sql = sql.replace(" COLLATE NOCASE", "")
    return sql + ";"


def _batched(iterable: Sequence[sqlite3.Row], size: int) -> Iterable[Sequence[sqlite3.Row]]:
    for start in range(0, len(iterable), size):
        yield iterable[start : start + size]


def _insert_batches_sql(table: str, columns: Sequence[dict[str, Any]], rows: Sequence[sqlite3.Row], batch_size: int) -> Iterable[str]:
    if not rows:
        return
    column_names = [str(column["name"]) for column in columns]
    column_sql = ", ".join(_quote_ident(name) for name in column_names)
    for batch in _batched(list(rows), batch_size):
        values_sql = []
        for row in batch:
            values_sql.append("(" + ", ".join(_sql_literal(row[name]) for name in column_names) + ")")
        yield f"INSERT INTO {_quote_ident(table)} ({column_sql}) VALUES\n" + ",\n".join(values_sql) + ";"


def _identity_reset_sql(table: str, columns: Sequence[dict[str, Any]]) -> str:
    pk_columns = [column for column in columns if int(column.get("pk") or 0)]
    if len(pk_columns) != 1:
        return ""
    pk = str(pk_columns[0]["name"])
    if "INT" not in str(pk_columns[0].get("type") or "").upper():
        return ""
    return (
        f"SELECT setval(pg_get_serial_sequence('{table}', '{pk}'), "
        f"COALESCE((SELECT MAX({_quote_ident(pk)}) FROM {_quote_ident(table)}), 1), "
        f"(SELECT COUNT(*) > 0 FROM {_quote_ident(table)}));"
    )


def _table_count(conn: sqlite3.Connection, table: str) -> int:
    return int(conn.execute(f"SELECT COUNT(*) FROM {_quote_ident(table)}").fetchone()[0])


def _write_lines(path: Path, lines: Iterable[str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")


def build_postgres_export_package(
    runtime_root: Path | str | None = None,
    *,
    source_db: Path | str | None = None,
    batch_size: int = 500,
) -> dict[str, Any]:
    runtime = resolve_runtime_root(runtime_root)
    if runtime.exists():
        shutil.rmtree(runtime)
    package_dir = runtime / "package"
    reports_dir = runtime / "reports"
    db_dir = runtime / "db"
    for directory in (package_dir, reports_dir, db_dir):
        directory.mkdir(parents=True, exist_ok=True)
    source = source_db_path(source_db)
    copied_db = db_dir / "classroom.export-source.db"
    _copy_sqlite_database(source, copied_db)

    conn = sqlite3.connect(copied_db)
    conn.row_factory = sqlite3.Row
    try:
        quick_check = str(conn.execute("PRAGMA quick_check").fetchone()[0])
        fk_count = len(conn.execute("PRAGMA foreign_key_check").fetchall())
        tables = _table_names(conn)
        schema_lines = [
            "-- LanShare SQLite to PostgreSQL schema export",
            "BEGIN;",
            "SET client_encoding = 'UTF8';",
            "SET standard_conforming_strings = on;",
            "",
        ]
        data_lines = [
            "-- LanShare SQLite to PostgreSQL data export",
            "BEGIN;",
            "SET client_encoding = 'UTF8';",
            "SET standard_conforming_strings = on;",
            "",
        ]
        constraints_lines = [
            "-- LanShare PostgreSQL foreign keys and indexes",
            "BEGIN;",
            "",
        ]
        verify_lines = [
            "-- LanShare PostgreSQL verification queries",
            "SELECT current_database() AS database_name;",
        ]
        table_reports: list[dict[str, Any]] = []
        identity_resets: list[str] = []
        for table in tables:
            columns = _columns(conn, table)
            if not columns:
                continue
            schema_lines.append(
                _create_table_sql(
                    table,
                    columns,
                    type_overrides=_foreign_key_type_overrides(conn, table),
                )
            )
            schema_lines.append("")
            rows = conn.execute(f"SELECT * FROM {_quote_ident(table)}").fetchall()
            row_count = len(rows)
            for statement in _insert_batches_sql(table, columns, rows, max(1, batch_size)):
                data_lines.append(statement)
            if row_count:
                data_lines.append("")
            reset_sql = _identity_reset_sql(table, columns)
            if reset_sql:
                identity_resets.append(reset_sql)
            for constraint in _foreign_key_constraints(conn, table):
                constraints_lines.append(constraint)
            verify_lines.append(
                f"SELECT '{table}' AS table_name, COUNT(*) AS row_count FROM {_quote_ident(table)};"
            )
            table_reports.append(
                {
                    "table": table,
                    "columns": [str(column["name"]) for column in columns],
                    "row_count": row_count,
                    "foreign_key_count": len(_foreign_key_constraints(conn, table)),
                }
            )
        if identity_resets:
            data_lines.append("-- Reset identity sequences after explicit id import")
            data_lines.extend(identity_resets)
            data_lines.append("")
        for index in _indexes(conn):
            constraints_lines.append(_index_sql(index))
        schema_lines.append("COMMIT;")
        data_lines.append("COMMIT;")
        constraints_lines.append("")
        constraints_lines.append("COMMIT;")
    finally:
        conn.close()

    schema_path = package_dir / "01-schema.sql"
    data_path = package_dir / "02-data.sql"
    constraints_path = package_dir / "03-constraints-indexes.sql"
    verify_path = package_dir / "04-verify-counts.sql"
    readme_path = package_dir / "README.md"
    _write_lines(schema_path, schema_lines)
    _write_lines(data_path, data_lines)
    _write_lines(constraints_path, constraints_lines)
    _write_lines(verify_path, verify_lines)
    _write_lines(
        readme_path,
        [
            "# LanShare PostgreSQL Migration Package",
            "",
            "Run only against an empty temporary PostgreSQL database first.",
            "",
            "```bash",
            "psql \"$DATABASE_URL\" -v ON_ERROR_STOP=1 -f 01-schema.sql",
            "psql \"$DATABASE_URL\" -v ON_ERROR_STOP=1 -f 02-data.sql",
            "psql \"$DATABASE_URL\" -v ON_ERROR_STOP=1 -f 03-constraints-indexes.sql",
            "psql \"$DATABASE_URL\" -v ON_ERROR_STOP=1 -f 04-verify-counts.sql",
            "```",
            "",
            "Never run this package against the production database without a fresh SQLite backup and a rollback window.",
        ],
    )

    report = {
        "status": "ok" if quick_check == "ok" else "failed",
        "generated_at": _now(),
        "runtime_root": str(runtime),
        "source_db": str(source),
        "copied_db": str(copied_db),
        "package_dir": str(package_dir),
        "quick_check": quick_check,
        "foreign_key_violations": fk_count,
        "table_count": len(table_reports),
        "total_rows": sum(int(item["row_count"]) for item in table_reports),
        "tables": table_reports,
        "files": {
            "schema_sql": str(schema_path),
            "data_sql": str(data_path),
            "constraints_indexes_sql": str(constraints_path),
            "verify_counts_sql": str(verify_path),
            "readme": str(readme_path),
        },
        "actual_postgres_data_load_executed": False,
        "safety": {
            "source_db_was_copied": True,
            "production_data_modified": False,
            "remote_data_modified": False,
        },
    }
    manifest_path = reports_dir / "postgres-export-package.json"
    manifest_path.write_text(json.dumps(report, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    _write_lines(
        reports_dir / "postgres-export-package.md",
        [
            "# PostgreSQL Export Package",
            "",
            f"- Status: `{report['status']}`",
            f"- Source DB: `{report['source_db']}`",
            f"- Copied DB: `{report['copied_db']}`",
            f"- Table count: `{report['table_count']}`",
            f"- Total rows: `{report['total_rows']}`",
            f"- Foreign-key violations: `{report['foreign_key_violations']}`",
            f"- Actual PostgreSQL data load executed: `{report['actual_postgres_data_load_executed']}`",
            f"- Production data modified: `{report['safety']['production_data_modified']}`",
            "",
            "## Package Files",
            "",
            *[f"- `{path}`" for path in report["files"].values()],
        ],
    )
    return report


def write_json(report: dict[str, Any], output: Path | None) -> None:
    text = json.dumps(report, ensure_ascii=False, indent=2)
    if output is None:
        print(text)
        return
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(text + "\n", encoding="utf-8")
    print(f"postgres export report written: {output}")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Build an offline PostgreSQL SQL package from a copied SQLite database.")
    parser.add_argument("--runtime-root", type=str)
    parser.add_argument("--source-db", type=Path)
    parser.add_argument("--batch-size", type=int, default=500)
    parser.add_argument("--json-output", type=Path)
    args = parser.parse_args(argv)
    try:
        report = build_postgres_export_package(args.runtime_root, source_db=args.source_db, batch_size=args.batch_size)
    except Exception as exc:
        report = {
            "status": "failed",
            "error": str(exc),
            "production_data_modified": False,
            "remote_data_modified": False,
        }
    write_json(report, args.json_output)
    return 0 if report.get("status") == "ok" else 1


if __name__ == "__main__":
    raise SystemExit(main())
