"""Local, isolated PostgreSQL probe for shared blob binding transactions.

The collector here is deliberately a test-only simulation using temporary
files. Production request-time physical collection remains disabled.
"""
from __future__ import annotations

import asyncio
import io
import json
import sys
import tempfile
import threading
import uuid
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path
from unittest.mock import AsyncMock, patch
from urllib.parse import urlsplit

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

import psycopg
from psycopg import sql
from fastapi import HTTPException, UploadFile
from classroom_app import config
from classroom_app.db.postgres import LanSharePostgresConnection, sqlite_compatible_dict_row
from classroom_app.services import file_service as files, profile_service as profile
from classroom_app.services import discussion_attachment_service as discussion


def run() -> dict:
    if urlsplit(config.DATABASE_URL).hostname not in {"127.0.0.1", "localhost", "::1"}:
        raise ValueError("This probe only permits a local PostgreSQL server")
    schema = "file_reference_probe_" + uuid.uuid4().hex
    created = False
    checks = {}

    def connect():
        raw = psycopg.connect(config.DATABASE_URL, connect_timeout=5,
            row_factory=sqlite_compatible_dict_row,
            options=f"-c search_path={schema} -c lock_timeout=5000 -c statement_timeout=10000")
        return LanSharePostgresConnection(raw)

    try:
        with psycopg.connect(config.DATABASE_URL, connect_timeout=5, autocommit=True) as admin:
            admin.execute(sql.SQL("CREATE SCHEMA {}").format(sql.Identifier(schema)))
            created = True
        with connect() as conn:
            conn.execute("CREATE TABLE students(id INTEGER PRIMARY KEY,avatar_file_hash TEXT,avatar_mime_type TEXT,avatar_updated_at TEXT)")
            conn.execute("INSERT INTO students(id) VALUES(1)")
            conn.execute("CREATE TABLE course_files(file_hash TEXT)")
            conn.execute("""CREATE TABLE discussion_attachments (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,class_offering_id INTEGER,
                uploaded_by_user_id TEXT,uploaded_by_role TEXT,file_hash TEXT,original_filename TEXT,mime_type TEXT,
                file_size INTEGER,image_width INTEGER,image_height INTEGER,thumbnail_file_hash TEXT,
                thumbnail_mime_type TEXT,thumbnail_file_size INTEGER,thumbnail_width INTEGER,thumbnail_height INTEGER,
                preview_file_hash TEXT,preview_mime_type TEXT,preview_file_size INTEGER,preview_width INTEGER,preview_height INTEGER)""")

        with tempfile.TemporaryDirectory(prefix="lanshare-file-pg-") as directory, \
             patch.object(files, "GLOBAL_FILES_DIR", Path(directory)), patch.object(files, "GLOBAL_FILES_LEGACY_DIRS", ()), \
             patch("classroom_app.db.connection.get_configured_db_engine", return_value="postgres"), \
             patch.object(profile, "get_user_profile", return_value={}), \
             patch.object(discussion, "get_configured_db_engine", return_value="postgres"):

            def bind_course(conn, saved):
                files.bind_global_file_references(conn, (saved["hash"],))
                conn.execute("INSERT INTO course_files VALUES(?)", (saved["hash"],))

            def bind_avatar(conn, saved):
                profile.update_profile_avatar(conn, {"id": 1, "role": "student"}, file_hash=saved["hash"], mime_type="image/png")

            def bind_discussion(conn, saved):
                image = {"file_hash": saved["hash"], "mime_type": "image/png", "file_size": saved["size"], "width": 1, "height": 1}
                derivatives = {"width": 1, "height": 1, "thumbnail": image, "preview": image}
                upload = UploadFile(filename="probe.png", file=io.BytesIO(b"probe"), headers={"content-type": "image/png"})
                with patch.object(discussion, "ensure_discussion_attachment_schema"), \
                     patch.object(discussion, "save_file_globally", new=AsyncMock(return_value=saved)), \
                     patch.object(discussion, "prepare_chat_image_derivatives", new=AsyncMock(return_value=derivatives)), \
                     patch.object(discussion, "build_discussion_attachment_payload", return_value={}):
                    asyncio.run(discussion.create_discussion_attachment(conn, 1, {"id": 1, "role": "student"}, upload))

            for name, binder in (("course", bind_course), ("avatar", bind_avatar), ("discussion", bind_discussion)):
                saved = files.store_file_object_globally(io.BytesIO(name.encode()))
                path, started = Path(saved["path"]), threading.Event()

                def simulate_collector():
                    with connect() as conn:
                        started.set()
                        files.lock_global_file_references(conn, (saved["hash"],), require_exists=False)
                        if files.count_global_file_references(conn, saved["hash"]) == 0:
                            path.unlink()
                            return True
                        return False

                with ThreadPoolExecutor(max_workers=1) as pool, connect() as conn:
                    binder(conn, saved)
                    pending = pool.submit(simulate_collector)
                    assert started.wait(5)
                    conn.commit()
                    checks[name + "_binding_first_retains_blob"] = pending.result(10) is False and path.is_file()

                with connect() as conn:
                    conn.execute("DELETE FROM course_files")
                    conn.execute("UPDATE students SET avatar_file_hash=NULL")
                    conn.execute("DELETE FROM discussion_attachments")
                started.clear()

                def competing_binder():
                    with connect() as conn:
                        started.set()
                        try:
                            binder(conn, saved)
                        except HTTPException as exc:
                            conn.rollback()
                            return exc.status_code == 409 and "重新上传" in str(exc.detail)
                        return False

                with ThreadPoolExecutor(max_workers=1) as pool, connect() as collector:
                    files.lock_global_file_references(collector, (saved["hash"],), require_exists=False)
                    path.unlink()  # Test-only offline collection simulation.
                    pending = pool.submit(competing_binder)
                    assert started.wait(5)
                    collector.commit()
                    checks[name + "_collection_first_returns_conflict"] = pending.result(10)
                with connect() as conn:
                    checks[name + "_no_dangling_reference"] = files.count_global_file_references(conn, saved["hash"]) == 0

            first, second = [files.store_file_object_globally(io.BytesIO(value)) for value in (b"batch-a", b"batch-b")]
            barrier = threading.Barrier(2)
            def bind_batch(values):
                with connect() as conn:
                    barrier.wait(5)
                    files.bind_global_file_references(conn, values)
                    for value in values:
                        conn.execute("INSERT INTO course_files VALUES(?)", (value,))
                    return True
            with ThreadPoolExecutor(max_workers=2) as pool:
                a = pool.submit(bind_batch, [first["hash"], second["hash"]])
                b = pool.submit(bind_batch, [second["hash"], first["hash"]])
                checks["opposite_batch_orders_finish_without_deadlock"] = a.result(10) and b.result(10)
            with connect() as conn:
                conn.execute("DELETE FROM course_files")
                checks["uncommitted_detach_preserves_blob"] = asyncio.run(files.delete_global_file(first["hash"], conn=conn)) is False
                conn.rollback()
                checks["rollback_restores_reference_and_bytes"] = files.count_global_file_references(conn, first["hash"]) == 2 and Path(first["path"]).is_file()
    finally:
        if created:
            if not schema.startswith("file_reference_probe_") or len(schema) != len("file_reference_probe_") + 32:
                raise RuntimeError("Refusing to remove unverified probe schema")
            with psycopg.connect(config.DATABASE_URL, connect_timeout=5, autocommit=True) as admin:
                admin.execute(sql.SQL("DROP SCHEMA {} CASCADE").format(sql.Identifier(schema)))
                assert admin.execute("SELECT COUNT(*) FROM pg_namespace WHERE nspname=%s", (schema,)).fetchone()[0] == 0
    return {"ok": all(checks.values()), "checks": checks, "schema_cleanup": "verified", "production_collection": "disabled"}


if __name__ == "__main__":
    report = run()
    print(json.dumps(report, ensure_ascii=False, indent=2))
    raise SystemExit(0 if report["ok"] else 1)
