"""Real local PostgreSQL acceptance in a unique schema, removed in finally.

Run from the repository root: python tools/validate_lessondoc_editor_postgres.py --run-local
No application rows or public schema DDL are touched. Uses the configured local
DATABASE_URL without printing credentials, and in-memory content-addressed blobs.
"""
from __future__ import annotations

import argparse
import copy
import hashlib
import json
import os
import sys
import threading
import uuid
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path
from unittest import mock


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--run-local", action="store_true", required=True)
    parser.parse_args()
    sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
    os.environ["DB_ENGINE"] = "postgres"
    from classroom_app import config
    import psycopg
    from psycopg import sql
    from psycopg.conninfo import conninfo_to_dict
    from classroom_app.db.postgres import LanSharePostgresConnection, sqlite_compatible_dict_row
    from classroom_app.db import schema_course_doc_packs, schema_lessondoc_editor
    from classroom_app.services.lessondoc import pack_service, editor_service as editor
    from tests.test_lessondoc_service import _PackFixture, _manifest

    if conninfo_to_dict(config.DATABASE_URL).get("host") not in {"127.0.0.1", "localhost", "::1"}:
        raise RuntimeError("This check only accepts a local PostgreSQL host")
    fixture = _PackFixture()
    fixture.setUp()
    try:
        ddl = [row[0].replace("INTEGER PRIMARY KEY AUTOINCREMENT", "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY")
               for row in fixture.conn.execute("SELECT sql FROM sqlite_master WHERE type='table' AND name<>'sqlite_sequence'")]
    finally:
        fixture.doCleanups()
    schema = "lde_qa_" + uuid.uuid4().hex
    admin = psycopg.connect(config.DATABASE_URL, autocommit=True, connect_timeout=10)
    created = False
    blobs = {}
    def store(content):
        key = hashlib.sha256(content.encode("utf-8")).hexdigest()
        blobs[key] = content
        return key, len(content.encode("utf-8"))
    def connection():
        raw = psycopg.connect(config.DATABASE_URL, options="-c search_path=" + schema + " -c lock_timeout=5000 -c statement_timeout=10000",
                               row_factory=sqlite_compatible_dict_row, connect_timeout=10)
        return LanSharePostgresConnection(raw)
    def load(pack, lesson=1):
        with connection() as conn:
            return editor.load_document(conn, pack_id=pack["id"], teacher_id=9, lesson_no=lesson)
    def save(pack, state, operation):
        with connection() as conn:
            return editor.save_document(conn, pack_id=pack["id"], teacher_id=9, lesson_no=state["lesson_no"],
                                         document=state["document"], expected_revision=state["revision"], operation_id=operation)
    checks = []
    try:
        admin.execute(sql.SQL("CREATE SCHEMA {}").format(sql.Identifier(schema)))
        created = True
        with connection() as conn:
            for statement in ddl:
                conn.execute(statement)
            schema_course_doc_packs.ensure_course_doc_pack_schema(conn)
            schema_lessondoc_editor.ensure_lessondoc_editor_schema(conn)
        schema_lessondoc_editor.mark_schema_ready_after_commit()
        with mock.patch("classroom_app.services.session_material_generation_service._store_markdown_bytes", side_effect=store), \
             mock.patch.object(pack_service, "_load_file_text", side_effect=lambda conn, row: blobs.get(row["file_hash"], "")):
            with connection() as conn:
                pack = pack_service.create_pack_skeleton(conn, teacher_id=9, course_id=42, manifest=_manifest(), theme="sky")["pack"]
            initial = load(pack)
            initial["document"]["slides"][1]["blocks"] = [{"type": "text", "id": "body", "md": "initial"}]
            save(pack, initial, "initial_save")
            shared = load(pack)
            barrier = threading.Barrier(2)
            def competing(number):
                state = copy.deepcopy(shared)
                state["document"]["slides"][1]["blocks"][0]["md"] = f"writer {number}"
                barrier.wait(timeout=5)
                try:
                    save(pack, state, f"competing_{number}")
                    return "saved", state, f"competing_{number}"
                except editor.EditorError as exc:
                    return exc.code, state, ""
            with ThreadPoolExecutor(max_workers=2) as pool:
                outcomes = list(pool.map(competing, (1, 2)))
            assert sorted(row[0] for row in outcomes) == ["REVISION_CONFLICT", "saved"], outcomes
            winner = next(row for row in outcomes if row[0] == "saved")
            assert save(pack, winner[1], winner[2])["replayed"]
            checks.extend(["same-document concurrent conflict", "idempotent retry"])
            states = [load(pack, 1), load(pack, 2)]
            for i, state in enumerate(states):
                state["document"]["slides"][1]["blocks"] = [{"type": "text", "id": "body", "md": f"lesson {i+1}"}]
            barrier = threading.Barrier(2)
            def separate(i):
                barrier.wait(timeout=5)
                return save(pack, states[i], f"parallel_lesson_{i}")
            with ThreadPoolExecutor(max_workers=2) as pool:
                list(pool.map(separate, (0, 1)))
            assert all(row["status"] == "ready" for row in load(pack, 0)["document"]["lessons"] if row["n"] in {1, 2})
            checks.append("two lessons preserve both home projections")
            before = load(pack)
            failed = copy.deepcopy(before)
            failed["document"]["title"] = "must roll back"
            try:
                with mock.patch.object(editor, "_projection", side_effect=RuntimeError("injected projection failure")):
                    save(pack, failed, "rollback_failure")
            except RuntimeError:
                pass
            else:
                raise AssertionError("Fault injection did not run")
            assert load(pack)["revision"] == before["revision"]
            with connection() as conn:
                assert conn.execute("SELECT COUNT(*) FROM lessondoc_save_operations WHERE operation_id=?", ("rollback_failure",)).fetchone()[0] == 0
                snapshots = editor.list_revisions(conn, pack_id=pack["id"], teacher_id=9, lesson_no=1)
                restored = editor.restore_revision(conn, pack_id=pack["id"], teacher_id=9, lesson_no=1, revision_id=snapshots[0]["id"], expected_revision=before["revision"], operation_id="history_restore")
            assert restored["revision"] != before["revision"]
            checks.extend(["projection failure rolls back file and receipt", "history restore"])
    finally:
        if created:
            assert schema.startswith("lde_qa_") and len(schema) == 39
            admin.execute(sql.SQL("DROP SCHEMA {} CASCADE").format(sql.Identifier(schema)))
        remains = admin.execute("SELECT COUNT(*) FROM information_schema.schemata WHERE schema_name=%s", (schema,)).fetchone()[0]
        admin.close()
        assert remains == 0
    print(json.dumps({"status": "ok", "checks": checks, "temporary_schema_removed": True}, ensure_ascii=False))


if __name__ == "__main__":
    main()
