from __future__ import annotations

from typing import Any, Sequence

from .errors import DatabaseProgrammingError
from .row import rows_to_mappings
from .sql import quote_identifier


POSTGRES_RUNTIME_UNIQUE_INDEXES: tuple[tuple[str, str, tuple[str, ...]], ...] = (
    (
        "idx_learning_material_progress_unique_material",
        "learning_material_progress",
        ("class_offering_id", "student_id", "material_id"),
    ),
    (
        "idx_learning_stage_status_unique_stage",
        "learning_stage_status",
        ("class_offering_id", "student_id", "stage_key"),
    ),
    (
        "idx_learning_certificates_unique_stage",
        "learning_certificates",
        ("class_offering_id", "student_id", "stage_key"),
    ),
    (
        "idx_student_learning_path_item_states_unique_item",
        "student_learning_path_item_states",
        ("student_id", "item_key"),
    ),
    (
        "idx_student_portfolio_items_unique_source",
        "student_portfolio_items",
        ("student_id", "source_type", "source_id"),
    ),
    (
        "idx_student_portfolio_reflections_unique_item",
        "student_portfolio_reflections",
        ("portfolio_item_id",),
    ),
)


REQUIRED_POSTGRES_TABLES = (
    "teachers",
    "system_settings",
    "teacher_onboarding_state",
    "user_sessions",
    "organization_schools",
    "organization_colleges",
    "organization_departments",
    "teacher_organization_memberships",
    "students",
    "student_shared_teacher_notes",
    "classes",
    "courses",
    "class_offerings",
    "assignments",
    "submissions",
    "submission_files",
    "submission_drafts",
    "submission_draft_files",
    "student_feedback_review_notes",
    "student_login_audit_logs",
    "student_password_reset_requests",
    "academic_semesters",
    "teacher_calendar_events",
    "teacher_academic_course_sync_items",
    "teacher_academic_course_session_occurrences",
    "teacher_academic_roster_sync_items",
    "teacher_academic_roster_memberships",
    "teacher_academic_invigilation_items",
    "teacher_academic_course_exam_items",
    "teacher_academic_exam_roster_items",
    "teacher_academic_exam_roster_students",
    "teacher_academic_teaching_places",
    "academic_semester_calendar_days",
    "textbooks",
    "course_lessons",
    "class_offering_sessions",
    "ai_class_configs",
    "course_files",
    "chunked_uploads",
    "course_materials",
    "course_material_assignments",
    "session_material_generation_tasks",
    "material_ai_import_records",
    "exam_papers",
    "teacher_git_credentials",
    "teacher_academic_system_credentials",
    "teacher_smart_classroom_credentials",
    "smart_classroom_schedule_items",
    "smart_classroom_checkin_sessions",
    "smart_classroom_checkin_students",
    "smart_attendance_daily_tasks",
    "smart_attendance_student_advice",
    "teacher_email_configs",
    "email_outbox",
    "email_worker_heartbeats",
    "agent_tasks",
    "agent_task_events",
    "agent_task_composers",
    "agent_runtime_api_keys",
    "agent_runtime_key_checks",
    "agent_runtime_usage_snapshots",
    "assignment_wrong_answer_ai_cache",
    "exam_paper_difficulty_ai_cache",
    "blog_news_crawler_runs",
    "blog_news_crawler_config",
    "blog_news_crawler_items",
    "blog_posts",
    "blog_comments",
    "blog_likes",
    "blog_bookmarks",
    "blog_attachments",
    "blog_media_assets",
    "blog_moderation_logs",
    "blog_ai_reply_jobs",
    "electronic_signatures",
    "signature_usage_logs",
    "signature_access_requests",
    "assignment_wrong_summary_jobs",
    "classroom_behavior_events",
    "classroom_behavior_states",
    "classroom_behavior_profiles",
    "ui_copy_snapshots",
    "discussion_mood_snapshots",
    "ai_chat_sessions",
    "ai_chat_messages",
    "ai_psychology_profiles",
    "message_center_notifications",
    "private_messages",
    "private_message_blocks",
    "private_message_audit_logs",
    "private_message_attachments",
    "private_message_ai_jobs",
    "study_groups",
    "study_group_members",
    "study_group_files",
    "group_submissions",
    "peer_reviews",
    "classroom_live_activities",
    "classroom_live_options",
    "classroom_live_responses",
    "classroom_live_questions",
    "classroom_live_help_signals",
    "classroom_todos",
    "app_feedback",
    "app_feedback_attachments",
    "chat_logs",
    "chat_log_migrations",
    "discussion_attachments",
    "custom_emojis",
    "emoji_usage_stats",
    "learning_material_progress",
    "learning_stage_status",
    "learning_stage_exam_attempts",
    "learning_certificates",
    "student_learning_path_item_states",
    "student_portfolio_items",
    "student_portfolio_reflections",
    "student_growth_events",
)

REQUIRED_POSTGRES_COLUMNS = {
    "teachers": ("id", "name"),
    "system_settings": ("key", "value", "updated_at"),
    "teacher_onboarding_state": (
        "teacher_id",
        "dismissed_at",
        "completed_at",
        "dismiss_reason",
        "updated_at",
    ),
    "user_sessions": (
        "session_user_key",
        "session_id",
        "user_id",
        "role",
        "name",
        "ip",
        "last_login",
        "expires_at",
        "created_at",
        "updated_at",
    ),
    "organization_schools": (
        "id",
        "school_code",
        "school_name",
        "display_order",
        "is_active",
        "source",
        "created_by_teacher_id",
        "updated_by_teacher_id",
        "created_at",
        "updated_at",
        "deactivated_at",
    ),
    "organization_colleges": (
        "id",
        "school_code",
        "college_name",
        "display_order",
        "is_active",
        "source",
        "created_by_teacher_id",
        "updated_by_teacher_id",
        "created_at",
        "updated_at",
        "deactivated_at",
    ),
    "organization_departments": (
        "id",
        "school_code",
        "college_name",
        "department_name",
        "display_order",
        "is_active",
        "source",
        "created_by_teacher_id",
        "updated_by_teacher_id",
        "created_at",
        "updated_at",
        "deactivated_at",
    ),
    "teacher_organization_memberships": (
        "id",
        "teacher_id",
        "school_code",
        "school_name",
        "college",
        "department",
        "is_primary",
        "is_active",
        "source",
        "created_by_teacher_id",
        "updated_by_teacher_id",
        "created_at",
        "updated_at",
        "deactivated_at",
    ),
    "students": (
        "id",
        "student_id_number",
        "name",
        "class_id",
        "gender",
        "email",
        "phone",
        "enrollment_status",
        "enrollment_status_updated_at",
        "school_code",
        "school_name",
        "college",
        "department",
    ),
    "student_shared_teacher_notes": (
        "student_id",
        "note_text",
        "created_by_teacher_id",
        "updated_by_teacher_id",
        "created_at",
        "updated_at",
    ),
    "classes": (
        "id",
        "name",
        "department",
        "description",
        "created_by_teacher_id",
        "school_code",
        "school_name",
        "college",
    ),
    "courses": (
        "id",
        "name",
        "description",
        "sect_name",
        "department",
        "credits",
        "total_hours",
        "created_by_teacher_id",
        "school_code",
        "school_name",
        "college",
    ),
    "class_offerings": (
        "id",
        "class_id",
        "course_id",
        "teacher_id",
        "semester",
        "semester_id",
        "textbook_id",
        "schedule_info",
        "first_class_date",
        "weekly_schedule_json",
        "schedule_source",
        "academic_teaching_class_name",
        "academic_schedule_sync_at",
        "academic_schedule_sync_message",
        "home_learning_material_id",
    ),
    "assignments": (
        "id",
        "course_id",
        "class_offering_id",
        "title",
        "status",
        "requirements_md",
        "rubric_md",
        "exam_paper_id",
        "allowed_file_types_json",
    ),
    "submissions": (
        "id",
        "assignment_id",
        "student_pk_id",
        "status",
        "score",
        "feedback_md",
        "answers_json",
        "submitted_at",
        "resubmission_allowed",
        "grading_started_at",
        "grading_attempt_fingerprint",
        "score_before_late_penalty",
        "late_penalty_points",
        "late_score_cap_applied",
    ),
    "submission_files": (
        "id",
        "submission_id",
        "stored_path",
        "original_filename",
        "relative_path",
        "mime_type",
        "file_size",
        "file_ext",
        "file_hash",
    ),
    "submission_drafts": (
        "id",
        "assignment_id",
        "student_pk_id",
        "answers_json",
        "current_page",
        "client_updated_at",
        "server_updated_at",
        "server_version",
        "status",
    ),
    "submission_draft_files": (
        "id",
        "draft_id",
        "question_id",
        "kind",
        "original_filename",
        "relative_path",
        "stored_path",
        "mime_type",
        "file_size",
        "file_ext",
        "file_hash",
        "created_at",
    ),
    "student_feedback_review_notes": (
        "id",
        "student_id",
        "submission_id",
        "question_key",
        "status",
        "reflection",
        "next_action",
        "pinned",
        "reviewed_at",
        "mastered_at",
        "created_at",
        "updated_at",
        "metadata_json",
    ),
    "student_login_audit_logs": (
        "id",
        "student_id",
        "class_id",
        "class_name_snapshot",
        "login_sequence",
        "login_method",
        "identifier_type",
        "identifier_value",
        "ip_address",
        "user_agent",
        "device_type",
        "os_name",
        "browser_name",
        "device_label",
        "logged_at",
    ),
    "student_password_reset_requests": (
        "id",
        "student_id",
        "class_id",
        "teacher_id",
        "status",
        "request_name",
        "request_student_id_number",
        "request_class_name",
        "requester_ip",
        "requester_user_agent",
        "requester_device_type",
        "requester_os_name",
        "requester_browser_name",
        "requester_device_label",
        "submitted_at",
        "reviewed_at",
        "completed_at",
        "reviewed_by_teacher_id",
        "review_note",
    ),
    "academic_semesters": (
        "id",
        "teacher_id",
        "school_code",
        "school_name",
        "name",
        "start_date",
        "end_date",
        "week_count",
        "calendar_sync_status",
        "calendar_sync_at",
        "calendar_sync_message",
        "calendar_source_summary_json",
        "created_at",
        "updated_at",
    ),
    "academic_semester_calendar_days": (
        "id",
        "semester_id",
        "teacher_id",
        "date",
        "week_index",
        "weekday",
        "day_type",
        "label",
        "source",
        "source_url",
        "confidence",
        "metadata_json",
        "created_at",
        "updated_at",
    ),
    "teacher_calendar_events": (
        "id",
        "teacher_id",
        "semester_id",
        "source_type",
        "source_id",
        "source_key",
        "title",
        "subtitle",
        "notes",
        "starts_at",
        "ends_at",
        "due_at",
        "location",
        "status",
        "tone",
        "link_url",
        "metadata_json",
        "synced_at",
        "created_at",
        "updated_at",
        "deleted_at",
    ),
    "teacher_academic_course_sync_items": (
        "id",
        "teacher_id",
        "semester_id",
        "course_id",
        "course_code",
        "teaching_class_name",
        "weeks_text",
        "weekday",
        "section_text",
        "location",
        "synced_at",
        "updated_at",
    ),
    "teacher_academic_course_session_occurrences": (
        "id",
        "teacher_id",
        "semester_id",
        "course_id",
        "sync_item_id",
        "teaching_class_name",
        "session_date",
        "section_text",
        "location",
        "synced_at",
        "updated_at",
    ),
    "teacher_academic_roster_sync_items": (
        "id",
        "teacher_id",
        "semester_id",
        "course_id",
        "class_id",
        "school_code",
        "academic_year",
        "academic_term",
        "teaching_class_id",
        "imported_student_count",
        "synced_at",
        "updated_at",
    ),
    "teacher_academic_roster_memberships": (
        "id",
        "teacher_id",
        "semester_id",
        "sync_item_id",
        "class_id",
        "student_id",
        "school_code",
        "academic_year",
        "academic_term",
        "teaching_class_id",
        "student_number",
        "synced_at",
        "updated_at",
    ),
    "teacher_academic_invigilation_items": (
        "id",
        "teacher_id",
        "semester_id",
        "school_code",
        "academic_year",
        "academic_term",
        "invigilation_key",
        "starts_at",
        "ends_at",
        "sync_status",
        "synced_at",
    ),
    "teacher_academic_course_exam_items": (
        "id",
        "teacher_id",
        "semester_id",
        "class_offering_id",
        "course_id",
        "class_id",
        "school_code",
        "academic_year",
        "academic_term",
        "exam_key",
        "course_code",
        "course_name",
        "teaching_class_name",
        "starts_at",
        "ends_at",
        "sync_status",
        "synced_at",
    ),
    "teacher_academic_exam_roster_items": (
        "id",
        "teacher_id",
        "semester_id",
        "class_offering_id",
        "course_id",
        "class_id",
        "school_code",
        "academic_year",
        "academic_term",
        "exam_course_key",
        "course_code",
        "course_name",
        "teaching_class_id",
        "sync_status",
        "synced_at",
        "updated_at",
    ),
    "teacher_academic_exam_roster_students": (
        "id",
        "teacher_id",
        "semester_id",
        "exam_roster_item_id",
        "class_offering_id",
        "class_id",
        "student_id",
        "school_code",
        "academic_year",
        "academic_term",
        "exam_course_key",
        "student_number",
        "student_name",
        "synced_at",
        "updated_at",
    ),
    "teacher_academic_teaching_places": (
        "id",
        "teacher_id",
        "school_code",
        "source",
        "place_key",
        "place_id",
        "room_code",
        "room_name",
        "room_full_name",
        "campus_id",
        "campus_name",
        "building_id",
        "building_name",
        "floor_name",
        "room_type_id",
        "room_type_name",
        "room_subtype_id",
        "room_subtype_name",
        "organization_id",
        "organization_name",
        "manager_name",
        "usage_department",
        "usage_class",
        "borrow_type",
        "seat_count",
        "scheduling_seat_count",
        "exam_seat_count",
        "building_area",
        "is_schedulable",
        "is_borrowable",
        "is_exam_schedulable",
        "conflict_ignored",
        "status_text",
        "note",
        "raw_json",
        "source_url",
        "sync_status",
        "sync_batch_id",
        "synced_at",
        "created_at",
        "updated_at",
    ),
    "textbooks": (
        "id",
        "teacher_id",
        "title",
        "authors_json",
        "publisher",
        "publication_date",
        "introduction",
        "catalog_text",
        "attachment_name",
        "attachment_path",
        "attachment_size",
        "attachment_mime_type",
        "tags_json",
        "owner_role",
        "owner_user_pk",
        "scope_level",
        "school_code",
        "school_name",
        "college",
        "department",
        "created_at",
        "updated_at",
    ),
    "course_lessons": (
        "id",
        "course_id",
        "order_index",
        "title",
        "content",
        "section_count",
        "source_type",
        "learning_material_id",
        "created_at",
        "updated_at",
    ),
    "class_offering_sessions": (
        "id",
        "class_offering_id",
        "course_lesson_id",
        "order_index",
        "title",
        "content",
        "section_count",
        "slot_section_count",
        "session_date",
        "weekday",
        "week_index",
        "schedule_source",
        "learning_material_id",
        "created_at",
        "updated_at",
    ),
    "ai_class_configs": (
        "id",
        "class_offering_id",
        "system_prompt",
        "syllabus",
        "created_at",
        "updated_at",
    ),
    "course_files": (
        "id",
        "course_id",
        "file_name",
        "file_hash",
        "file_size",
        "is_public",
        "is_teacher_resource",
        "description",
        "original_link",
        "uploaded_by_teacher_id",
        "uploaded_at",
    ),
    "chunked_uploads": (
        "id",
        "upload_id",
        "course_id",
        "teacher_id",
        "file_name",
        "file_size",
        "chunk_size",
        "total_chunks",
        "received_chunks",
        "status",
        "temp_dir",
        "description",
        "is_public",
        "is_teacher_resource",
        "created_at",
    ),
    "course_materials": (
        "id",
        "teacher_id",
        "parent_id",
        "root_id",
        "material_path",
        "name",
        "node_type",
        "mime_type",
        "preview_type",
        "ai_capability",
        "file_ext",
        "file_hash",
        "file_size",
        "ai_parse_status",
        "ai_parse_result_json",
        "ai_optimize_status",
        "owner_role",
        "owner_user_pk",
        "scope_level",
        "school_code",
        "school_name",
        "college",
        "department",
        "created_at",
        "updated_at",
    ),
    "course_material_assignments": (
        "id",
        "material_id",
        "class_offering_id",
        "assigned_by_teacher_id",
        "created_at",
    ),
    "session_material_generation_tasks": (
        "id",
        "class_offering_id",
        "session_id",
        "teacher_id",
        "trigger_mode",
        "status",
        "document_type",
        "requirement_text",
        "request_payload_json",
        "result_payload_json",
        "generated_material_id",
        "generated_material_path",
        "error_message",
        "created_at",
        "started_at",
        "completed_at",
        "updated_at",
    ),
    "material_ai_import_records": (
        "id",
        "teacher_id",
        "package_material_id",
        "source_material_id",
        "parsed_material_id",
        "parent_material_id",
        "document_group",
        "document_type",
        "document_type_label",
        "parse_status",
        "parse_mode",
        "extraction_method",
        "source_file_hash",
        "source_file_name",
        "source_file_size",
        "source_mime_type",
        "metadata_json",
        "content_markdown",
        "parsed_payload_json",
        "export_payload_json",
        "warnings_json",
        "content_quality_status",
        "content_quality_json",
        "error_message",
        "created_at",
        "started_at",
        "updated_at",
        "completed_at",
        "failed_at",
    ),
    "exam_papers": ("id", "title"),
    "teacher_git_credentials": (
        "id",
        "teacher_id",
        "remote_key",
        "remote_host",
        "remote_url",
        "provider",
        "auth_mode",
        "username",
        "secret_encrypted",
        "created_at",
        "updated_at",
        "last_used_at",
    ),
    "teacher_academic_system_credentials": (
        "id",
        "teacher_id",
        "school_code",
        "school_name",
        "adapter_key",
        "auth_method",
        "base_url",
        "login_url",
        "username",
        "password_encrypted",
        "display_name",
        "enabled",
        "last_status",
        "last_status_at",
        "last_error",
        "last_verified_at",
        "access_method_json",
        "created_at",
        "updated_at",
    ),
    "teacher_smart_classroom_credentials": (
        "id",
        "teacher_id",
        "platform_code",
        "platform_name",
        "adapter_key",
        "auth_method",
        "base_url",
        "api_base_url",
        "login_url",
        "username",
        "password_encrypted",
        "display_name",
        "enabled",
        "last_status",
        "last_status_at",
        "last_error",
        "last_verified_at",
        "access_method_json",
        "created_at",
        "updated_at",
    ),
    "smart_classroom_schedule_items": (
        "id",
        "teacher_id",
        "class_offering_id",
        "platform_code",
        "remote_schedule_id",
        "remote_course_id",
        "remote_course_name",
        "remote_teaching_class_id",
        "remote_teaching_class_name",
        "academic_year",
        "academic_term",
        "weeks_text",
        "sections_text",
        "weekday",
        "classroom_name",
        "student_count",
        "match_status",
        "match_message",
        "metadata_json",
        "synced_at",
        "created_at",
        "updated_at",
    ),
    "smart_classroom_checkin_sessions": (
        "id",
        "teacher_id",
        "class_offering_id",
        "session_id",
        "schedule_item_id",
        "platform_code",
        "remote_checkin_id",
        "remote_schedule_id",
        "course_code",
        "course_name",
        "teaching_class_name",
        "academic_year",
        "academic_term",
        "week_index",
        "weekday",
        "section_index",
        "checkin_time",
        "stop_time",
        "method",
        "checked_rate",
        "checked_count",
        "unchecked_count",
        "sick_leave_count",
        "personal_leave_count",
        "late_or_early_count",
        "total_count",
        "match_status",
        "match_message",
        "metadata_json",
        "synced_at",
        "created_at",
        "updated_at",
    ),
    "smart_classroom_checkin_students": (
        "id",
        "checkin_session_id",
        "teacher_id",
        "class_offering_id",
        "session_id",
        "student_id",
        "student_number",
        "student_name",
        "status",
        "status_label",
        "local_match_status",
        "metadata_json",
        "synced_at",
        "created_at",
        "updated_at",
    ),
    "smart_attendance_daily_tasks": (
        "id",
        "class_offering_id",
        "teacher_id",
        "task_type",
        "task_date",
        "status",
        "message",
        "raw_payload_json",
        "started_at",
        "finished_at",
        "created_at",
        "updated_at",
    ),
    "smart_attendance_student_advice": (
        "id",
        "class_offering_id",
        "student_id",
        "fingerprint",
        "status",
        "attempts",
        "advice_json",
        "fallback_insights_json",
        "context_json",
        "last_error",
        "first_requested_at",
        "last_requested_at",
        "started_at",
        "completed_at",
        "created_at",
        "updated_at",
    ),
    "email_outbox": (
        "id",
        "config_id",
        "teacher_id",
        "notification_id",
        "dedupe_key",
        "recipient_identity",
        "recipient_role",
        "recipient_user_pk",
        "recipient_email",
        "subject",
        "body_text",
        "body_html",
        "category",
        "severity",
        "status",
        "attempt_count",
        "next_attempt_at",
        "locked_at",
        "sent_at",
        "last_error",
        "created_at",
        "updated_at",
    ),
    "teacher_email_configs": (
        "id",
        "teacher_id",
        "label",
        "provider",
        "smtp_host",
        "smtp_port",
        "smtp_security",
        "smtp_username",
        "smtp_password_encrypted",
        "from_email",
        "from_name",
        "imap_host",
        "imap_port",
        "imap_security",
        "imap_username",
        "imap_password_encrypted",
        "enabled",
        "is_default",
        "per_minute_limit",
        "daily_limit",
        "last_status",
        "last_status_at",
        "last_error",
        "sent_success_count",
        "sent_failure_count",
        "last_sent_at",
        "created_at",
        "updated_at",
    ),
    "email_worker_heartbeats": (
        "worker_id",
        "status",
        "queue_depth",
        "last_error",
        "updated_at",
    ),
    "agent_tasks": ("id", "status", "created_at"),
    "agent_task_events": (
        "id",
        "task_id",
        "event_type",
        "message",
        "detail_json",
        "created_at",
    ),
    "agent_task_composers": (
        "teacher_id",
        "teacher_name",
        "page_label",
        "updated_at",
    ),
    "agent_runtime_api_keys": (
        "id",
        "provider",
        "key_label",
        "key_fingerprint",
        "key_encrypted",
        "key_suffix",
        "base_url",
        "model",
        "enabled",
        "is_active",
        "created_by_teacher_id",
        "last_test_status",
        "last_test_message",
        "last_test_usage_json",
        "last_test_at",
        "last_used_at",
        "created_at",
        "updated_at",
    ),
    "agent_runtime_key_checks": (
        "id",
        "key_id",
        "status",
        "message",
        "response_ms",
        "usage_json",
        "checked_by_teacher_id",
        "created_at",
    ),
    "agent_runtime_usage_snapshots": (
        "id",
        "source",
        "runtime_url",
        "usage_json",
        "fetched_by_teacher_id",
        "created_at",
    ),
    "blog_news_crawler_runs": (
        "id",
        "trigger_source",
        "status",
        "scheduled_for",
        "worker_id",
        "started_at",
        "finished_at",
        "keywords_json",
        "candidate_count",
        "new_candidate_count",
        "duplicate_count",
        "selected_count",
        "published_count",
        "skipped_count",
        "error_message",
        "log_json",
        "created_at",
        "updated_at",
    ),
    "blog_news_crawler_config": (
        "id",
        "enabled",
        "auto_publish",
        "featured_posts",
        "timezone",
        "schedule_window_start",
        "schedule_window_end",
        "recent_days",
        "max_keywords",
        "search_limit_per_keyword",
        "max_candidates_total",
        "max_posts_per_run",
        "article_fetch_limit",
        "fetch_article_pages",
        "fetch_images",
        "max_images_per_post",
        "max_image_bytes",
        "request_timeout_seconds",
        "min_request_interval_seconds",
        "max_request_interval_seconds",
        "extra_keywords_json",
        "blocked_domains_json",
        "source_templates_json",
        "enable_global_search_sources",
        "next_run_at",
        "last_run_id",
        "last_run_at",
        "last_heartbeat_at",
        "worker_id",
        "worker_status",
        "updated_by_teacher_id",
        "updated_at",
    ),
    "blog_news_crawler_items": (
        "id",
        "run_id",
        "keyword",
        "course_names_json",
        "source_name",
        "title",
        "url",
        "canonical_url",
        "url_hash",
        "content_hash",
        "summary",
        "published_at",
        "fetched_at",
        "media_json",
        "score",
        "selected",
        "duplicate_of_item_id",
        "duplicate_of_post_id",
        "post_id",
        "raw_json",
        "created_at",
        "updated_at",
    ),
    "blog_posts": (
        "id",
        "author_identity",
        "author_role",
        "author_user_pk",
        "author_display_name",
        "author_display_mode",
        "author_avatar_hash",
        "author_avatar_mime",
        "title",
        "content_md",
        "summary",
        "cover_image_hash",
        "status",
        "visibility",
        "visible_class_id",
        "visible_user_identities_json",
        "allow_comments",
        "is_pinned",
        "is_featured",
        "pinned_at",
        "featured_at",
        "hot_notified_at",
        "view_count",
        "like_count",
        "comment_count",
        "bookmark_count",
        "system_tags_json",
        "tags_json",
        "edited_at",
        "created_at",
        "updated_at",
    ),
    "blog_comments": (
        "id",
        "post_id",
        "parent_comment_id",
        "author_identity",
        "author_role",
        "author_user_pk",
        "author_display_name",
        "content_md",
        "emoji_payload_json",
        "attachments_json",
        "status",
        "like_count",
        "created_at",
        "updated_at",
    ),
    "blog_likes": (
        "id",
        "target_type",
        "target_id",
        "user_identity",
        "user_role",
        "user_pk",
        "created_at",
    ),
    "blog_bookmarks": (
        "id",
        "post_id",
        "user_identity",
        "user_role",
        "user_pk",
        "created_at",
    ),
    "blog_attachments": (
        "id",
        "post_id",
        "file_hash",
        "original_filename",
        "mime_type",
        "file_size",
        "image_width",
        "image_height",
        "display_order",
        "created_at",
    ),
    "blog_media_assets": (
        "id",
        "file_hash",
        "uploader_identity",
        "uploader_role",
        "uploader_user_pk",
        "original_filename",
        "mime_type",
        "file_size",
        "image_width",
        "image_height",
        "created_at",
        "updated_at",
    ),
    "blog_moderation_logs": (
        "id",
        "post_id",
        "moderator_identity",
        "moderator_role",
        "moderator_user_pk",
        "action",
        "reason",
        "created_at",
    ),
    "blog_ai_reply_jobs": (
        "id",
        "trigger_type",
        "trigger_id",
        "post_id",
        "trigger_author_identity",
        "status",
        "assistant_comment_id",
        "error_message",
        "created_at",
        "updated_at",
    ),
    "electronic_signatures": (
        "id",
        "name",
        "subject_name",
        "subject_role",
        "scope_level",
        "owner_role",
        "owner_id",
        "owner_name_snapshot",
        "uploaded_by_role",
        "uploaded_by_id",
        "uploaded_by_name_snapshot",
        "ownership_updated_at",
        "ownership_updated_by_teacher_id",
        "school_code",
        "school_name",
        "college",
        "department",
        "file_hash",
        "file_ext",
        "mime_type",
        "stored_path",
        "file_size",
        "description",
        "status",
        "legacy_source",
        "legacy_id",
        "metadata_json",
        "created_at",
        "updated_at",
        "deleted_at",
    ),
    "signature_usage_logs": (
        "id",
        "signature_id",
        "signature_name_snapshot",
        "actor_role",
        "actor_id",
        "actor_name_snapshot",
        "action",
        "context_type",
        "context_id",
        "context_label",
        "metadata_json",
        "ip",
        "user_agent",
        "created_at",
    ),
    "signature_access_requests": (
        "id",
        "signature_id",
        "requester_teacher_id",
        "owner_role",
        "owner_id",
        "status",
        "request_note",
        "review_note",
        "context_type",
        "context_id",
        "context_label",
        "requested_at",
        "reviewed_at",
        "reviewed_by_teacher_id",
    ),
    "assignment_wrong_answer_ai_cache": (
        "id",
        "assignment_id",
        "question_key",
        "answer_signature",
        "prompt_version",
        "result_json",
        "created_at",
        "updated_at",
    ),
    "exam_paper_difficulty_ai_cache": (
        "id",
        "exam_paper_id",
        "questions_signature",
        "prompt_version",
        "result_json",
        "created_at",
        "updated_at",
    ),
    "assignment_wrong_summary_jobs": (
        "id",
        "assignment_id",
        "teacher_id",
        "questions_signature",
        "prompt_version",
        "status",
        "pending_text_questions",
        "pending_difficulty",
        "error_message",
        "created_at",
        "started_at",
        "completed_at",
        "run_token",
        "updated_at",
    ),
    "classroom_behavior_events": (
        "id",
        "class_offering_id",
        "user_pk",
        "user_role",
        "display_name",
        "action_type",
        "summary_text",
        "payload_json",
        "created_at",
    ),
    "classroom_behavior_states": (
        "class_offering_id",
        "user_pk",
        "user_role",
        "total_activity_count",
        "last_profiled_activity_count",
        "profile_generation_pending",
        "last_event_at",
        "last_profiled_at",
        "next_profile_interval_seconds",
        "next_profile_due_at",
        "online_accumulated_seconds",
        "current_session_started_at",
        "last_presence_at",
        "last_page_key",
        "last_visibility_state",
        "last_focus_state",
        "last_idle_seconds",
        "focus_total_seconds",
        "blur_total_seconds",
        "visible_total_seconds",
        "hidden_total_seconds",
        "discussion_lurk_total_seconds",
        "ai_panel_open_total_seconds",
        "created_at",
        "updated_at",
    ),
    "classroom_behavior_profiles": (
        "id",
        "class_offering_id",
        "user_pk",
        "user_role",
        "trigger_event_id",
        "round_index",
        "activity_count_snapshot",
        "profile_summary",
        "mental_state_summary",
        "support_strategy",
        "hidden_premise_prompt",
        "personality_traits",
        "preference_summary",
        "language_habit_summary",
        "preferred_ai_style",
        "interest_hypothesis",
        "evidence_summary",
        "trigger_mode",
        "confidence",
        "raw_payload",
        "created_at",
    ),
    "ui_copy_snapshots": (
        "id",
        "snapshot_date",
        "schema_version",
        "source",
        "generation_reason",
        "payload_json",
        "generated_at",
        "updated_at",
    ),
    "discussion_mood_snapshots": (
        "id",
        "class_offering_id",
        "schema_version",
        "source",
        "mood_label",
        "headline",
        "detail",
        "latest_message_id",
        "raw_payload_json",
        "created_at",
        "updated_at",
    ),
    "ai_chat_sessions": (
        "id",
        "session_uuid",
        "class_offering_id",
        "user_pk",
        "user_role",
        "title",
        "context_prompt",
        "created_at",
    ),
    "ai_chat_messages": (
        "id",
        "session_id",
        "role",
        "message",
        "thinking_content",
        "final_answer",
        "attachments_json",
        "timestamp",
    ),
    "ai_psychology_profiles": (
        "id",
        "class_offering_id",
        "session_id",
        "user_pk",
        "user_role",
        "round_index",
        "profile_summary",
        "mental_state_summary",
        "support_strategy",
        "hidden_premise_prompt",
        "confidence",
        "raw_payload",
        "created_at",
    ),
    "message_center_notifications": (
        "id",
        "recipient_identity",
        "recipient_role",
        "recipient_user_pk",
        "category",
        "severity",
        "actor_identity",
        "actor_role",
        "actor_user_pk",
        "actor_display_name",
        "title",
        "body_preview",
        "link_url",
        "class_offering_id",
        "ref_type",
        "ref_id",
        "metadata_json",
        "email_status",
        "email_job_id",
        "read_at",
        "created_at",
    ),
    "private_messages": (
        "id",
        "conversation_key",
        "class_offering_id",
        "sender_identity",
        "sender_role",
        "sender_user_pk",
        "sender_display_name",
        "recipient_identity",
        "recipient_role",
        "recipient_user_pk",
        "recipient_display_name",
        "content",
        "read_at",
        "created_at",
    ),
    "private_message_blocks": (
        "id",
        "owner_identity",
        "owner_role",
        "owner_user_pk",
        "blocked_identity",
        "blocked_role",
        "blocked_user_pk",
        "blocked_display_name",
        "created_at",
    ),
    "private_message_audit_logs": (
        "id",
        "message_id",
        "class_offering_id",
        "sender_identity",
        "sender_role",
        "sender_user_pk",
        "sender_display_name",
        "recipient_identity",
        "recipient_role",
        "recipient_user_pk",
        "recipient_display_name",
        "created_at",
    ),
    "private_message_attachments": (
        "id",
        "message_id",
        "conversation_key",
        "class_offering_id",
        "uploaded_by_identity",
        "uploaded_by_role",
        "file_hash",
        "original_filename",
        "mime_type",
        "file_size",
        "attachment_kind",
        "image_width",
        "image_height",
        "thumbnail_file_hash",
        "thumbnail_mime_type",
        "thumbnail_file_size",
        "thumbnail_width",
        "thumbnail_height",
        "preview_file_hash",
        "preview_mime_type",
        "preview_file_size",
        "preview_width",
        "preview_height",
        "created_at",
    ),
    "private_message_ai_jobs": (
        "id",
        "conversation_key",
        "class_offering_id",
        "request_message_id",
        "requester_identity",
        "status",
        "error_message",
        "reply_message_id",
        "attempt_count",
        "created_at",
        "started_at",
        "finished_at",
        "updated_at",
    ),
    "study_groups": (
        "id",
        "class_offering_id",
        "assignment_id",
        "name",
        "description",
        "status",
        "join_policy",
        "max_members",
        "leader_student_id",
        "created_by_role",
        "created_by_user_pk",
        "created_at",
        "updated_at",
        "archived_at",
        "metadata_json",
    ),
    "study_group_members": (
        "id",
        "group_id",
        "student_id",
        "member_role",
        "status",
        "contribution_summary",
        "contribution_score",
        "joined_at",
        "left_at",
        "added_by_role",
        "added_by_user_pk",
        "metadata_json",
    ),
    "study_group_files": (
        "id",
        "group_id",
        "uploaded_by_role",
        "uploaded_by_user_pk",
        "uploaded_by_name",
        "file_hash",
        "original_filename",
        "mime_type",
        "file_size",
        "description",
        "created_at",
        "metadata_json",
    ),
    "group_submissions": (
        "id",
        "group_id",
        "assignment_id",
        "submitted_by_role",
        "submitted_by_user_pk",
        "title",
        "summary_md",
        "final_file_id",
        "blog_post_id",
        "status",
        "submitted_at",
        "updated_at",
        "teacher_feedback_md",
        "metadata_json",
    ),
    "peer_reviews": (
        "id",
        "class_offering_id",
        "group_id",
        "assignment_id",
        "reviewer_student_id",
        "reviewee_student_id",
        "responsibility_score",
        "collaboration_score",
        "quality_score",
        "comment",
        "share_with_reviewee",
        "status",
        "created_at",
        "updated_at",
        "metadata_json",
    ),
    "classroom_live_activities": (
        "id",
        "class_offering_id",
        "kind",
        "title",
        "prompt",
        "status",
        "allow_anonymous",
        "show_results",
        "created_by_teacher_id",
        "created_by_name",
        "created_at",
        "updated_at",
        "started_at",
        "closed_at",
        "settings_json",
    ),
    "classroom_live_options": (
        "id",
        "activity_id",
        "option_key",
        "label",
        "is_correct",
        "sort_order",
        "created_at",
    ),
    "classroom_live_responses": (
        "id",
        "activity_id",
        "student_id",
        "option_id",
        "response_text",
        "is_anonymous",
        "created_at",
        "updated_at",
        "metadata_json",
    ),
    "classroom_live_questions": (
        "id",
        "activity_id",
        "class_offering_id",
        "student_id",
        "display_name",
        "question_text",
        "is_anonymous",
        "status",
        "created_at",
        "updated_at",
        "addressed_at",
        "addressed_by_teacher_id",
        "metadata_json",
    ),
    "classroom_live_help_signals": (
        "id",
        "class_offering_id",
        "student_id",
        "display_name",
        "signal_type",
        "status",
        "message",
        "created_at",
        "updated_at",
        "resolved_at",
        "resolved_by_teacher_id",
        "metadata_json",
    ),
    "classroom_todos": (
        "id",
        "class_offering_id",
        "owner_role",
        "owner_user_pk",
        "title",
        "notes",
        "start_at",
        "due_at",
        "completed_at",
        "created_at",
        "updated_at",
        "deleted_at",
        "metadata_json",
    ),
    "app_feedback": (
        "id",
        "user_id",
        "user_role",
        "user_name",
        "feedback_type",
        "section",
        "title",
        "description",
        "page_url",
        "status",
        "created_at",
        "updated_at",
    ),
    "app_feedback_attachments": (
        "id",
        "feedback_id",
        "file_hash",
        "original_filename",
        "file_size",
        "mime_type",
        "created_at",
    ),
    "chat_logs": (
        "id",
        "class_offering_id",
        "user_id",
        "user_name",
        "user_role",
        "message",
        "timestamp",
        "logged_at",
        "message_type",
        "emoji_payload_json",
        "attachments_json",
        "quote_message_id",
        "quote_payload_json",
    ),
    "chat_log_migrations": (
        "class_offering_id",
        "migrated_at",
    ),
    "discussion_attachments": (
        "id",
        "class_offering_id",
        "uploaded_by_user_id",
        "uploaded_by_role",
        "file_hash",
        "original_filename",
        "mime_type",
        "file_size",
        "image_width",
        "image_height",
        "thumbnail_file_hash",
        "thumbnail_mime_type",
        "thumbnail_file_size",
        "thumbnail_width",
        "thumbnail_height",
        "preview_file_hash",
        "preview_mime_type",
        "preview_file_size",
        "preview_width",
        "preview_height",
        "created_at",
    ),
    "custom_emojis": (
        "id",
        "class_offering_id",
        "owner_user_id",
        "owner_user_role",
        "display_name",
        "original_filename",
        "file_hash",
        "mime_type",
        "file_size",
        "image_width",
        "image_height",
        "created_at",
        "updated_at",
    ),
    "emoji_usage_stats": (
        "id",
        "class_offering_id",
        "user_id",
        "user_role",
        "emoji_type",
        "emoji_key",
        "usage_count",
        "last_used_at",
        "created_at",
    ),
    "learning_material_progress": (
        "id",
        "class_offering_id",
        "student_id",
        "material_id",
        "session_id",
        "view_count",
        "accumulated_seconds",
        "active_seconds",
        "max_scroll_ratio",
        "completed",
        "first_viewed_at",
        "last_viewed_at",
        "updated_at",
        "metadata_json",
    ),
    "learning_stage_status": (
        "id",
        "class_offering_id",
        "student_id",
        "stage_key",
        "status",
        "progress_score",
        "readiness_score",
        "unlocked_at",
        "passed_at",
        "last_exam_assignment_id",
        "certificate_id",
        "last_calculated_at",
        "metadata_json",
    ),
    "learning_stage_exam_attempts": (
        "id",
        "class_offering_id",
        "student_id",
        "stage_key",
        "assignment_id",
        "exam_paper_id",
        "status",
        "score",
        "generated_at",
        "submitted_at",
        "graded_at",
        "passed_at",
        "ai_error",
        "metadata_json",
    ),
    "learning_certificates": (
        "id",
        "class_offering_id",
        "student_id",
        "stage_key",
        "level_key",
        "level_name",
        "tier",
        "title",
        "certificate_code",
        "issued_at",
        "metadata_json",
    ),
    "student_learning_path_item_states": (
        "id",
        "student_id",
        "class_offering_id",
        "item_key",
        "status",
        "pinned",
        "reflection",
        "next_action",
        "completed_at",
        "snoozed_until",
        "created_at",
        "updated_at",
        "metadata_json",
    ),
    "student_portfolio_items": (
        "id",
        "student_id",
        "class_offering_id",
        "course_id",
        "source_type",
        "source_id",
        "title",
        "summary",
        "artifact_type",
        "cover_file_hash",
        "visibility",
        "featured",
        "teacher_recommended",
        "teacher_recommended_by",
        "teacher_recommended_at",
        "sort_order",
        "created_at",
        "updated_at",
        "metadata_json",
    ),
    "student_portfolio_reflections": (
        "id",
        "portfolio_item_id",
        "student_id",
        "reflection_text",
        "ability_tags_json",
        "evidence_notes",
        "updated_at",
    ),
    "student_growth_events": (
        "id",
        "student_id",
        "class_offering_id",
        "event_type",
        "source_type",
        "source_id",
        "title",
        "description",
        "occurred_at",
        "importance",
        "metadata_json",
    ),
}


def _fetch_mappings(
    conn: Any,
    sql: str,
    params: Sequence[Any] | None = None,
    *,
    columns: Sequence[str],
) -> list[dict[str, Any]]:
    cursor = conn.execute(sql, tuple(params or ()))
    return rows_to_mappings(cursor.fetchall(), columns)


def _public_tables(conn: Any) -> set[str]:
    rows = _fetch_mappings(
        conn,
        """
        SELECT table_name
        FROM information_schema.tables
        WHERE table_schema = ?
          AND table_type = ?
        """,
        ("public", "BASE TABLE"),
        columns=("table_name",),
    )
    return {str(row["table_name"]) for row in rows}


def _public_columns(conn: Any) -> dict[str, set[str]]:
    rows = _fetch_mappings(
        conn,
        """
        SELECT table_name, column_name
        FROM information_schema.columns
        WHERE table_schema = ?
        """,
        ("public",),
        columns=("table_name", "column_name"),
    )
    columns_by_table: dict[str, set[str]] = {}
    for row in rows:
        table_name = str(row["table_name"])
        columns_by_table.setdefault(table_name, set()).add(str(row["column_name"]))
    return columns_by_table


def _count_rows(conn: Any, table: str) -> int | None:
    cursor = conn.execute(f"SELECT COUNT(*) AS row_count FROM {quote_identifier(table)}")
    rows = rows_to_mappings(cursor.fetchall(), ("row_count",))
    if not rows:
        return None
    value = rows[0].get("row_count")
    return int(value) if value is not None else None


def _index_exists(conn: Any, index_name: str) -> bool:
    rows = conn.execute(
        """
        SELECT 1 AS exists_flag
        FROM pg_indexes
        WHERE schemaname = ?
          AND indexname = ?
        LIMIT 1
        """,
        ("public", index_name),
    ).fetchall()
    return bool(rows)


def _duplicate_unique_key_rows(conn: Any, table: str, columns: Sequence[str]) -> list[dict[str, Any]]:
    column_sql = ", ".join(quote_identifier(column) for column in columns)
    rows = conn.execute(
        f"""
        SELECT {column_sql}, COUNT(*) AS row_count
        FROM {quote_identifier(table)}
        GROUP BY {column_sql}
        HAVING COUNT(*) > 1
        LIMIT 5
        """
    ).fetchall()
    return rows_to_mappings(rows, (*columns, "row_count"))


def ensure_postgres_runtime_constraints(conn: Any) -> dict[str, Any]:
    created_indexes: list[str] = []
    skipped_indexes: list[str] = []
    table_names = _public_tables(conn)
    for index_name, table, columns in POSTGRES_RUNTIME_UNIQUE_INDEXES:
        if table not in table_names:
            skipped_indexes.append(index_name)
            continue
        if _index_exists(conn, index_name):
            continue
        duplicate_rows = _duplicate_unique_key_rows(conn, table, columns)
        if duplicate_rows:
            raise DatabaseProgrammingError(
                "PostgreSQL schema repair refused to create unique index "
                f"{index_name} because duplicate keys exist in {table}: {duplicate_rows}"
            )
        column_sql = ", ".join(quote_identifier(column) for column in columns)
        conn.execute(
            f"CREATE UNIQUE INDEX IF NOT EXISTS {quote_identifier(index_name)} "
            f"ON {quote_identifier(table)} ({column_sql})"
        )
        created_indexes.append(index_name)
    return {
        "created_indexes": created_indexes,
        "skipped_indexes": skipped_indexes,
        "schema_writes_executed": bool(created_indexes),
    }


def build_postgres_schema_report(conn: Any) -> dict[str, Any]:
    table_names = _public_tables(conn)
    columns_by_table = _public_columns(conn)
    missing_tables = [
        table
        for table in REQUIRED_POSTGRES_TABLES
        if table not in table_names
    ]
    missing_columns: dict[str, list[str]] = {}
    for table, required_columns in REQUIRED_POSTGRES_COLUMNS.items():
        if table in missing_tables:
            continue
        actual_columns = columns_by_table.get(table, set())
        missing = [column for column in required_columns if column not in actual_columns]
        if missing:
            missing_columns[table] = missing

    row_counts: dict[str, int | None] = {}
    for table in REQUIRED_POSTGRES_TABLES:
        if table in missing_tables:
            row_counts[table] = None
            continue
        row_counts[table] = _count_rows(conn, table)

    return {
        "status": "ok" if not missing_tables and not missing_columns else "failed",
        "required_table_count": len(REQUIRED_POSTGRES_TABLES),
        "present_required_table_count": len(REQUIRED_POSTGRES_TABLES) - len(missing_tables),
        "missing_tables": missing_tables,
        "missing_columns": missing_columns,
        "row_counts": row_counts,
        "schema_writes_executed": False,
    }


def validate_postgres_schema(conn: Any) -> dict[str, Any]:
    report = build_postgres_schema_report(conn)
    if report["status"] != "ok":
        details: list[str] = []
        if report["missing_tables"]:
            details.append("missing tables: " + ", ".join(report["missing_tables"]))
        if report["missing_columns"]:
            formatted = [
                f"{table}({', '.join(columns)})"
                for table, columns in report["missing_columns"].items()
            ]
            details.append("missing columns: " + "; ".join(formatted))
        raise DatabaseProgrammingError(
            "PostgreSQL schema validation failed; refusing to run SQLite schema initializers. "
            + " ".join(details)
        )
    return report
