"""Schema for the unified scheduled-task scheduler.

The scheduler is a generic timer: callers persist a row in ``scheduled_tasks``
with a ``run_at`` and a ``task_kind`` (mapped to a registered handler), and a
dedicated worker container claims due rows and dispatches them. It supports
one-shot tasks (``recurrence_seconds IS NULL``) and recurring tasks.

The DDL is engine-aware and idempotent (``CREATE TABLE IF NOT EXISTS`` on both
SQLite and PostgreSQL) so it can be ensured lazily at runtime without touching
the central PostgreSQL migration. Timestamps are stored as ISO-8601 TEXT to
stay consistent with the rest of the codebase (e.g. ``email_outbox``).
"""

from __future__ import annotations

from typing import Any

from .connection import get_configured_db_engine


def ensure_scheduler_schema(conn: Any) -> None:
    """Create the scheduler tables if they do not exist (sqlite + postgres)."""
    engine = get_configured_db_engine()
    id_column = (
        "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
        if engine == "postgres"
        else "id INTEGER PRIMARY KEY AUTOINCREMENT"
    )

    conn.execute(
        f"""
        CREATE TABLE IF NOT EXISTS scheduled_tasks (
            {id_column},
            task_kind TEXT NOT NULL,
            dedupe_key TEXT,
            title TEXT NOT NULL DEFAULT '',
            status TEXT NOT NULL DEFAULT 'pending',
            priority INTEGER NOT NULL DEFAULT 100,
            run_at TEXT NOT NULL,
            recurrence_seconds INTEGER,
            payload_json TEXT NOT NULL DEFAULT '{{}}',
            owner_role TEXT NOT NULL DEFAULT '',
            owner_user_pk INTEGER,
            attempt_count INTEGER NOT NULL DEFAULT 0,
            max_attempts INTEGER NOT NULL DEFAULT 5,
            next_attempt_at TEXT,
            locked_at TEXT,
            locked_by TEXT NOT NULL DEFAULT '',
            last_error TEXT NOT NULL DEFAULT '',
            last_result TEXT NOT NULL DEFAULT '',
            started_at TEXT,
            finished_at TEXT,
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
        )
        """
    )
    # Unique dedupe key (partial: only when set) so callers can upsert a task by
    # a stable key (e.g. one reminder per teacher+calendar event). Both engines
    # allow multiple NULLs in a UNIQUE index, which is exactly what we want.
    conn.execute(
        "CREATE UNIQUE INDEX IF NOT EXISTS idx_scheduled_tasks_dedupe_key "
        "ON scheduled_tasks (dedupe_key)"
    )
    conn.execute(
        "CREATE INDEX IF NOT EXISTS idx_scheduled_tasks_due "
        "ON scheduled_tasks (status, run_at)"
    )
    conn.execute(
        "CREATE INDEX IF NOT EXISTS idx_scheduled_tasks_owner "
        "ON scheduled_tasks (owner_role, owner_user_pk, status)"
    )
    conn.execute(
        "CREATE INDEX IF NOT EXISTS idx_scheduled_tasks_kind "
        "ON scheduled_tasks (task_kind, status)"
    )

    conn.execute(
        """
        CREATE TABLE IF NOT EXISTS scheduled_task_worker_heartbeats (
            worker_id TEXT PRIMARY KEY,
            status TEXT NOT NULL DEFAULT '',
            queue_depth INTEGER NOT NULL DEFAULT 0,
            last_error TEXT NOT NULL DEFAULT '',
            updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
        )
        """
    )
