"""Schema for the student career-development network feature.

Two tables:

* ``career_major_networks`` — one cached career network per (school, major).
  The software-engineering network ships as a built-in *seed*; networks for
  any other major (网络工程、文科专业 …) are generated on demand by the
  deep-thinking AI and cached here so every student of that major reuses them.
* ``career_student_sessions`` — one row per student tracking the welcome /
  personality-test / AI-personalisation lifecycle and the per-student
  recommendation overrides + pre-graduation knowledge cards.

The DDL is engine-aware and idempotent (``CREATE TABLE IF NOT EXISTS`` on both
SQLite and PostgreSQL) so it can be ensured lazily at runtime without touching
the central SQLite->PostgreSQL migration — mirroring ``schema_scheduler`` and
``schema_study_group_scheme``. Timestamps are ISO-8601 TEXT.
"""

from __future__ import annotations

from typing import Any

from .connection import get_configured_db_engine

_SCHEMA_READY = False


def _add_column(conn: Any, table: str, column: str, definition: str, *, engine: str) -> None:
    """Idempotently add a column to an existing table on either engine."""
    if engine == "postgres":
        conn.execute(f"ALTER TABLE {table} ADD COLUMN IF NOT EXISTS {column} {definition}")
        return
    try:
        conn.execute(f"ALTER TABLE {table} ADD COLUMN {column} {definition}")
    except Exception:
        pass


def ensure_career_path_schema(conn: Any) -> None:
    """Create the career-network + per-student session tables (sqlite + postgres)."""
    global _SCHEMA_READY
    if _SCHEMA_READY:
        return
    engine = get_configured_db_engine()
    id_column = (
        "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
        if engine == "postgres"
        else "id INTEGER PRIMARY KEY AUTOINCREMENT"
    )

    # Per-major cached network. major_key is a normalized slug of the major name
    # (so "软件工程" / "软件工程技术" collapse to the same seed where intended).
    conn.execute(
        f"""
        CREATE TABLE IF NOT EXISTS career_major_networks (
            {id_column},
            school_code TEXT NOT NULL DEFAULT 'gxufl',
            major_key TEXT NOT NULL,
            major_name TEXT NOT NULL DEFAULT '',
            status TEXT NOT NULL DEFAULT 'ready',
            source TEXT NOT NULL DEFAULT 'seed',
            network_json TEXT NOT NULL DEFAULT '{{}}',
            knowledge_json TEXT NOT NULL DEFAULT '{{}}',
            doc_markdown TEXT NOT NULL DEFAULT '',
            model_label TEXT NOT NULL DEFAULT '',
            error_message TEXT NOT NULL DEFAULT '',
            generated_at TEXT,
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            UNIQUE (school_code, major_key)
        )
        """
    )
    conn.execute(
        "CREATE INDEX IF NOT EXISTS idx_career_major_networks_lookup "
        "ON career_major_networks (school_code, major_key, status)"
    )

    # Per-student lifecycle + personalisation.
    conn.execute(
        f"""
        CREATE TABLE IF NOT EXISTS career_student_sessions (
            {id_column},
            student_id INTEGER NOT NULL,
            school_code TEXT NOT NULL DEFAULT 'gxufl',
            major_key TEXT NOT NULL DEFAULT '',
            major_name TEXT NOT NULL DEFAULT '',
            status TEXT NOT NULL DEFAULT 'intro',
            enrollment_year INTEGER,
            graduation_year INTEGER,
            program_duration_years INTEGER,
            test_answers_json TEXT NOT NULL DEFAULT '[]',
            test_result_json TEXT NOT NULL DEFAULT '{{}}',
            personalized_json TEXT NOT NULL DEFAULT '{{}}',
            model_label TEXT NOT NULL DEFAULT '',
            error_message TEXT NOT NULL DEFAULT '',
            submitted_at TEXT,
            generated_at TEXT,
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            UNIQUE (student_id)
        )
        """
    )
    conn.execute(
        "CREATE INDEX IF NOT EXISTS idx_career_student_sessions_status "
        "ON career_student_sessions (status, updated_at DESC)"
    )

    # Backfill columns for databases created before a column existed.
    _add_column(conn, "career_student_sessions", "program_duration_years", "INTEGER", engine=engine)
    _add_column(conn, "career_major_networks", "error_message", "TEXT NOT NULL DEFAULT ''", engine=engine)

    _SCHEMA_READY = True
