"""Additive, immutable per-student grade publication snapshots."""
from __future__ import annotations
from .connection import get_configured_db_engine


def grade_publication_schema_statements(engine: str) -> tuple[str, ...]:
    identity = "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY" if engine == "postgres" else "INTEGER PRIMARY KEY AUTOINCREMENT"
    return (
        f"""CREATE TABLE IF NOT EXISTS grade_publications (
            id {identity}, class_offering_id BIGINT NOT NULL, semester_id BIGINT,
            teacher_id BIGINT NOT NULL, version INTEGER NOT NULL, status TEXT NOT NULL DEFAULT 'active',
            source_record_id BIGINT NOT NULL, source_document_type TEXT NOT NULL,
            source_updated_at TEXT NOT NULL DEFAULT '', source_hash TEXT NOT NULL,
            source_snapshot_json TEXT NOT NULL, formula_json TEXT NOT NULL,
            confirmation_json TEXT NOT NULL DEFAULT '{{}}', published_at TEXT NOT NULL,
            withdrawn_at TEXT, withdrawn_by_teacher_id BIGINT, withdrawal_reason TEXT,
            UNIQUE(class_offering_id, version), CHECK(status IN ('active','superseded','withdrawn'))
        )""",
        """CREATE TABLE IF NOT EXISTS grade_publication_students (
            publication_id BIGINT NOT NULL REFERENCES grade_publications(id), student_pk_id BIGINT NOT NULL,
            student_number TEXT NOT NULL, scores_json TEXT NOT NULL,
            PRIMARY KEY(publication_id, student_pk_id)
        )""",
        "CREATE UNIQUE INDEX IF NOT EXISTS idx_grade_publications_active ON grade_publications(class_offering_id) WHERE status = 'active'",
        "CREATE INDEX IF NOT EXISTS idx_grade_publication_students_self ON grade_publication_students(student_pk_id, publication_id)",
    )


def ensure_grade_publication_schema(conn, *, engine: str | None = None) -> None:
    for sql in grade_publication_schema_statements(engine or get_configured_db_engine()):
        conn.execute(sql)


GRADE_PUBLICATION_POSTGRES_TABLES = dict(zip(
    ("grade_publications", "grade_publication_students"), grade_publication_schema_statements("postgres")[:2],
))
GRADE_PUBLICATION_REQUIRED_COLUMNS = {
    "grade_publications": (
        "id", "class_offering_id", "semester_id", "teacher_id", "version", "status", "source_record_id",
        "source_document_type", "source_updated_at", "source_hash", "source_snapshot_json", "formula_json",
        "confirmation_json", "published_at", "withdrawn_at", "withdrawn_by_teacher_id", "withdrawal_reason",
    ),
    "grade_publication_students": ("publication_id", "student_pk_id", "student_number", "scores_json"),
}
