"""Schema for the WeChat Mini Program access layer (微信小程序端).

Two runtime tables, mirroring the lazy engine-aware pattern of
``schema_life_tips`` (ensured on first use, never part of the central
migration REQUIRED set):

- ``wechat_bindings``  — one row per WeChat identity bound to a platform
  account. ``openid`` is UNIQUE: one WeChat user maps to exactly one
  account (student or teacher). Rebinding revokes the old row first.
- ``mp_sessions``      — long-lived opaque tokens for the mini program
  (``Authorization: Bearer``). Stored as SHA-256 (``token_hash``); the
  clear token never touches the database. Sliding expiry is applied in
  the service layer. Deliberately separate from the web JWT session
  store: web sessions are IP-bound and single-session-per-user, both of
  which are wrong for a phone on cellular networks.

Timestamps are ISO-8601 TEXT, booleans INTEGER 0/1, per codebase
convention.
"""

from __future__ import annotations

from typing import Any

from .connection import get_configured_db_engine

_SCHEMA_READY = False


def ensure_wechat_mp_schema(conn: Any) -> None:
    """Create the mini-program tables on either engine (idempotent)."""
    global _SCHEMA_READY
    if _SCHEMA_READY:
        return
    engine = get_configured_db_engine()
    id_column = (
        "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
        if engine == "postgres"
        else "id INTEGER PRIMARY KEY AUTOINCREMENT"
    )

    conn.execute(
        f"""
        CREATE TABLE IF NOT EXISTS wechat_bindings (
            {id_column},
            user_role TEXT NOT NULL,
            user_pk INTEGER NOT NULL,
            openid TEXT NOT NULL,
            unionid TEXT NOT NULL DEFAULT '',
            status TEXT NOT NULL DEFAULT 'active',
            bound_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            last_login_at TEXT NOT NULL DEFAULT '',
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            UNIQUE (openid)
        )
        """
    )
    conn.execute(
        "CREATE INDEX IF NOT EXISTS idx_wechat_bindings_user "
        "ON wechat_bindings (user_role, user_pk, status)"
    )

    conn.execute(
        f"""
        CREATE TABLE IF NOT EXISTS mp_sessions (
            {id_column},
            token_hash TEXT NOT NULL,
            user_role TEXT NOT NULL,
            user_pk INTEGER NOT NULL,
            openid TEXT NOT NULL DEFAULT '',
            issued_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            expires_at TEXT NOT NULL,
            last_seen_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            revoked INTEGER NOT NULL DEFAULT 0,
            UNIQUE (token_hash)
        )
        """
    )
    conn.execute(
        "CREATE INDEX IF NOT EXISTS idx_mp_sessions_user "
        "ON mp_sessions (user_role, user_pk, revoked)"
    )

    _SCHEMA_READY = True
