from __future__ import annotations

import sqlite3
from typing import Any

from .connection import get_configured_db_engine


_SCHEMA_READY_ENGINES: set[str] = set()

AI_JOB_POSTGRES_RUNTIME_COLUMNS = {
    "ai_jobs": {"capacity_reserved_until": "TEXT"},
    "submissions": {
        "grading_revision_hash": "TEXT",
        "active_grade_revision_id": "BIGINT",
        "grading_job_id": "BIGINT",
    }
}

AI_JOB_POSTGRES_RUNTIME_TABLES = {
    "ai_jobs": """
        CREATE TABLE IF NOT EXISTS ai_jobs (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            task_type TEXT NOT NULL, priority INTEGER NOT NULL DEFAULT 100,
            status TEXT NOT NULL DEFAULT 'queued', dedupe_key TEXT NOT NULL UNIQUE,
            payload_json TEXT NOT NULL DEFAULT '{}', payload_hash TEXT NOT NULL DEFAULT '',
            input_schema_version TEXT NOT NULL DEFAULT 'v1', policy_version TEXT NOT NULL DEFAULT '',
            scope_type TEXT NOT NULL DEFAULT '', scope_id TEXT NOT NULL DEFAULT '',
            owner_role TEXT NOT NULL DEFAULT '', owner_user_pk INTEGER, source_ref TEXT NOT NULL DEFAULT '',
            attempt_count INTEGER NOT NULL DEFAULT 0, max_attempts INTEGER NOT NULL DEFAULT 8,
            delivery_attempt_count INTEGER NOT NULL DEFAULT 0, available_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            locked_at TEXT, locked_by TEXT NOT NULL DEFAULT '', lease_token TEXT NOT NULL DEFAULT '',
            lease_expires_at TEXT, heartbeat_at TEXT, capacity_reserved_until TEXT, result_id BIGINT,
            review_required INTEGER NOT NULL DEFAULT 0, last_error_code TEXT NOT NULL DEFAULT '',
            last_error TEXT NOT NULL DEFAULT '', created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, started_at TEXT, finished_at TEXT
        )
    """,
    "ai_job_attempts": """
        CREATE TABLE IF NOT EXISTS ai_job_attempts (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            job_id BIGINT NOT NULL REFERENCES ai_jobs(id) ON DELETE CASCADE,
            attempt_no INTEGER NOT NULL, stage TEXT NOT NULL DEFAULT 'execute',
            status TEXT NOT NULL DEFAULT 'running', provider TEXT NOT NULL DEFAULT '', model TEXT NOT NULL DEFAULT '',
            prompt_tokens INTEGER NOT NULL DEFAULT 0, completion_tokens INTEGER NOT NULL DEFAULT 0,
            estimated_cost_cny DOUBLE PRECISION NOT NULL DEFAULT 0,
            error_code TEXT NOT NULL DEFAULT '', error_message TEXT NOT NULL DEFAULT '',
            metadata_json TEXT NOT NULL DEFAULT '{}', started_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            finished_at TEXT, UNIQUE(job_id, attempt_no, stage)
        )
    """,
    "ai_job_results": """
        CREATE TABLE IF NOT EXISTS ai_job_results (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            job_id BIGINT NOT NULL REFERENCES ai_jobs(id) ON DELETE CASCADE,
            result_hash TEXT NOT NULL, result_json TEXT NOT NULL DEFAULT '{}', status TEXT NOT NULL DEFAULT 'candidate',
            provider TEXT NOT NULL DEFAULT '', model TEXT NOT NULL DEFAULT '', prompt_version TEXT NOT NULL DEFAULT '',
            rubric_hash TEXT NOT NULL DEFAULT '', policy_version TEXT NOT NULL DEFAULT '',
            deterministic_version TEXT NOT NULL DEFAULT '', confidence DOUBLE PRECISION,
            review_required INTEGER NOT NULL DEFAULT 0, quality_audit_json TEXT NOT NULL DEFAULT '{}',
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE(job_id, result_hash)
        )
    """,
    "submission_grade_revisions": """
        CREATE TABLE IF NOT EXISTS submission_grade_revisions (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            submission_id BIGINT NOT NULL REFERENCES submissions(id) ON DELETE CASCADE,
            ai_job_id BIGINT REFERENCES ai_jobs(id) ON DELETE SET NULL,
            ai_result_id BIGINT REFERENCES ai_job_results(id) ON DELETE SET NULL,
            revision_hash TEXT NOT NULL, revision_no INTEGER NOT NULL DEFAULT 1,
            status TEXT NOT NULL DEFAULT 'candidate', score DOUBLE PRECISION,
            feedback_md TEXT NOT NULL DEFAULT '', quality_audit_json TEXT NOT NULL DEFAULT '{}',
            provenance_json TEXT NOT NULL DEFAULT '{}', created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            activated_at TEXT, superseded_at TEXT, UNIQUE(submission_id, revision_hash)
        )
    """,
}

AI_JOB_REQUIRED_POSTGRES_COLUMNS = {
    "ai_jobs": (
        "id", "task_type", "priority", "status", "dedupe_key", "payload_json", "payload_hash",
        "attempt_count", "max_attempts", "available_at", "locked_at", "locked_by", "lease_token",
        "lease_expires_at", "capacity_reserved_until", "result_id", "review_required", "created_at", "updated_at",
    ),
    "ai_job_attempts": (
        "id", "job_id", "attempt_no", "stage", "status", "provider", "model", "error_code",
        "error_message", "started_at", "finished_at",
    ),
    "ai_job_results": (
        "id", "job_id", "result_hash", "result_json", "status", "provider", "model", "prompt_version",
        "rubric_hash", "policy_version", "deterministic_version", "review_required", "created_at",
    ),
    "submission_grade_revisions": (
        "id", "submission_id", "ai_job_id", "ai_result_id", "revision_hash", "revision_no", "status",
        "score", "feedback_md", "quality_audit_json", "provenance_json", "created_at", "activated_at",
        "superseded_at",
    ),
}


def _add_submission_columns(conn: Any, engine: str) -> None:
    columns = {
        "grading_revision_hash": "TEXT",
        "active_grade_revision_id": "BIGINT" if engine == "postgres" else "INTEGER",
        "grading_job_id": "BIGINT" if engine == "postgres" else "INTEGER",
    }
    for name, definition in columns.items():
        try:
            if engine == "postgres":
                conn.execute(f"ALTER TABLE submissions ADD COLUMN IF NOT EXISTS {name} {definition}")
            else:
                conn.execute(f"ALTER TABLE submissions ADD COLUMN {name} {definition}")
        except sqlite3.OperationalError:
            pass


def ensure_ai_job_schema(conn: Any, *, engine: str | None = None) -> None:
    """Create the durable AI job ledger for SQLite and PostgreSQL.

    Payloads contain references and hashes only; uploaded file bytes remain in
    the existing protected storage tree. Long provider calls never run while a
    schema or claim transaction is open.
    """

    global _SCHEMA_READY_ENGINES
    db_engine = (engine or get_configured_db_engine()).strip().lower()
    if db_engine not in {"sqlite", "postgres"}:
        raise ValueError(f"Unsupported AI job database engine: {db_engine!r}")
    if db_engine in _SCHEMA_READY_ENGINES:
        return

    id_column = (
        "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
        if db_engine == "postgres"
        else "INTEGER PRIMARY KEY AUTOINCREMENT"
    )
    foreign_id = "BIGINT" if db_engine == "postgres" else "INTEGER"

    conn.execute(
        f"""
        CREATE TABLE IF NOT EXISTS ai_jobs (
            id {id_column},
            task_type TEXT NOT NULL,
            priority INTEGER NOT NULL DEFAULT 100,
            status TEXT NOT NULL DEFAULT 'queued',
            dedupe_key TEXT NOT NULL UNIQUE,
            payload_json TEXT NOT NULL DEFAULT '{{}}',
            payload_hash TEXT NOT NULL DEFAULT '',
            input_schema_version TEXT NOT NULL DEFAULT 'v1',
            policy_version TEXT NOT NULL DEFAULT '',
            scope_type TEXT NOT NULL DEFAULT '',
            scope_id TEXT NOT NULL DEFAULT '',
            owner_role TEXT NOT NULL DEFAULT '',
            owner_user_pk INTEGER,
            source_ref TEXT NOT NULL DEFAULT '',
            attempt_count INTEGER NOT NULL DEFAULT 0,
            max_attempts INTEGER NOT NULL DEFAULT 8,
            delivery_attempt_count INTEGER NOT NULL DEFAULT 0,
            available_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            locked_at TEXT,
            locked_by TEXT NOT NULL DEFAULT '',
            lease_token TEXT NOT NULL DEFAULT '',
            lease_expires_at TEXT,
            heartbeat_at TEXT,
            capacity_reserved_until TEXT,
            result_id {foreign_id},
            review_required INTEGER NOT NULL DEFAULT 0,
            last_error_code TEXT NOT NULL DEFAULT '',
            last_error TEXT NOT NULL DEFAULT '',
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            started_at TEXT,
            finished_at TEXT
        )
        """
    )
    conn.execute(
        f"""
        CREATE TABLE IF NOT EXISTS ai_job_attempts (
            id {id_column},
            job_id {foreign_id} NOT NULL,
            attempt_no INTEGER NOT NULL,
            stage TEXT NOT NULL DEFAULT 'execute',
            status TEXT NOT NULL DEFAULT 'running',
            provider TEXT NOT NULL DEFAULT '',
            model TEXT NOT NULL DEFAULT '',
            prompt_tokens INTEGER NOT NULL DEFAULT 0,
            completion_tokens INTEGER NOT NULL DEFAULT 0,
            estimated_cost_cny REAL NOT NULL DEFAULT 0,
            error_code TEXT NOT NULL DEFAULT '',
            error_message TEXT NOT NULL DEFAULT '',
            metadata_json TEXT NOT NULL DEFAULT '{{}}',
            started_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            finished_at TEXT,
            UNIQUE (job_id, attempt_no, stage),
            FOREIGN KEY (job_id) REFERENCES ai_jobs (id) ON DELETE CASCADE
        )
        """
    )
    conn.execute(
        f"""
        CREATE TABLE IF NOT EXISTS ai_job_results (
            id {id_column},
            job_id {foreign_id} NOT NULL,
            result_hash TEXT NOT NULL,
            result_json TEXT NOT NULL DEFAULT '{{}}',
            status TEXT NOT NULL DEFAULT 'candidate',
            provider TEXT NOT NULL DEFAULT '',
            model TEXT NOT NULL DEFAULT '',
            prompt_version TEXT NOT NULL DEFAULT '',
            rubric_hash TEXT NOT NULL DEFAULT '',
            policy_version TEXT NOT NULL DEFAULT '',
            deterministic_version TEXT NOT NULL DEFAULT '',
            confidence REAL,
            review_required INTEGER NOT NULL DEFAULT 0,
            quality_audit_json TEXT NOT NULL DEFAULT '{{}}',
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            UNIQUE (job_id, result_hash),
            FOREIGN KEY (job_id) REFERENCES ai_jobs (id) ON DELETE CASCADE
        )
        """
    )
    conn.execute(
        f"""
        CREATE TABLE IF NOT EXISTS submission_grade_revisions (
            id {id_column},
            submission_id {foreign_id} NOT NULL,
            ai_job_id {foreign_id},
            ai_result_id {foreign_id},
            revision_hash TEXT NOT NULL,
            revision_no INTEGER NOT NULL DEFAULT 1,
            status TEXT NOT NULL DEFAULT 'candidate',
            score REAL,
            feedback_md TEXT NOT NULL DEFAULT '',
            quality_audit_json TEXT NOT NULL DEFAULT '{{}}',
            provenance_json TEXT NOT NULL DEFAULT '{{}}',
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            activated_at TEXT,
            superseded_at TEXT,
            UNIQUE (submission_id, revision_hash),
            FOREIGN KEY (submission_id) REFERENCES submissions (id) ON DELETE CASCADE,
            FOREIGN KEY (ai_job_id) REFERENCES ai_jobs (id) ON DELETE SET NULL,
            FOREIGN KEY (ai_result_id) REFERENCES ai_job_results (id) ON DELETE SET NULL
        )
        """
    )

    # Backwards-compatible capacity hold for cancelled/timed-out upstream work.
    # Such a hold is independent of the job lease and may outlive a terminal job.
    if db_engine == "postgres":
        conn.execute("ALTER TABLE ai_jobs ADD COLUMN IF NOT EXISTS capacity_reserved_until TEXT")
    elif "capacity_reserved_until" not in {row[1] for row in conn.execute("PRAGMA table_info(ai_jobs)")}:
        conn.execute("ALTER TABLE ai_jobs ADD COLUMN capacity_reserved_until TEXT")

    statements = (
        "CREATE INDEX IF NOT EXISTS idx_ai_jobs_owner_served ON ai_jobs (owner_role, owner_user_pk, started_at)",
        "CREATE INDEX IF NOT EXISTS idx_ai_jobs_type_status_created ON ai_jobs (task_type, status, created_at, id)",
        "CREATE INDEX IF NOT EXISTS idx_ai_jobs_scope_served ON ai_jobs (scope_type, scope_id, started_at) WHERE owner_user_pk IS NULL",
        "CREATE INDEX IF NOT EXISTS idx_ai_jobs_capacity_hold ON ai_jobs (task_type, capacity_reserved_until) WHERE capacity_reserved_until IS NOT NULL",
        "CREATE INDEX IF NOT EXISTS idx_ai_jobs_due ON ai_jobs (status, available_at, priority, id)",
        "CREATE INDEX IF NOT EXISTS idx_ai_jobs_lease ON ai_jobs (status, lease_expires_at)",
        "CREATE INDEX IF NOT EXISTS idx_ai_jobs_scope ON ai_jobs (scope_type, scope_id, status, created_at)",
        "CREATE INDEX IF NOT EXISTS idx_ai_jobs_source ON ai_jobs (source_ref, task_type, created_at)",
        "CREATE INDEX IF NOT EXISTS idx_ai_job_attempts_job ON ai_job_attempts (job_id, attempt_no, stage)",
        "CREATE INDEX IF NOT EXISTS idx_ai_job_results_job ON ai_job_results (job_id, created_at)",
        "CREATE INDEX IF NOT EXISTS idx_grade_revisions_submission ON submission_grade_revisions (submission_id, created_at)",
        "CREATE UNIQUE INDEX IF NOT EXISTS idx_grade_revisions_active ON submission_grade_revisions (submission_id) WHERE status = 'active'",
    )
    for statement in statements:
        conn.execute(statement)

    _add_submission_columns(conn, db_engine)
    _SCHEMA_READY_ENGINES.add(db_engine)


def reset_ai_job_schema_guard_for_tests() -> None:
    _SCHEMA_READY_ENGINES.clear()
