"""Schema for the 校园公文通 (official-document) teacher integration.

Teachers connect their unified-auth account; the platform logs into the school
公文通 (``doc.gxufl.com``) via OAuth2 + captcha and syncs their inbox documents
into ``gongwen_documents`` for local search, download and (later) reminders.

The DDL is engine-aware and idempotent (``CREATE TABLE IF NOT EXISTS`` on both
SQLite and PostgreSQL) so it can be ensured lazily at runtime without touching
the central PostgreSQL migration — mirrors ``schema_scheduler.ensure_scheduler_schema``.
Timestamps are stored as ISO-8601 / source TEXT to match the rest of the codebase.
"""

from __future__ import annotations

from typing import Any

from .connection import get_configured_db_engine

# Per-process guard so hot paths don't re-issue DDL once the tables exist.
_SCHEMA_READY = False


def ensure_gongwen_schema(conn: Any) -> None:
    """Create the 公文 integration tables if absent (sqlite + postgres)."""
    global _SCHEMA_READY
    if _SCHEMA_READY:
        return
    engine = get_configured_db_engine()
    id_column = (
        "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
        if engine == "postgres"
        else "id INTEGER PRIMARY KEY AUTOINCREMENT"
    )

    # --- Saved teacher credential (one row per teacher per system+auth) ---
    conn.execute(
        f"""
        CREATE TABLE IF NOT EXISTS teacher_gongwen_credentials (
            {id_column},
            teacher_id INTEGER NOT NULL,
            system_code TEXT NOT NULL,
            system_name TEXT NOT NULL,
            adapter_key TEXT NOT NULL,
            auth_method TEXT NOT NULL DEFAULT 'sso_captcha',
            base_url TEXT NOT NULL DEFAULT '',
            api_base_url TEXT NOT NULL DEFAULT '',
            sso_base_url TEXT NOT NULL DEFAULT '',
            login_url TEXT NOT NULL DEFAULT '',
            username TEXT NOT NULL,
            password_encrypted TEXT NOT NULL,
            display_name TEXT NOT NULL DEFAULT '',
            enabled INTEGER NOT NULL DEFAULT 1,
            last_status TEXT NOT NULL DEFAULT 'unchecked',
            last_status_at TEXT,
            last_error TEXT NOT NULL DEFAULT '',
            last_verified_at TEXT,
            access_method_json TEXT NOT NULL DEFAULT '{{}}',
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
        )
        """
    )
    conn.execute(
        "CREATE UNIQUE INDEX IF NOT EXISTS idx_gongwen_credentials_unique_auth "
        "ON teacher_gongwen_credentials (teacher_id, system_code, auth_method)"
    )
    conn.execute(
        "CREATE INDEX IF NOT EXISTS idx_gongwen_credentials_teacher "
        "ON teacher_gongwen_credentials (teacher_id, enabled, updated_at)"
    )

    # --- Synced inbox documents ---
    conn.execute(
        f"""
        CREATE TABLE IF NOT EXISTS gongwen_documents (
            {id_column},
            teacher_id INTEGER NOT NULL,
            credential_id INTEGER,
            system_code TEXT NOT NULL DEFAULT 'gxufl',
            remote_id TEXT NOT NULL,
            sn TEXT NOT NULL DEFAULT '',
            title TEXT NOT NULL DEFAULT '',
            subhead TEXT NOT NULL DEFAULT '',
            author TEXT NOT NULL DEFAULT '',
            sender_name TEXT NOT NULL DEFAULT '',
            category_id TEXT NOT NULL DEFAULT '',
            category_name TEXT NOT NULL DEFAULT '',
            summary TEXT NOT NULL DEFAULT '',
            content_html TEXT NOT NULL DEFAULT '',
            content_text TEXT NOT NULL DEFAULT '',
            keywords TEXT NOT NULL DEFAULT '',
            tags TEXT NOT NULL DEFAULT '',
            source TEXT NOT NULL DEFAULT '',
            link TEXT NOT NULL DEFAULT '',
            source_link TEXT NOT NULL DEFAULT '',
            cover_url TEXT NOT NULL DEFAULT '',
            file_url TEXT NOT NULL DEFAULT '',
            attachment_url TEXT NOT NULL DEFAULT '',
            local_file_path TEXT NOT NULL DEFAULT '',
            local_attachment_path TEXT NOT NULL DEFAULT '',
            file_download_status TEXT NOT NULL DEFAULT 'idle',
            file_download_error TEXT NOT NULL DEFAULT '',
            is_read INTEGER NOT NULL DEFAULT 0,
            is_fav INTEGER NOT NULL DEFAULT 0,
            is_need_feedback INTEGER NOT NULL DEFAULT 0,
            publish_time TEXT NOT NULL DEFAULT '',
            remote_created_at TEXT NOT NULL DEFAULT '',
            remote_updated_at TEXT NOT NULL DEFAULT '',
            reminder_status TEXT NOT NULL DEFAULT 'none',
            raw_json TEXT NOT NULL DEFAULT '{{}}',
            synced_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
        )
        """
    )
    conn.execute(
        "CREATE UNIQUE INDEX IF NOT EXISTS idx_gongwen_documents_unique_remote "
        "ON gongwen_documents (teacher_id, system_code, remote_id)"
    )
    conn.execute(
        "CREATE INDEX IF NOT EXISTS idx_gongwen_documents_teacher_time "
        "ON gongwen_documents (teacher_id, publish_time)"
    )
    conn.execute(
        "CREATE INDEX IF NOT EXISTS idx_gongwen_documents_teacher_category "
        "ON gongwen_documents (teacher_id, category_name)"
    )
    conn.execute(
        "CREATE INDEX IF NOT EXISTS idx_gongwen_documents_teacher_read "
        "ON gongwen_documents (teacher_id, is_read, publish_time)"
    )
    conn.execute(
        "CREATE INDEX IF NOT EXISTS idx_gongwen_documents_reminder "
        "ON gongwen_documents (teacher_id, reminder_status)"
    )
    _SCHEMA_READY = True
