"""Schema for nationally published holiday / make-up workday records (全国法定节假日与调休).

One row per (date, source). Holidays (``kind='holiday'``) and make-up workdays
(``kind='workday'``) are fetched automatically from the public *holiday-cn*
dataset (mirrors the State Council notices) by a weekly scheduled task and
overlaid onto the curated ``HOLIDAY_DATA`` when building holiday lookups. A
make-up workday also records *which* weekday timetable is followed
(``makeup_for_date`` / ``makeup_for_weekday``); when the notice does not say,
the mapping is inferred (``inferred=1``) and the calendar labels it as such.

Engine-aware, idempotent DDL (``CREATE TABLE IF NOT EXISTS`` on both SQLite and
PostgreSQL), ensured lazily at runtime like ``schema_schedule_editor``.
"""

from __future__ import annotations

from typing import Any

from .connection import get_configured_db_engine

_SCHEMA_READY = False

HOLIDAY_KINDS = ("holiday", "workday")


def ensure_national_holiday_schema(conn: Any) -> None:
    """Create the national holiday table on either engine (idempotent)."""
    global _SCHEMA_READY
    if _SCHEMA_READY:
        return
    engine = get_configured_db_engine()
    id_column = (
        "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
        if engine == "postgres"
        else "id INTEGER PRIMARY KEY AUTOINCREMENT"
    )
    conn.execute(
        f"""
        CREATE TABLE IF NOT EXISTS national_holiday_days (
            {id_column},
            year INTEGER NOT NULL,
            date TEXT NOT NULL,
            kind TEXT NOT NULL DEFAULT 'holiday',
            name TEXT NOT NULL DEFAULT '',
            label TEXT NOT NULL DEFAULT '',
            makeup_for_date TEXT NOT NULL DEFAULT '',
            makeup_for_weekday TEXT NOT NULL DEFAULT '',
            inferred INTEGER NOT NULL DEFAULT 0,
            source TEXT NOT NULL DEFAULT 'holiday-cn',
            source_url TEXT NOT NULL DEFAULT '',
            fetched_at TEXT NOT NULL DEFAULT '',
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            UNIQUE (date, source)
        )
        """
    )
    conn.execute(
        "CREATE INDEX IF NOT EXISTS idx_national_holiday_days_year ON national_holiday_days (year, kind)"
    )
    _SCHEMA_READY = True


def reset_schema_ready_for_tests() -> None:
    """Allow unit tests that rebuild in-memory databases to re-run the DDL."""
    global _SCHEMA_READY
    _SCHEMA_READY = False
