"""Schema for the random study-group scheme system.

A *group scheme* (``group_schemes``) is a teacher-defined plan for randomly
splitting a class into study groups. The teacher sets per-group min/max member
counts, an optional total group count (otherwise derived from the class size),
and an optional deadline. Starting a scheme pre-creates the empty groups
(rows in ``study_groups`` linked via ``scheme_id``); students then self-assign
randomly into any non-full group of the scheme.

The DDL is engine-aware and idempotent (``CREATE TABLE IF NOT EXISTS`` on both
SQLite and PostgreSQL) so it can be ensured lazily at runtime without touching
the central SQLite->PostgreSQL migration — mirroring ``schema_scheduler`` and
``schema_gongwen``. Timestamps are ISO-8601 TEXT, consistent with the codebase.
"""

from __future__ import annotations

from typing import Any

from .connection import get_configured_db_engine

_SCHEMA_READY = False


def _add_column(conn: Any, table: str, column: str, definition: str, *, engine: str) -> None:
    """Idempotently add a column to an existing table on either engine."""
    if engine == "postgres":
        conn.execute(f"ALTER TABLE {table} ADD COLUMN IF NOT EXISTS {column} {definition}")
        return
    try:
        conn.execute(f"ALTER TABLE {table} ADD COLUMN {column} {definition}")
    except Exception:
        # SQLite has no ADD COLUMN IF NOT EXISTS; a duplicate column raises
        # OperationalError, which is the idempotent no-op we want.
        pass


def ensure_study_group_scheme_schema(conn: Any) -> None:
    """Create the group-scheme table + extend study_groups (sqlite + postgres)."""
    global _SCHEMA_READY
    if _SCHEMA_READY:
        return
    engine = get_configured_db_engine()
    id_column = (
        "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
        if engine == "postgres"
        else "id INTEGER PRIMARY KEY AUTOINCREMENT"
    )

    conn.execute(
        f"""
        CREATE TABLE IF NOT EXISTS group_schemes (
            {id_column},
            class_offering_id INTEGER NOT NULL,
            name TEXT NOT NULL DEFAULT '随机分组',
            description TEXT NOT NULL DEFAULT '',
            min_members INTEGER NOT NULL DEFAULT 2,
            max_members INTEGER NOT NULL DEFAULT 6,
            group_count INTEGER NOT NULL DEFAULT 0,
            status TEXT NOT NULL DEFAULT 'active',
            expires_at TEXT,
            created_by_teacher_id INTEGER NOT NULL,
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            archived_at TEXT,
            metadata_json TEXT NOT NULL DEFAULT '{{}}'
        )
        """
    )
    conn.execute(
        "CREATE INDEX IF NOT EXISTS idx_group_schemes_offering "
        "ON group_schemes (class_offering_id, status, created_at DESC, id DESC)"
    )

    # Extend study_groups so an existing group can belong to a scheme and carry
    # a shared goal + progress. These are nullable / defaulted so legacy
    # assignment-based groups are unaffected.
    _add_column(conn, "study_groups", "scheme_id", "INTEGER", engine=engine)
    _add_column(conn, "study_groups", "group_index", "INTEGER NOT NULL DEFAULT 0", engine=engine)
    _add_column(conn, "study_groups", "goal_text", "TEXT NOT NULL DEFAULT ''", engine=engine)
    _add_column(conn, "study_groups", "progress_percent", "INTEGER NOT NULL DEFAULT 0", engine=engine)
    conn.execute(
        "CREATE INDEX IF NOT EXISTS idx_study_groups_scheme "
        "ON study_groups (scheme_id, group_index, id)"
    )

    _SCHEMA_READY = True
