"""Schema for teacher timetable edit drafts (课表编辑模式 · 调课草稿).

One row per lesson occurrence a teacher wants to move (or re-room) inside a
term. The row keeps the original slot, the proposed slot and, once pushed,
the identifiers the 教务系统 (正方) assigned to the *saved draft* detail. The
platform never submits an application on the teacher's behalf: the teacher
signs in to 教务, reviews the saved drafts and presses 提交 there.

Engine-aware, idempotent DDL (``CREATE TABLE IF NOT EXISTS`` on both SQLite and
PostgreSQL) so it can be ensured lazily at runtime — the same pattern as
``schema_polls`` / ``schema_smart_schedule``. Timestamps are ISO-8601 TEXT.
"""

from __future__ import annotations

from typing import Any

from .connection import get_configured_db_engine
from .schema_schedule_availability import ensure_schedule_availability_schema

_SCHEMA_READY = False

DRAFT_STATUSES = ("draft", "pushed", "conflict", "failed")


def ensure_schedule_editor_schema(conn: Any) -> None:
    """Create the timetable edit-draft table on either engine (idempotent)."""
    global _SCHEMA_READY
    if _SCHEMA_READY:
        return
    engine = get_configured_db_engine()
    id_column = (
        "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
        if engine == "postgres"
        else "id INTEGER PRIMARY KEY AUTOINCREMENT"
    )
    conn.execute(
        f"""
        CREATE TABLE IF NOT EXISTS teacher_schedule_edit_drafts (
            {id_column},
            teacher_id INTEGER NOT NULL,
            school_code TEXT NOT NULL DEFAULT 'gxufl',
            academic_year TEXT NOT NULL DEFAULT '',
            academic_term TEXT NOT NULL DEFAULT '',
            event_key TEXT NOT NULL DEFAULT '',
            teaching_class_id TEXT NOT NULL DEFAULT '',
            teaching_class_name TEXT NOT NULL DEFAULT '',
            course_name TEXT NOT NULL DEFAULT '',
            class_label TEXT NOT NULL DEFAULT '',
            change_kind TEXT NOT NULL DEFAULT 'move',
            original_json TEXT NOT NULL DEFAULT '{{}}',
            proposed_json TEXT NOT NULL DEFAULT '{{}}',
            reason TEXT NOT NULL DEFAULT '',
            note TEXT NOT NULL DEFAULT '',
            status TEXT NOT NULL DEFAULT 'draft',
            remote_ttk_id TEXT NOT NULL DEFAULT '',
            remote_detail_id TEXT NOT NULL DEFAULT '',
            remote_label TEXT NOT NULL DEFAULT '',
            remote_message TEXT NOT NULL DEFAULT '',
            remote_conflict_json TEXT NOT NULL DEFAULT '{{}}',
            pushed_at TEXT NOT NULL DEFAULT '',
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            UNIQUE (teacher_id, academic_year, academic_term, event_key)
        )
        """
    )
    conn.execute(
        "CREATE INDEX IF NOT EXISTS idx_schedule_edit_drafts_term "
        "ON teacher_schedule_edit_drafts (teacher_id, academic_year, academic_term, status)"
    )
    _ensure_extension_columns(conn, engine)
    # 可调时段缓存表与草稿同生命周期，在同一连接上一并建好。
    ensure_schedule_availability_schema(conn)
    _SCHEMA_READY = True


def _ensure_extension_columns(conn: Any, engine: str) -> None:
    """Columns added after the first release (可调时段 verdict per draft)."""
    columns = (
        ("room_status", "TEXT NOT NULL DEFAULT 'unknown'"),   # free | busy | unknown for the proposed slot
        ("availability_json", "TEXT NOT NULL DEFAULT '{}'"),   # verdict snapshot at save time
    )
    if engine == "postgres":
        for name, ddl_type in columns:
            conn.execute(f"ALTER TABLE teacher_schedule_edit_drafts ADD COLUMN IF NOT EXISTS {name} {ddl_type}")
        return
    existing = {str(row[1]) for row in conn.execute("PRAGMA table_info(teacher_schedule_edit_drafts)").fetchall()}
    for name, ddl_type in columns:
        if name not in existing:
            conn.execute(f"ALTER TABLE teacher_schedule_edit_drafts ADD COLUMN {name} {ddl_type}")


def reset_schema_ready_for_tests() -> None:
    """Allow unit tests that rebuild in-memory databases to re-run the DDL."""
    global _SCHEMA_READY
    _SCHEMA_READY = False
