"""Schema for teacher whiteboards attached to course materials (材料白板).

A *material whiteboard* is a free-form drawing board a teacher opens on top of
a course material (``course_materials``). Each board is identified by a
client-generated ``board_key`` and belongs to one owner (``owner_role`` +
``owner_user_pk``) for one material, so the same key can safely exist for
different teachers or materials.

Element data is stored as JSON (``elements_json``) with an optimistic-lock
``version`` counter: a save whose ``base_version`` no longer matches the row
is rejected with a conflict instead of silently overwriting the other tab.
``visibility`` / ``share_token`` are reserved for the future share / collab
mode and are not used yet.

The DDL is engine-aware and idempotent (``CREATE TABLE IF NOT EXISTS`` on both
SQLite and PostgreSQL) so it can be ensured lazily at runtime without touching
the central SQLite->PostgreSQL migration — mirroring ``schema_polls``.
Timestamps are ISO-8601 TEXT, consistent with the rest of the codebase.
"""

from __future__ import annotations

from typing import Any

from .connection import get_configured_db_engine

_SCHEMA_READY = False


def ensure_material_whiteboard_schema(conn: Any) -> None:
    """Create the material whiteboard table on either engine (idempotent)."""
    global _SCHEMA_READY
    if _SCHEMA_READY:
        return
    engine = get_configured_db_engine()
    id_column = (
        "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
        if engine == "postgres"
        else "id INTEGER PRIMARY KEY AUTOINCREMENT"
    )

    conn.execute(
        f"""
        CREATE TABLE IF NOT EXISTS material_whiteboards (
            {id_column},
            owner_role TEXT NOT NULL DEFAULT 'teacher',
            owner_user_pk INTEGER NOT NULL,
            material_id INTEGER NOT NULL,
            board_key TEXT NOT NULL,
            name TEXT NOT NULL DEFAULT '',
            viewport_json TEXT NOT NULL DEFAULT '{{}}',
            elements_json TEXT NOT NULL DEFAULT '[]',
            element_count INTEGER NOT NULL DEFAULT 0,
            schema_version INTEGER NOT NULL DEFAULT 2,
            version INTEGER NOT NULL DEFAULT 1,
            visibility TEXT NOT NULL DEFAULT 'private',
            share_token TEXT,
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            deleted_at TEXT,
            UNIQUE (owner_role, owner_user_pk, material_id, board_key)
        )
        """
    )
    conn.execute(
        "CREATE INDEX IF NOT EXISTS idx_material_whiteboards_owner "
        "ON material_whiteboards (owner_role, owner_user_pk, material_id, updated_at DESC)"
    )

    _SCHEMA_READY = True
