"""Schema for the login "人生一言" tip system (游戏加载屏式登录提示).

A *life tip* is one game-loading-screen style sentence shown right after login
(学业规则 / 毕业条件 / 实习求职 / 人生大实话 …). Tips live in a single table
with a three-level scope pool:

- ``scope='global'``      — shared by every school (the seed pack lives here);
- ``scope='school'``      — one school (``school_code``), e.g. 校级奖学金规定;
- ``scope='department'``  — one department of one school (``school_code`` +
  ``department``), e.g. 系部毕业设计要求.

A student's effective pool = global ∪ school(本校) ∪ department(本校+本系),
so every student in the same department sees the same pool while different
departments / schools naturally overlap through the wider scopes.

``content_hash`` is the SHA-256 of the normalised tip text and dedupes both
the idempotent seed pass and AI-generated batches. ``status`` is
``active`` / ``draft`` / ``retired`` — only ``active`` tips are served.

The DDL is engine-aware and idempotent so it can be ensured lazily at runtime
without touching the central migration — mirroring ``schema_polls``.
Timestamps are ISO-8601 TEXT, booleans INTEGER 0/1, per codebase convention.
"""

from __future__ import annotations

from typing import Any

from .connection import get_configured_db_engine

_SCHEMA_READY = False


def ensure_life_tip_schema(conn: Any) -> None:
    """Create the life tip table on either engine (idempotent)."""
    global _SCHEMA_READY
    if _SCHEMA_READY:
        return
    engine = get_configured_db_engine()
    id_column = (
        "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
        if engine == "postgres"
        else "id INTEGER PRIMARY KEY AUTOINCREMENT"
    )

    # source_kind: 'seed' (shipped fixtures) | 'ai_gongwen' (scheduler-generated
    # from official documents) | 'manual' (hand-entered). source_ref keeps the
    # provenance line shown to students (公文标题/文号) when present.
    conn.execute(
        f"""
        CREATE TABLE IF NOT EXISTS life_tips (
            {id_column},
            scope TEXT NOT NULL DEFAULT 'global',
            school_code TEXT NOT NULL DEFAULT '',
            department TEXT NOT NULL DEFAULT '',
            category TEXT NOT NULL DEFAULT '人生大实话',
            audience TEXT NOT NULL DEFAULT 'student',
            tip_text TEXT NOT NULL,
            source_kind TEXT NOT NULL DEFAULT 'seed',
            source_ref TEXT NOT NULL DEFAULT '',
            status TEXT NOT NULL DEFAULT 'active',
            weight INTEGER NOT NULL DEFAULT 1,
            content_hash TEXT NOT NULL DEFAULT '',
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            UNIQUE (content_hash)
        )
        """
    )
    # Pool resolution query shape: WHERE status='active' AND audience IN (...)
    # AND (scope='global' OR (scope='school' AND school_code=?) OR
    # (scope='department' AND school_code=? AND department=?)).
    conn.execute(
        "CREATE INDEX IF NOT EXISTS idx_life_tips_scope_lookup "
        "ON life_tips (status, scope, school_code, department, audience)"
    )

    # 公文挖掘台账：记录哪些 gongwen_documents 已经跑过提示语提取
    # （无论产出几条），生成任务据此增量推进、绝不重复喂给 AI。
    conn.execute(
        """
        CREATE TABLE IF NOT EXISTS life_tip_source_ledger (
            doc_id INTEGER PRIMARY KEY,
            tips_created INTEGER NOT NULL DEFAULT 0,
            processed_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
        )
        """
    )

    _SCHEMA_READY = True
