"""Schema for the standalone poll / vote system (投票活动).

A *poll* (``polls``) is a vote activity created by a teacher or a student. It is
NOT tied to a single class: a poll's data is shared across every class it is
assigned to (``poll_assignments``). A teacher creating a poll in the management
center can distribute one poll to several classes and all members share a single
result set; a poll created inside a classroom is auto-assigned to that one class
only. Students can also create their own polls and pick participants
(``poll_participants``), with PM-blacklisted peers excluded at the service layer.

Polls have three states: ``draft`` / ``active`` / ``closed``. Only ``active``
polls are open for voting; ``draft`` polls are visible only to the creator.

The DDL is engine-aware and idempotent (``CREATE TABLE IF NOT EXISTS`` on both
SQLite and PostgreSQL) so it can be ensured lazily at runtime without touching
the central SQLite->PostgreSQL migration — mirroring ``schema_study_group_scheme``
and ``schema_scheduler``. Timestamps are ISO-8601 TEXT and booleans are stored
as INTEGER 0/1, consistent with the rest of the codebase.
"""

from __future__ import annotations

from typing import Any

from .connection import get_configured_db_engine

_SCHEMA_READY = False


def ensure_poll_schema(conn: Any) -> None:
    """Create the poll tables on either engine (idempotent)."""
    global _SCHEMA_READY
    if _SCHEMA_READY:
        return
    engine = get_configured_db_engine()
    id_column = (
        "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
        if engine == "postgres"
        else "id INTEGER PRIMARY KEY AUTOINCREMENT"
    )

    # The poll activity itself. owner_role/owner_user_pk identify the creator
    # (teacher or student). audience_scope = 'class' means every member of the
    # assigned classes can vote; 'custom' means only the explicitly listed
    # participants (used by student-created polls).
    conn.execute(
        f"""
        CREATE TABLE IF NOT EXISTS polls (
            {id_column},
            owner_role TEXT NOT NULL DEFAULT 'teacher',
            owner_user_pk INTEGER NOT NULL,
            owner_name TEXT NOT NULL DEFAULT '',
            title TEXT NOT NULL DEFAULT '投票',
            description TEXT NOT NULL DEFAULT '',
            vote_type TEXT NOT NULL DEFAULT 'single',
            status TEXT NOT NULL DEFAULT 'draft',
            origin TEXT NOT NULL DEFAULT 'management',
            origin_class_offering_id INTEGER,
            audience_scope TEXT NOT NULL DEFAULT 'class',
            deadline_at TEXT,
            allow_change INTEGER NOT NULL DEFAULT 0,
            max_changes INTEGER NOT NULL DEFAULT 0,
            result_visibility TEXT NOT NULL DEFAULT 'after_vote',
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            closed_at TEXT,
            settings_json TEXT NOT NULL DEFAULT '{{}}'
        )
        """
    )
    conn.execute(
        "CREATE INDEX IF NOT EXISTS idx_polls_owner "
        "ON polls (owner_role, owner_user_pk, status, updated_at DESC, id DESC)"
    )

    conn.execute(
        f"""
        CREATE TABLE IF NOT EXISTS poll_options (
            {id_column},
            poll_id INTEGER NOT NULL,
            label TEXT NOT NULL DEFAULT '',
            sort_order INTEGER NOT NULL DEFAULT 0,
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
        )
        """
    )
    conn.execute(
        "CREATE INDEX IF NOT EXISTS idx_poll_options_poll "
        "ON poll_options (poll_id, sort_order, id)"
    )

    # Which class offerings a poll is distributed to. The shared-data guarantee:
    # one poll row backs every assigned class, so cross-class distribution never
    # forks the vote tallies.
    conn.execute(
        f"""
        CREATE TABLE IF NOT EXISTS poll_assignments (
            {id_column},
            poll_id INTEGER NOT NULL,
            class_offering_id INTEGER NOT NULL,
            assigned_by_role TEXT NOT NULL DEFAULT 'teacher',
            assigned_by_user_pk INTEGER NOT NULL DEFAULT 0,
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            UNIQUE (poll_id, class_offering_id)
        )
        """
    )
    conn.execute(
        "CREATE INDEX IF NOT EXISTS idx_poll_assignments_class "
        "ON poll_assignments (class_offering_id, poll_id)"
    )
    conn.execute(
        "CREATE INDEX IF NOT EXISTS idx_poll_assignments_poll "
        "ON poll_assignments (poll_id)"
    )

    # Explicit participant list for audience_scope = 'custom'.
    conn.execute(
        f"""
        CREATE TABLE IF NOT EXISTS poll_participants (
            {id_column},
            poll_id INTEGER NOT NULL,
            student_id INTEGER NOT NULL,
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            UNIQUE (poll_id, student_id)
        )
        """
    )
    conn.execute(
        "CREATE INDEX IF NOT EXISTS idx_poll_participants_poll "
        "ON poll_participants (poll_id, student_id)"
    )

    # A voter's participation record — one per (poll, student). change_count
    # tracks how many times the ballot was edited (capped by polls.max_changes
    # when allow_change is on).
    conn.execute(
        f"""
        CREATE TABLE IF NOT EXISTS poll_ballots (
            {id_column},
            poll_id INTEGER NOT NULL,
            voter_id INTEGER NOT NULL,
            change_count INTEGER NOT NULL DEFAULT 0,
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            UNIQUE (poll_id, voter_id)
        )
        """
    )
    conn.execute(
        "CREATE INDEX IF NOT EXISTS idx_poll_ballots_poll "
        "ON poll_ballots (poll_id, voter_id)"
    )

    # The actual selected options. Single-choice polls have one row per voter;
    # multiple-choice polls have one row per selected option.
    conn.execute(
        f"""
        CREATE TABLE IF NOT EXISTS poll_votes (
            {id_column},
            poll_id INTEGER NOT NULL,
            voter_id INTEGER NOT NULL,
            option_id INTEGER NOT NULL,
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
        )
        """
    )
    conn.execute(
        "CREATE INDEX IF NOT EXISTS idx_poll_votes_poll_option "
        "ON poll_votes (poll_id, option_id)"
    )
    conn.execute(
        "CREATE INDEX IF NOT EXISTS idx_poll_votes_poll_voter "
        "ON poll_votes (poll_id, voter_id)"
    )

    _purge_legacy_interaction_polls(conn)

    _SCHEMA_READY = True


def _purge_legacy_interaction_polls(conn: Any) -> None:
    """One-time cleanup: the poll feature moved out of the classroom interaction
    area into the standalone poll system. Drop any leftover ``kind='poll'`` rows
    (and their options/responses) from ``classroom_live_activities``. Idempotent
    and guarded — the table may not exist yet on a brand-new database."""
    statements = (
        "DELETE FROM classroom_live_responses WHERE activity_id IN "
        "(SELECT id FROM classroom_live_activities WHERE kind = 'poll')",
        "DELETE FROM classroom_live_options WHERE activity_id IN "
        "(SELECT id FROM classroom_live_activities WHERE kind = 'poll')",
        "DELETE FROM classroom_live_activities WHERE kind = 'poll'",
    )
    for statement in statements:
        try:
            conn.execute(statement)
        except Exception:
            # Table absent (fresh DB) or transient lock — cleanup is best-effort
            # and retried on the next startup.
            pass
