"""Privacy-minimal engagement events for the student career/resume workflow.

The table deliberately stores only a whitelisted, compact JSON context.  Resume
content, job-description text, contact details and other sensitive profile data
must never enter this event stream.  It is runtime-managed for both SQLite and
PostgreSQL, matching the career-path and resume schemas.
"""

from __future__ import annotations

from typing import Any

from .connection import get_configured_db_engine

_SCHEMA_READY = False


def ensure_career_engagement_schema(conn: Any) -> None:
    """Create the append-only student career engagement event table."""
    global _SCHEMA_READY
    if _SCHEMA_READY:
        return

    engine = get_configured_db_engine()
    id_column = (
        "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
        if engine == "postgres"
        else "id INTEGER PRIMARY KEY AUTOINCREMENT"
    )
    conn.execute(
        f"""
        CREATE TABLE IF NOT EXISTS student_career_events (
            {id_column},
            student_id INTEGER NOT NULL,
            surface TEXT NOT NULL,
            event_name TEXT NOT NULL,
            context_json TEXT NOT NULL DEFAULT '{{}}',
            client_event_id TEXT,
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
        )
        """
    )
    conn.execute(
        "CREATE INDEX IF NOT EXISTS idx_student_career_events_funnel "
        "ON student_career_events (event_name, created_at DESC)"
    )
    conn.execute(
        "CREATE INDEX IF NOT EXISTS idx_student_career_events_student "
        "ON student_career_events (student_id, created_at DESC)"
    )
    conn.execute(
        "CREATE UNIQUE INDEX IF NOT EXISTS uq_student_career_events_client "
        "ON student_career_events (student_id, client_event_id)"
    )
    _SCHEMA_READY = True
