"""Schema for the random study-group scheme system.

A *group scheme* (``group_schemes``) is a teacher-defined plan for randomly
splitting a class into study groups. The teacher sets per-group min/max member
counts, an optional total group count (otherwise derived from the class size),
and an optional deadline. Starting a scheme pre-creates the empty groups
(rows in ``study_groups`` linked via ``scheme_id``); students then self-assign
randomly into any non-full group of the scheme.

The DDL is engine-aware and idempotent (``CREATE TABLE IF NOT EXISTS`` on both
SQLite and PostgreSQL) so it can be ensured lazily at runtime without touching
the central SQLite->PostgreSQL migration — mirroring ``schema_scheduler`` and
``schema_gongwen``. Timestamps are ISO-8601 TEXT, consistent with the codebase.
"""

from __future__ import annotations

from typing import Any

from .connection import get_configured_db_engine

_SCHEMA_READY = False


def _add_column(conn: Any, table: str, column: str, definition: str, *, engine: str) -> None:
    """Idempotently add a column to an existing table on either engine."""
    if engine == "postgres":
        conn.execute(f"ALTER TABLE {table} ADD COLUMN IF NOT EXISTS {column} {definition}")
        return
    try:
        conn.execute(f"ALTER TABLE {table} ADD COLUMN {column} {definition}")
    except Exception:
        # SQLite has no ADD COLUMN IF NOT EXISTS; a duplicate column raises
        # OperationalError, which is the idempotent no-op we want.
        pass


def ensure_study_group_scheme_schema(conn: Any) -> None:
    """Create the group-scheme table + extend study_groups (sqlite + postgres)."""
    global _SCHEMA_READY
    if _SCHEMA_READY:
        return
    engine = get_configured_db_engine()
    id_column = (
        "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
        if engine == "postgres"
        else "id INTEGER PRIMARY KEY AUTOINCREMENT"
    )

    conn.execute(
        f"""
        CREATE TABLE IF NOT EXISTS group_schemes (
            {id_column},
            class_offering_id INTEGER NOT NULL,
            name TEXT NOT NULL DEFAULT '随机分组',
            description TEXT NOT NULL DEFAULT '',
            min_members INTEGER NOT NULL DEFAULT 2,
            max_members INTEGER NOT NULL DEFAULT 6,
            group_count INTEGER NOT NULL DEFAULT 0,
            status TEXT NOT NULL DEFAULT 'active',
            expires_at TEXT,
            created_by_teacher_id INTEGER NOT NULL,
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            archived_at TEXT,
            metadata_json TEXT NOT NULL DEFAULT '{{}}'
        )
        """
    )
    conn.execute(
        "CREATE INDEX IF NOT EXISTS idx_group_schemes_offering "
        "ON group_schemes (class_offering_id, status, created_at DESC, id DESC)"
    )

    # Extend study_groups so an existing group can belong to a scheme and carry
    # a shared goal + progress. These are nullable / defaulted so legacy
    # assignment-based groups are unaffected.
    _add_column(conn, "study_groups", "scheme_id", "INTEGER", engine=engine)
    _add_column(conn, "study_groups", "group_index", "INTEGER NOT NULL DEFAULT 0", engine=engine)
    _add_column(conn, "study_groups", "goal_text", "TEXT NOT NULL DEFAULT ''", engine=engine)
    _add_column(conn, "study_groups", "progress_percent", "INTEGER NOT NULL DEFAULT 0", engine=engine)
    conn.execute(
        "CREATE INDEX IF NOT EXISTS idx_study_groups_scheme "
        "ON study_groups (scheme_id, group_index, id)"
    )

    # In-group chat (组内对话). A lightweight REST + polling channel scoped to a
    # single study group — deliberately separate from the WebSocket classroom
    # discussion room so group chat needs no socket-room changes.
    conn.execute(
        f"""
        CREATE TABLE IF NOT EXISTS group_chat_messages (
            {id_column},
            group_id INTEGER NOT NULL,
            sender_role TEXT NOT NULL DEFAULT 'student',
            sender_user_pk INTEGER NOT NULL,
            sender_name TEXT NOT NULL DEFAULT '',
            content TEXT NOT NULL DEFAULT '',
            message_type TEXT NOT NULL DEFAULT 'text',
            attachments_json TEXT NOT NULL DEFAULT '[]',
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
        )
        """
    )
    # Backfill columns on databases created before chat attachments existed.
    _add_column(conn, "group_chat_messages", "message_type", "TEXT NOT NULL DEFAULT 'text'", engine=engine)
    _add_column(conn, "group_chat_messages", "attachments_json", "TEXT NOT NULL DEFAULT '[]'", engine=engine)
    _add_column(conn, "group_chat_messages", "recalled_at", "TEXT", engine=engine)
    conn.execute(
        "CREATE INDEX IF NOT EXISTS idx_group_chat_messages_group "
        "ON group_chat_messages (group_id, id)"
    )

    # Attachments (images + files + custom-emoji stickers) for in-group chat.
    conn.execute(
        f"""
        CREATE TABLE IF NOT EXISTS group_chat_attachments (
            {id_column},
            group_id INTEGER NOT NULL,
            uploaded_by_role TEXT NOT NULL DEFAULT 'student',
            uploaded_by_user_pk INTEGER NOT NULL,
            uploaded_by_name TEXT NOT NULL DEFAULT '',
            file_hash TEXT NOT NULL,
            original_filename TEXT NOT NULL DEFAULT '',
            mime_type TEXT NOT NULL DEFAULT 'application/octet-stream',
            file_size INTEGER NOT NULL DEFAULT 0,
            kind TEXT NOT NULL DEFAULT 'file',
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
        )
        """
    )
    conn.execute(
        "CREATE INDEX IF NOT EXISTS idx_group_chat_attachments_group "
        "ON group_chat_attachments (group_id, id)"
    )

    # Student-initiated group invitations (邀请进组). An invitee accepts (joins)
    # or declines; repeated declines from the same inviter trigger a permanent
    # invite block + PM blacklist (enforced in the service layer).
    conn.execute(
        f"""
        CREATE TABLE IF NOT EXISTS group_invitations (
            {id_column},
            group_id INTEGER NOT NULL,
            class_offering_id INTEGER NOT NULL,
            inviter_student_id INTEGER NOT NULL,
            invitee_student_id INTEGER NOT NULL,
            status TEXT NOT NULL DEFAULT 'pending',
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            responded_at TEXT
        )
        """
    )
    conn.execute(
        "CREATE INDEX IF NOT EXISTS idx_group_invitations_invitee "
        "ON group_invitations (invitee_student_id, status, created_at DESC)"
    )
    conn.execute(
        "CREATE INDEX IF NOT EXISTS idx_group_invitations_inviter "
        "ON group_invitations (inviter_student_id, created_at DESC)"
    )
    conn.execute(
        "CREATE INDEX IF NOT EXISTS idx_group_invitations_group "
        "ON group_invitations (group_id, status)"
    )

    # ------------------------------------------------------------------
    # Group-based assignment / exam completion.
    #
    # A teacher can mark an assignment (or exam) as "completed by group",
    # binding it to a specific group scheme. Each group member still submits
    # their own work and gets their own AI score, but at submit time they rate
    # every teammate's contribution on a 20-point scale. Once *all* members of a
    # group have submitted and been graded (and their peer ratings are in), each
    # member's final score is computed as:
    #
    #     final = round(work_score * 0.8 + peer_avg, 2)
    #
    # where ``peer_avg`` is the average of the 20-point ratings the member
    # received from teammates. Scores stay hidden ("等待小组成员完成") until the
    # whole group is finalized, after which every member sees only their own
    # blended "综合表现分" — never the individual ratings teammates gave them.
    # ------------------------------------------------------------------
    conn.execute(
        f"""
        CREATE TABLE IF NOT EXISTS assignment_group_bindings (
            {id_column},
            assignment_id TEXT NOT NULL,
            class_offering_id INTEGER NOT NULL,
            scheme_id INTEGER NOT NULL,
            status TEXT NOT NULL DEFAULT 'active',
            created_by_teacher_id INTEGER NOT NULL,
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            metadata_json TEXT NOT NULL DEFAULT '{{}}'
        )
        """
    )
    conn.execute(
        "CREATE UNIQUE INDEX IF NOT EXISTS idx_assignment_group_bindings_assignment "
        "ON assignment_group_bindings (assignment_id)"
    )
    conn.execute(
        "CREATE INDEX IF NOT EXISTS idx_assignment_group_bindings_scheme "
        "ON assignment_group_bindings (scheme_id, status)"
    )

    # Per-member finalization ledger for a group assignment. One row per
    # (assignment, student). ``revealed=0`` means the score is computed but
    # withheld until the whole group is done.
    conn.execute(
        f"""
        CREATE TABLE IF NOT EXISTS group_assignment_member_results (
            {id_column},
            assignment_id TEXT NOT NULL,
            class_offering_id INTEGER NOT NULL,
            group_id INTEGER NOT NULL,
            student_pk_id INTEGER NOT NULL,
            submission_id INTEGER,
            work_score REAL,
            peer_avg REAL,
            peer_review_count INTEGER NOT NULL DEFAULT 0,
            final_score REAL,
            revealed INTEGER NOT NULL DEFAULT 0,
            finalized_at TEXT,
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
        )
        """
    )
    conn.execute(
        "CREATE UNIQUE INDEX IF NOT EXISTS idx_group_assignment_member_results_unique "
        "ON group_assignment_member_results (assignment_id, student_pk_id)"
    )
    conn.execute(
        "CREATE INDEX IF NOT EXISTS idx_group_assignment_member_results_group "
        "ON group_assignment_member_results (assignment_id, group_id)"
    )

    # Extend peer_reviews with the 20-point contribution score used by group
    # assignments + a flag marking auto-filled defaults (student closed the page
    # without rating). These are additive/nullable so the legacy 3-axis peer
    # review path is unaffected.
    _add_column(conn, "peer_reviews", "contribution_points", "INTEGER", engine=engine)
    _add_column(conn, "peer_reviews", "is_auto_default", "INTEGER NOT NULL DEFAULT 0", engine=engine)

    _SCHEMA_READY = True
