"""Schema for timetable availability caches (课表编辑模式 · 可调时段).

Three school-wide caches feed the editor's "where can this lesson go" overlay:

* ``academic_class_timetable_slots`` — 行政班 / 教学班 term timetables pulled
  from 教务 (students' other courses). A slot is one recurring block:
  weekday + contiguous sections + the weeks it occurs in.
* ``academic_room_timetable_slots`` — the same shape for a classroom (room
  timetable), when 教务 exposes it.
* ``academic_room_slot_checks`` — per (week, weekday, sections) verdicts for a
  room obtained from targeted 空闲教室 queries; fills the gaps when a full
  room timetable is unavailable.

``academic_availability_sync_state`` records, per teacher and term, when the
caches were last refreshed and what 教务 endpoints answered.

Engine-aware, idempotent DDL (``CREATE TABLE IF NOT EXISTS`` on SQLite and
PostgreSQL), ensured lazily at runtime like ``schema_schedule_editor``.
"""

from __future__ import annotations

from typing import Any

from .connection import get_configured_db_engine

_SCHEMA_READY = False


def ensure_schedule_availability_schema(conn: Any) -> None:
    global _SCHEMA_READY
    if _SCHEMA_READY:
        return
    engine = get_configured_db_engine()
    id_column = (
        "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
        if engine == "postgres"
        else "id INTEGER PRIMARY KEY AUTOINCREMENT"
    )
    conn.execute(
        f"""
        CREATE TABLE IF NOT EXISTS academic_class_timetable_slots (
            {id_column},
            school_code TEXT NOT NULL DEFAULT 'gxufl',
            academic_year TEXT NOT NULL DEFAULT '',
            academic_term TEXT NOT NULL DEFAULT '',
            scope_kind TEXT NOT NULL DEFAULT 'admin_class',
            scope_key TEXT NOT NULL DEFAULT '',
            scope_name TEXT NOT NULL DEFAULT '',
            weekday INTEGER NOT NULL DEFAULT 0,
            sections_json TEXT NOT NULL DEFAULT '[]',
            weeks_json TEXT NOT NULL DEFAULT '[]',
            course_name TEXT NOT NULL DEFAULT '',
            teaching_class_name TEXT NOT NULL DEFAULT '',
            room TEXT NOT NULL DEFAULT '',
            teacher_name TEXT NOT NULL DEFAULT '',
            source_path TEXT NOT NULL DEFAULT '',
            synced_at TEXT NOT NULL DEFAULT ''
        )
        """
    )
    conn.execute(
        "CREATE INDEX IF NOT EXISTS idx_class_timetable_slots_scope "
        "ON academic_class_timetable_slots (school_code, academic_year, academic_term, scope_kind, scope_key)"
    )
    conn.execute(
        f"""
        CREATE TABLE IF NOT EXISTS academic_room_timetable_slots (
            {id_column},
            school_code TEXT NOT NULL DEFAULT 'gxufl',
            academic_year TEXT NOT NULL DEFAULT '',
            academic_term TEXT NOT NULL DEFAULT '',
            room_id TEXT NOT NULL DEFAULT '',
            room_name TEXT NOT NULL DEFAULT '',
            weekday INTEGER NOT NULL DEFAULT 0,
            sections_json TEXT NOT NULL DEFAULT '[]',
            weeks_json TEXT NOT NULL DEFAULT '[]',
            course_name TEXT NOT NULL DEFAULT '',
            teaching_class_name TEXT NOT NULL DEFAULT '',
            teacher_name TEXT NOT NULL DEFAULT '',
            source_path TEXT NOT NULL DEFAULT '',
            synced_at TEXT NOT NULL DEFAULT ''
        )
        """
    )
    conn.execute(
        "CREATE INDEX IF NOT EXISTS idx_room_timetable_slots_room "
        "ON academic_room_timetable_slots (school_code, academic_year, academic_term, room_id)"
    )
    conn.execute(
        f"""
        CREATE TABLE IF NOT EXISTS academic_room_slot_checks (
            {id_column},
            school_code TEXT NOT NULL DEFAULT 'gxufl',
            academic_year TEXT NOT NULL DEFAULT '',
            academic_term TEXT NOT NULL DEFAULT '',
            room_id TEXT NOT NULL DEFAULT '',
            room_name TEXT NOT NULL DEFAULT '',
            week INTEGER NOT NULL DEFAULT 0,
            weekday INTEGER NOT NULL DEFAULT 0,
            sections_json TEXT NOT NULL DEFAULT '[]',
            status TEXT NOT NULL DEFAULT 'unknown',
            detail TEXT NOT NULL DEFAULT '',
            checked_at TEXT NOT NULL DEFAULT '',
            UNIQUE (school_code, academic_year, academic_term, room_id, week, weekday, sections_json)
        )
        """
    )
    conn.execute(
        f"""
        CREATE TABLE IF NOT EXISTS academic_availability_sync_state (
            {id_column},
            teacher_id INTEGER NOT NULL,
            academic_year TEXT NOT NULL DEFAULT '',
            academic_term TEXT NOT NULL DEFAULT '',
            status TEXT NOT NULL DEFAULT 'never',
            message TEXT NOT NULL DEFAULT '',
            class_scope_count INTEGER NOT NULL DEFAULT 0,
            class_slot_count INTEGER NOT NULL DEFAULT 0,
            room_count INTEGER NOT NULL DEFAULT 0,
            room_slot_count INTEGER NOT NULL DEFAULT 0,
            source_summary_json TEXT NOT NULL DEFAULT '[]',
            synced_at TEXT NOT NULL DEFAULT '',
            updated_at TEXT NOT NULL DEFAULT '',
            UNIQUE (teacher_id, academic_year, academic_term)
        )
        """
    )
    _SCHEMA_READY = True


def reset_schema_ready_for_tests() -> None:
    global _SCHEMA_READY
    _SCHEMA_READY = False
