"""Schema for combined-class offerings (合班课堂) — offering↔class links.

A class offering historically bound exactly one administrative class via
``class_offerings.class_id``. Real academic teaching classes (教学班) can be
composed of several administrative classes (教学班组成/JXBZC), so this table
turns the binding into one-to-many:

* every offering keeps ``class_offerings.class_id`` as its **primary class**
  (backward compatibility, display fallback and the UNIQUE(class, course,
  semester) anchor);
* each linked class gets one row here; the primary class row has
  ``is_primary = 1`` and must always agree with ``class_offerings.class_id``.

The DDL is engine-aware and idempotent (``CREATE TABLE IF NOT EXISTS`` on both
SQLite and PostgreSQL) so it can be ensured lazily at runtime without touching
the central SQLite->PostgreSQL migration — mirroring ``schema_polls`` and
``schema_study_group_scheme``. Timestamps are ISO-8601 TEXT and booleans are
INTEGER 0/1, consistent with the rest of the codebase.

Backfill runs inside :func:`ensure_offering_class_links_schema` and is
idempotent: offerings without a primary link get one seeded from their
``class_id`` (source ``backfill``), so pre-existing single-class offerings
behave identically before and after this feature ships.
"""

from __future__ import annotations

from typing import Any

from .connection import get_configured_db_engine

LINK_SOURCE_MANUAL = "manual"
LINK_SOURCE_ACADEMIC_SYNC = "academic_sync"
LINK_SOURCE_BACKFILL = "backfill"

_READY_KEYS: set[str] = set()


def _schema_identity_key() -> str:
    """Guard key per (engine, database) so tests with per-case temp SQLite
    files re-ensure automatically while production ensures once per process."""
    engine = get_configured_db_engine()
    if engine == "postgres":
        return "postgres"
    try:
        from .. import config

        return f"sqlite:{config.DB_PATH}"
    except Exception:
        return "sqlite"


def ensure_offering_class_links_schema(
    conn: Any, *, force: bool = False, engine: str | None = None
) -> None:
    """Create the link table on either engine and backfill primary links.

    ``force`` bypasses the per-database ready cache and ``engine`` overrides
    the configured engine — both used by test fixtures that build hand-rolled
    minimal schemas on ad-hoc connections.
    """
    ready_key = _schema_identity_key()
    if ready_key in _READY_KEYS and not force:
        return
    engine = engine or get_configured_db_engine()
    id_column = (
        "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
        if engine == "postgres"
        else "id INTEGER PRIMARY KEY AUTOINCREMENT"
    )

    conn.execute(
        f"""
        CREATE TABLE IF NOT EXISTS class_offering_class_links (
            {id_column},
            offering_id INTEGER NOT NULL,
            class_id INTEGER NOT NULL,
            teacher_id INTEGER NOT NULL,
            is_primary INTEGER NOT NULL DEFAULT 0,
            source TEXT NOT NULL DEFAULT '{LINK_SOURCE_MANUAL}',
            academic_admin_class_name TEXT NOT NULL DEFAULT '',
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            UNIQUE (offering_id, class_id)
        )
        """
    )
    conn.execute(
        "CREATE INDEX IF NOT EXISTS idx_cocl_class "
        "ON class_offering_class_links (class_id, offering_id)"
    )
    conn.execute(
        "CREATE INDEX IF NOT EXISTS idx_cocl_offering "
        "ON class_offering_class_links (offering_id, is_primary)"
    )

    # Display/badge cache columns on the offering itself. Kept in this runtime
    # module (not the central migration) so both engines converge lazily.
    if engine == "postgres":
        conn.execute(
            "ALTER TABLE class_offerings ADD COLUMN IF NOT EXISTS "
            "is_combined INTEGER NOT NULL DEFAULT 0"
        )
        conn.execute(
            "ALTER TABLE class_offerings ADD COLUMN IF NOT EXISTS "
            "combined_class_names TEXT NOT NULL DEFAULT ''"
        )
    else:
        for statement in (
            "ALTER TABLE class_offerings ADD COLUMN is_combined INTEGER NOT NULL DEFAULT 0",
            "ALTER TABLE class_offerings ADD COLUMN combined_class_names TEXT NOT NULL DEFAULT ''",
        ):
            try:
                conn.execute(statement)
            except Exception:
                pass

    _backfill_primary_links(conn)
    if not force:
        # force 走的是测试夹具的 ad-hoc 连接（如 :memory:），不能把
        # 「当前配置数据库已就绪」写进进程级缓存，否则会污染后续连接。
        _READY_KEYS.add(ready_key)


def _backfill_primary_links(conn: Any) -> None:
    """Seed a primary link for every offering that lacks one (idempotent).

    Two repair paths so re-running always converges:
    1. the (offering, primary class) pair is missing entirely → insert it;
    2. the pair exists but lost its ``is_primary`` flag while no other primary
       exists → promote it.
    """
    conn.execute(
        f"""
        INSERT INTO class_offering_class_links (
            offering_id, class_id, teacher_id, is_primary, source
        )
        SELECT o.id, o.class_id, o.teacher_id, 1, '{LINK_SOURCE_BACKFILL}'
        FROM class_offerings o
        WHERE o.class_id IS NOT NULL
          AND NOT EXISTS (
                SELECT 1 FROM class_offering_class_links l
                WHERE l.offering_id = o.id AND l.class_id = o.class_id
          )
          AND NOT EXISTS (
                SELECT 1 FROM class_offering_class_links p
                WHERE p.offering_id = o.id AND p.is_primary = 1
          )
        """
    )
    conn.execute(
        """
        UPDATE class_offering_class_links
        SET is_primary = 1
        WHERE is_primary = 0
          AND EXISTS (
                SELECT 1 FROM class_offerings o
                WHERE o.id = class_offering_class_links.offering_id
                  AND o.class_id = class_offering_class_links.class_id
          )
          AND NOT EXISTS (
                SELECT 1 FROM class_offering_class_links p
                WHERE p.offering_id = class_offering_class_links.offering_id
                  AND p.is_primary = 1
          )
        """
    )
