"""Schema for multi-material binding on课次/课程首页.

历史上每个课次 (`class_offering_sessions.learning_material_id`) 和课程首页
(`class_offerings.home_learning_material_id`) 只能绑定**一份** Markdown 文档。
本表把绑定关系升级为**列表**：一个课次/首页可以同时挂多份材料
（Markdown 阅读 + HTML 渲染等混合），课堂卡片的"材料入口"点开后以宽卡片列表
呈现，逐项可进入、可解绑。

约定：
- ``session_id = 0`` 表示课程首页/课堂级绑定；``> 0`` 表示具体课次。
- 旧的单列字段 (`learning_material_id` / `home_learning_material_id`) 继续保留，
  始终镜像为列表中的"首项/主材料"，以兼容时间轴、AI/Git 自动绑定、agent 等
  仍读取单列的旧代码；本表是材料**列表**的事实来源。
- ``ai_blurb`` 由快速版 AI 生成的一句话介绍（≤20 字），懒加载、可失败降级。

DDL 引擎自适应、幂等（sqlite + postgres 均 ``CREATE TABLE IF NOT EXISTS``），
可在运行时按需 ensure，无需改动中心化迁移 —— 与 ``schema_study_group_scheme`` 一致。
"""

from __future__ import annotations

from typing import Any

from .connection import get_configured_db_engine

_SCHEMA_READY = False


def ensure_session_learning_materials_schema(conn: Any) -> None:
    global _SCHEMA_READY
    if _SCHEMA_READY:
        return
    engine = get_configured_db_engine()
    id_column = (
        "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
        if engine == "postgres"
        else "id INTEGER PRIMARY KEY AUTOINCREMENT"
    )

    conn.execute(
        f"""
        CREATE TABLE IF NOT EXISTS class_offering_learning_materials (
            {id_column},
            class_offering_id INTEGER NOT NULL,
            session_id INTEGER NOT NULL DEFAULT 0,
            material_id INTEGER NOT NULL,
            ai_blurb TEXT NOT NULL DEFAULT '',
            ai_blurb_status TEXT NOT NULL DEFAULT 'idle',
            sort_order INTEGER NOT NULL DEFAULT 0,
            created_by_teacher_id INTEGER NOT NULL DEFAULT 0,
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            UNIQUE (class_offering_id, session_id, material_id)
        )
        """
    )
    conn.execute(
        "CREATE INDEX IF NOT EXISTS idx_offering_learning_materials_scope "
        "ON class_offering_learning_materials (class_offering_id, session_id, sort_order, id)"
    )
    conn.execute(
        "CREATE INDEX IF NOT EXISTS idx_offering_learning_materials_material "
        "ON class_offering_learning_materials (material_id)"
    )

    _SCHEMA_READY = True
