"""Immutable attendance originals and reviewed, versioned interpretations."""
from __future__ import annotations

from .connection import get_configured_db_engine


TABLES = (
    "smart_attendance_source_bindings", "smart_attendance_source_offerings", "attendance_reports",
    "attendance_report_versions", "attendance_parse_runs", "attendance_report_students",
    "attendance_report_sessions", "attendance_report_cells", "attendance_report_reviews",
)


def attendance_report_schema_statements(engine: str) -> tuple[str, ...]:
    pk = "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY" if engine == "postgres" else "INTEGER PRIMARY KEY AUTOINCREMENT"
    return (
        f"""CREATE TABLE IF NOT EXISTS smart_attendance_source_bindings (
            id {pk}, owner_teacher_id BIGINT NOT NULL REFERENCES teachers(id),
            school_code TEXT NOT NULL, platform_code TEXT NOT NULL, external_account_key TEXT NOT NULL,
            credential_id BIGINT, remote_schedule_id TEXT NOT NULL,
            academic_year TEXT NOT NULL, academic_term INTEGER NOT NULL CHECK(academic_term IN (1,2)),
            semester_id BIGINT, remote_course_id TEXT NOT NULL DEFAULT '', remote_course_name TEXT NOT NULL DEFAULT '',
            remote_class_id TEXT NOT NULL DEFAULT '', remote_class_name TEXT NOT NULL DEFAULT '',
            source_metadata_json TEXT NOT NULL DEFAULT '{{}}', binding_state TEXT NOT NULL DEFAULT 'confirmed',
            revision INTEGER NOT NULL DEFAULT 1, confirmed_by BIGINT, confirmed_at TEXT,
            created_at TEXT NOT NULL, updated_at TEXT NOT NULL,
            UNIQUE(owner_teacher_id,school_code,platform_code,external_account_key,academic_year,academic_term,remote_schedule_id)
        )""",
        f"""CREATE TABLE IF NOT EXISTS smart_attendance_source_offerings (
            id {pk}, binding_id BIGINT NOT NULL REFERENCES smart_attendance_source_bindings(id),
            class_offering_id BIGINT REFERENCES class_offerings(id) ON DELETE SET NULL,
            link_state TEXT NOT NULL DEFAULT 'active', is_grade_source INTEGER NOT NULL DEFAULT 0, match_method TEXT NOT NULL DEFAULT 'teacher_confirmed',
            scope_json TEXT NOT NULL DEFAULT '{{}}', revision INTEGER NOT NULL DEFAULT 1,
            confirmed_by BIGINT, confirmed_at TEXT, ended_at TEXT,
            UNIQUE(binding_id,class_offering_id)
        )""",
        f"""CREATE TABLE IF NOT EXISTS attendance_reports (
            id {pk}, binding_id BIGINT NOT NULL REFERENCES smart_attendance_source_bindings(id),
            scope_kind TEXT NOT NULL DEFAULT 'all_schedule' CHECK(scope_kind='all_schedule'),
            latest_source_version_id BIGINT, confirmed_parse_run_id BIGINT,
            revision INTEGER NOT NULL DEFAULT 1, created_at TEXT NOT NULL, updated_at TEXT NOT NULL,
            deleted_at TEXT, deleted_by BIGINT, UNIQUE(binding_id,scope_kind)
        )""",
        f"""CREATE TABLE IF NOT EXISTS attendance_report_versions (
            id {pk}, report_id BIGINT NOT NULL REFERENCES attendance_reports(id), version_no INTEGER NOT NULL,
            request_key TEXT NOT NULL, job_id BIGINT, source_file_hash TEXT,
            source_byte_size BIGINT, source_page_count INTEGER, source_filename TEXT NOT NULL DEFAULT '',
            media_type TEXT NOT NULL DEFAULT 'application/pdf', request_manifest_json TEXT NOT NULL DEFAULT '{{}}',
            checkin_manifest_json TEXT NOT NULL DEFAULT '{{}}', manifest_fingerprint TEXT NOT NULL DEFAULT '',
            fetched_at TEXT, source_exported_at TEXT, source_state TEXT NOT NULL DEFAULT 'queued',
            error_code TEXT NOT NULL DEFAULT '', safe_message TEXT NOT NULL DEFAULT '', created_by BIGINT NOT NULL,
            created_at TEXT NOT NULL, UNIQUE(report_id,version_no), UNIQUE(report_id,request_key)
        )""",
        f"""CREATE TABLE IF NOT EXISTS attendance_parse_runs (
            id {pk}, source_version_id BIGINT NOT NULL REFERENCES attendance_report_versions(id), run_no INTEGER NOT NULL,
            request_key TEXT NOT NULL, job_id BIGINT, base_confirmed_run_id BIGINT,
            mapped_offering_id BIGINT REFERENCES class_offerings(id) ON DELETE SET NULL, binding_link_revision INTEGER,
            parser_version TEXT NOT NULL DEFAULT 'v1', prompt_version TEXT NOT NULL DEFAULT 'v1',
            model_id TEXT NOT NULL DEFAULT '', schema_version TEXT NOT NULL DEFAULT 'v1', ai_used INTEGER NOT NULL DEFAULT 0,
            ai_coverage_json TEXT NOT NULL DEFAULT '{{}}', state TEXT NOT NULL DEFAULT 'queued',
            semantic_fingerprint TEXT NOT NULL DEFAULT '', validation_json TEXT NOT NULL DEFAULT '{{}}',
            coverage_json TEXT NOT NULL DEFAULT '{{}}', revision INTEGER NOT NULL DEFAULT 1,
            started_at TEXT, finished_at TEXT, confirmed_by BIGINT, confirmed_at TEXT,
            error_code TEXT NOT NULL DEFAULT '', safe_message TEXT NOT NULL DEFAULT '',
            UNIQUE(source_version_id,run_no), UNIQUE(source_version_id,request_key)
        )""",
        f"""CREATE TABLE IF NOT EXISTS attendance_report_students (
            id {pk}, parse_run_id BIGINT NOT NULL REFERENCES attendance_parse_runs(id), row_index INTEGER NOT NULL,
            student_number TEXT NOT NULL DEFAULT '', source_name TEXT NOT NULL DEFAULT '', source_class_name TEXT NOT NULL DEFAULT '',
            local_student_id BIGINT REFERENCES students(id) ON DELETE SET NULL, identity_state TEXT NOT NULL DEFAULT 'unmapped',
            source_page INTEGER, bbox_json TEXT NOT NULL DEFAULT '[]', raw_identity_json TEXT NOT NULL DEFAULT '{{}}',
            UNIQUE(parse_run_id,row_index), UNIQUE(parse_run_id,id)
        )""",
        f"""CREATE TABLE IF NOT EXISTS attendance_report_sessions (
            id {pk}, parse_run_id BIGINT NOT NULL REFERENCES attendance_parse_runs(id), column_index INTEGER NOT NULL,
            source_header TEXT NOT NULL DEFAULT '', source_datetime TEXT, time_precision TEXT NOT NULL DEFAULT 'minute',
            remote_checkin_id TEXT, local_session_id BIGINT REFERENCES class_offering_sessions(id) ON DELETE SET NULL,
            week_index INTEGER, weekday INTEGER, section INTEGER, mapping_state TEXT NOT NULL DEFAULT 'unmapped',
            evidence_json TEXT NOT NULL DEFAULT '{{}}', UNIQUE(parse_run_id,column_index), UNIQUE(parse_run_id,id)
        )""",
        f"""CREATE TABLE IF NOT EXISTS attendance_report_cells (
            id {pk}, parse_run_id BIGINT NOT NULL REFERENCES attendance_parse_runs(id),
            student_row_id BIGINT NOT NULL, session_column_id BIGINT NOT NULL,
            raw_text TEXT NOT NULL DEFAULT '', raw_status TEXT NOT NULL DEFAULT '',
            normalized_status TEXT NOT NULL DEFAULT 'UNKNOWN', quality_state TEXT NOT NULL DEFAULT 'unknown',
            interpretation_method TEXT NOT NULL DEFAULT '', model_confidence DOUBLE PRECISION,
            evidence_page INTEGER, bbox_json TEXT NOT NULL DEFAULT '[]', api_status TEXT, ai_status TEXT,
            evidence_fingerprint TEXT NOT NULL DEFAULT '', revision INTEGER NOT NULL DEFAULT 1,
            FOREIGN KEY(parse_run_id,student_row_id) REFERENCES attendance_report_students(parse_run_id,id),
            FOREIGN KEY(parse_run_id,session_column_id) REFERENCES attendance_report_sessions(parse_run_id,id),
            UNIQUE(parse_run_id,student_row_id,session_column_id)
        )""",
        f"""CREATE TABLE IF NOT EXISTS attendance_report_reviews (
            id {pk}, parse_run_id BIGINT NOT NULL REFERENCES attendance_parse_runs(id),
            target_type TEXT NOT NULL, target_id BIGINT, before_json TEXT NOT NULL DEFAULT '{{}}',
            after_json TEXT NOT NULL DEFAULT '{{}}', reason TEXT NOT NULL DEFAULT '', actor_id BIGINT NOT NULL,
            expected_revision INTEGER NOT NULL, created_at TEXT NOT NULL, event_type TEXT NOT NULL
        )""",
        "CREATE UNIQUE INDEX IF NOT EXISTS idx_attendance_one_active_offering ON smart_attendance_source_offerings(binding_id) WHERE link_state='active'",
        "CREATE UNIQUE INDEX IF NOT EXISTS idx_attendance_one_grade_source ON smart_attendance_source_offerings(class_offering_id) WHERE link_state='active' AND is_grade_source=1",
        "CREATE INDEX IF NOT EXISTS idx_attendance_binding_owner_term ON smart_attendance_source_bindings(owner_teacher_id,school_code,academic_year,academic_term)",
        "CREATE INDEX IF NOT EXISTS idx_attendance_offering_binding ON smart_attendance_source_offerings(class_offering_id,binding_id)",
        "CREATE INDEX IF NOT EXISTS idx_attendance_report_page ON attendance_reports(deleted_at,updated_at,id)",
        "CREATE INDEX IF NOT EXISTS idx_attendance_run_state ON attendance_parse_runs(state,finished_at,id)",
        "CREATE INDEX IF NOT EXISTS idx_attendance_student_number ON attendance_report_students(parse_run_id,student_number)",
        "CREATE INDEX IF NOT EXISTS idx_attendance_student_local ON attendance_report_students(parse_run_id,local_student_id)",
        "CREATE INDEX IF NOT EXISTS idx_attendance_cell_quality ON attendance_report_cells(parse_run_id,quality_state)",
        "CREATE INDEX IF NOT EXISTS idx_attendance_cell_status ON attendance_report_cells(parse_run_id,normalized_status)",
    )


def ensure_attendance_report_schema(conn, *, engine: str | None = None) -> None:
    for statement in attendance_report_schema_statements(engine or get_configured_db_engine()):
        conn.execute(statement)


ATTENDANCE_REPORT_POSTGRES_TABLES = dict(zip(TABLES, attendance_report_schema_statements("postgres")[:len(TABLES)]))
# Keep validation derived from the actual schema: only top-level declarations,
# not tokens inside constraints or JSON defaults, are column names.
def _required_columns() -> dict[str, tuple[str, ...]]:
    import re
    result = {}
    for table, sql in ATTENDANCE_REPORT_POSTGRES_TABLES.items():
        result[table] = tuple(re.findall(r"(?:\(|,)\s*([a-z][a-z_0-9]*)\s+(?:BIGINT|TEXT|INTEGER|DOUBLE)\b", sql))
    return result


ATTENDANCE_REPORT_REQUIRED_COLUMNS = _required_columns()
