"""Additive conversation storage; historical feedback and attachments stay untouched."""
from .connection import get_configured_db_engine


def feedback_conversation_schema_statements(engine):
    pk = "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY" if engine == "postgres" else "INTEGER PRIMARY KEY AUTOINCREMENT"
    return (
        f"""CREATE TABLE IF NOT EXISTS app_feedback_messages (
            id {pk}, feedback_id BIGINT NOT NULL REFERENCES app_feedback(id) ON DELETE CASCADE,
            sender_role TEXT NOT NULL, sender_id TEXT NOT NULL, sender_name TEXT NOT NULL DEFAULT '',
            sender_is_super_admin INTEGER NOT NULL DEFAULT 0,
            event_type TEXT NOT NULL CHECK(event_type IN ('reply','closed','reopened')),
            content TEXT NOT NULL DEFAULT '', client_message_id TEXT NOT NULL,
            created_at TEXT NOT NULL,
            UNIQUE(feedback_id,sender_role,sender_id,client_message_id)
        )""",
        """CREATE TABLE IF NOT EXISTS app_feedback_reads (
            feedback_id BIGINT NOT NULL REFERENCES app_feedback(id) ON DELETE CASCADE,
            user_role TEXT NOT NULL, user_id TEXT NOT NULL,
            last_read_message_id BIGINT NOT NULL DEFAULT 0, updated_at TEXT NOT NULL,
            PRIMARY KEY(feedback_id,user_role,user_id)
        )""",
        "CREATE INDEX IF NOT EXISTS idx_feedback_messages_page ON app_feedback_messages(feedback_id,id)",
        "CREATE INDEX IF NOT EXISTS idx_feedback_owner_page ON app_feedback(user_role,user_id,id)",
        "CREATE INDEX IF NOT EXISTS idx_feedback_status_page ON app_feedback(status,id)",
    )


def ensure_feedback_conversation_schema(conn, *, engine=None):
    for statement in feedback_conversation_schema_statements(engine or get_configured_db_engine()):
        conn.execute(statement)


FEEDBACK_CONVERSATION_POSTGRES_TABLES = dict(zip(
    ("app_feedback_messages", "app_feedback_reads"), feedback_conversation_schema_statements("postgres")[:2]
))
FEEDBACK_CONVERSATION_REQUIRED_COLUMNS = {
    "app_feedback_messages": ("id", "feedback_id", "sender_role", "sender_id", "sender_name",
                              "sender_is_super_admin", "event_type", "content", "client_message_id", "created_at"),
    "app_feedback_reads": ("feedback_id", "user_role", "user_id", "last_read_message_id", "updated_at"),
}
