"""Account-owned assistant storage, independent of classroom foreign keys."""
from .connection import get_configured_db_engine


def ai_workspace_schema_statements(engine):
    pk = "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY" if engine == "postgres" else "INTEGER PRIMARY KEY AUTOINCREMENT"
    return (
        f"""CREATE TABLE IF NOT EXISTS ai_workspace_sessions (
            id {pk}, session_uuid TEXT NOT NULL UNIQUE,
            user_pk BIGINT NOT NULL, user_role TEXT NOT NULL CHECK(user_role IN ('teacher','student')),
            title TEXT NOT NULL DEFAULT '新对话', created_at TEXT NOT NULL, updated_at TEXT NOT NULL,
            active_request_id TEXT, request_started_at TEXT
        )""",
        f"""CREATE TABLE IF NOT EXISTS ai_workspace_messages (
            id {pk}, session_id BIGINT NOT NULL REFERENCES ai_workspace_sessions(id) ON DELETE CASCADE,
            request_id TEXT NOT NULL, role TEXT NOT NULL CHECK(role IN ('user','assistant')),
            message TEXT NOT NULL, attachments_json TEXT NOT NULL DEFAULT '[]',
            thinking_content TEXT, final_answer TEXT, created_at TEXT NOT NULL,
            status TEXT NOT NULL DEFAULT 'running', request_fingerprint TEXT NOT NULL DEFAULT '',
            UNIQUE(session_id,request_id,role)
        )""",
        """CREATE TABLE IF NOT EXISTS ai_workspace_profile_states (
            user_pk BIGINT NOT NULL, user_role TEXT NOT NULL CHECK(user_role IN ('teacher','student')),
            completed_rounds BIGINT NOT NULL DEFAULT 0, profiled_rounds BIGINT NOT NULL DEFAULT 0,
            claimed_rounds BIGINT NOT NULL DEFAULT 0, claim_token TEXT,
            lease_until TEXT, next_due_at TEXT NOT NULL DEFAULT '',
            profile_json TEXT NOT NULL DEFAULT '{}', profile_updated_at TEXT,
            PRIMARY KEY(user_role,user_pk)
        )""",
        "CREATE INDEX IF NOT EXISTS idx_ai_workspace_owner ON ai_workspace_sessions(user_role,user_pk,updated_at DESC,id DESC)",
        "CREATE INDEX IF NOT EXISTS idx_ai_workspace_history ON ai_workspace_messages(session_id,id)",
        "CREATE INDEX IF NOT EXISTS idx_ai_workspace_profile_due ON ai_workspace_profile_states(next_due_at,lease_until)",
        "CREATE INDEX IF NOT EXISTS idx_behavior_profiles_personal ON classroom_behavior_profiles(user_role,user_pk,created_at DESC,id DESC)",
        "CREATE INDEX IF NOT EXISTS idx_ai_psych_profiles_personal ON ai_psychology_profiles(user_role,user_pk,created_at DESC,id DESC)",
    )


def ensure_ai_workspace_schema(conn, *, engine=None):
    for statement in ai_workspace_schema_statements(engine or get_configured_db_engine()):
        conn.execute(statement)


AI_WORKSPACE_POSTGRES_TABLES = dict(zip(
    ('ai_workspace_sessions', 'ai_workspace_messages', 'ai_workspace_profile_states'),
    ai_workspace_schema_statements('postgres')[:3],
))
AI_WORKSPACE_REQUIRED_COLUMNS = {
    'ai_workspace_sessions': ('id', 'session_uuid', 'user_pk', 'user_role', 'title', 'created_at', 'updated_at', 'active_request_id', 'request_started_at'),
    'ai_workspace_messages': ('id', 'session_id', 'request_id', 'role', 'message', 'attachments_json', 'thinking_content', 'final_answer', 'created_at', 'status', 'request_fingerprint'),
    'ai_workspace_profile_states': ('user_pk', 'user_role', 'completed_rounds', 'profiled_rounds', 'claimed_rounds', 'claim_token', 'lease_until', 'next_due_at', 'profile_json', 'profile_updated_at'),
}
