"""Schema for the Smart Classroom teacher course schedule (教师课程表 / 课时统计).

Stores the raw teaching schedule pulled from the Smart Classroom endpoint
``POST /teaching/teacherSchedule/list``. Each remote row is one recurring
schedule slot: a course taught in one classroom, on one weekday (``xqj``),
covering a contiguous section block (``sections``) across a set of teaching
weeks (``weeks``). Sync is *replace-based*: every sync wipes the teacher's
rows for the returned academic term and re-inserts the fresh payload, so the
local copy always mirrors the platform.

``smart_classroom_course_schedule_meta`` keeps one row per
(teacher, platform, year, semester) with the term-level context returned by
the endpoint (current week, max week) plus the sync timestamp.

The DDL is engine-aware and idempotent (``CREATE TABLE IF NOT EXISTS`` on both
SQLite and PostgreSQL) so it can be ensured lazily at runtime without touching
the central SQLite->PostgreSQL migration — mirroring ``schema_polls``.
Timestamps are ISO-8601 TEXT, consistent with the rest of the codebase.
"""

from __future__ import annotations

from typing import Any

from .connection import get_configured_db_engine

_SCHEMA_READY = False


def ensure_course_schedule_schema(conn: Any) -> None:
    """Create the teacher course-schedule tables on either engine (idempotent)."""
    global _SCHEMA_READY
    if _SCHEMA_READY:
        return
    engine = get_configured_db_engine()
    id_column = (
        "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
        if engine == "postgres"
        else "id INTEGER PRIMARY KEY AUTOINCREMENT"
    )

    conn.execute(
        f"""
        CREATE TABLE IF NOT EXISTS smart_classroom_course_schedule_meta (
            {id_column},
            teacher_id INTEGER NOT NULL,
            platform_code TEXT NOT NULL DEFAULT 'gxufl_smart_classroom',
            academic_year TEXT NOT NULL DEFAULT '',
            academic_term TEXT NOT NULL DEFAULT '',
            cur_week INTEGER NOT NULL DEFAULT 0,
            max_week INTEGER NOT NULL DEFAULT 0,
            cur_xq INTEGER NOT NULL DEFAULT 0,
            item_count INTEGER NOT NULL DEFAULT 0,
            week1_monday_date TEXT NOT NULL DEFAULT '',
            synced_at TEXT NOT NULL DEFAULT '',
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            UNIQUE (teacher_id, platform_code, academic_year, academic_term)
        )
        """
    )
    conn.execute(
        "CREATE INDEX IF NOT EXISTS idx_course_schedule_meta_teacher "
        "ON smart_classroom_course_schedule_meta (teacher_id, synced_at DESC)"
    )

    # One row per remote schedule slot. sections_json / weeks_json are JSON
    # arrays of integers; weekday follows the remote convention 1=周一 .. 7=周日.
    # local_class_name / class_offering_id are resolved at sync time from the
    # check-in schedule sync so the UI can show real class names (软工2303班)
    # and deep-link each lesson to its本地课堂 when the mapping is unambiguous.
    conn.execute(
        f"""
        CREATE TABLE IF NOT EXISTS smart_classroom_course_schedule_items (
            {id_column},
            teacher_id INTEGER NOT NULL,
            platform_code TEXT NOT NULL DEFAULT 'gxufl_smart_classroom',
            remote_id TEXT NOT NULL DEFAULT '',
            course_name TEXT NOT NULL DEFAULT '',
            course_code TEXT NOT NULL DEFAULT '',
            classroom TEXT NOT NULL DEFAULT '',
            teaching_class_name TEXT NOT NULL DEFAULT '',
            local_class_name TEXT NOT NULL DEFAULT '',
            class_offering_id INTEGER,
            teacher_name TEXT NOT NULL DEFAULT '',
            teacher_no TEXT NOT NULL DEFAULT '',
            academic_year TEXT NOT NULL DEFAULT '',
            academic_term TEXT NOT NULL DEFAULT '',
            weekday INTEGER NOT NULL DEFAULT 0,
            sections_json TEXT NOT NULL DEFAULT '[]',
            weeks_json TEXT NOT NULL DEFAULT '[]',
            week_text TEXT NOT NULL DEFAULT '',
            single_or_double TEXT NOT NULL DEFAULT 'NONE',
            student_count INTEGER NOT NULL DEFAULT 0,
            metadata_json TEXT NOT NULL DEFAULT '{{}}',
            synced_at TEXT NOT NULL DEFAULT '',
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            UNIQUE (teacher_id, platform_code, remote_id)
        )
        """
    )
    conn.execute(
        "CREATE INDEX IF NOT EXISTS idx_course_schedule_items_term "
        "ON smart_classroom_course_schedule_items "
        "(teacher_id, academic_year, academic_term, weekday)"
    )
    _ensure_extension_columns(conn, engine)

    _SCHEMA_READY = True


def _ensure_extension_columns(conn: Any, engine: str) -> None:
    """Add columns introduced after the first release to pre-existing tables."""
    extension_columns: dict[str, tuple[tuple[str, str], ...]] = {
        "smart_classroom_course_schedule_items": (
            ("local_class_name", "TEXT NOT NULL DEFAULT ''"),
            ("class_offering_id", "INTEGER"),
        ),
        # week1_monday_date：该学期第 1 教学周周一（ISO 日期），同步当前学期时由
        # synced_at 与 curWeek 反推，是"第几周/几月几号"换算的兜底锚点。
        "smart_classroom_course_schedule_meta": (
            ("week1_monday_date", "TEXT NOT NULL DEFAULT ''"),
        ),
    }
    for table, columns in extension_columns.items():
        if engine == "postgres":
            for name, ddl_type in columns:
                conn.execute(f"ALTER TABLE {table} ADD COLUMN IF NOT EXISTS {name} {ddl_type}")
            continue
        existing = {
            str(row[1])
            for row in conn.execute(f"PRAGMA table_info({table})").fetchall()
        }
        for name, ddl_type in columns:
            if name not in existing:
                conn.execute(f"ALTER TABLE {table} ADD COLUMN {name} {ddl_type}")
