"""Schema for LessonDoc course doc packs(课程学习文档包登记表).

A *pack* (``course_doc_packs``) registers one LessonDoc 2.0 package folder in
the teacher's material library: it links the package root material row to the
course it was generated for, remembers the theme and caches the manifest for
list pages. Per-lesson generation state lives in ``course_doc_pack_lessons``
(pending/queued/running/ready/failed/excluded + the teacher's per-lesson
generation hint and validation warnings).

Deliberately NOT bound to ``class_offering_id``: packs belong to course ×
teacher; classroom binding reuses the existing HTML-package deterministic
binding (``apply_package_session_bindings``) + the two-layer binding tables,
so no ``offering_merge_service.MERGE_RULES`` entry is needed.

Engine-aware, idempotent runtime DDL mirroring ``schema_polls``. Timestamps
are ISO-8601 TEXT.
"""

from __future__ import annotations

from typing import Any

from .connection import get_configured_db_engine

_SCHEMA_READY = False


def ensure_course_doc_pack_schema(conn: Any) -> None:
    """Create the pack tables on either engine (idempotent)."""
    global _SCHEMA_READY
    if _SCHEMA_READY:
        return
    engine = get_configured_db_engine()
    id_column = (
        "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
        if engine == "postgres"
        else "id INTEGER PRIMARY KEY AUTOINCREMENT"
    )

    conn.execute(
        f"""
        CREATE TABLE IF NOT EXISTS course_doc_packs (
            {id_column},
            root_material_id INTEGER NOT NULL UNIQUE,
            course_id INTEGER NOT NULL,
            teacher_id INTEGER NOT NULL,
            spec_version TEXT NOT NULL DEFAULT 'lessondoc/2.0',
            theme TEXT NOT NULL DEFAULT 'sky',
            status TEXT NOT NULL DEFAULT 'active',
            assets_fingerprint TEXT NOT NULL DEFAULT '',
            manifest_cache_json TEXT NOT NULL DEFAULT '{{}}',
            created_at TEXT NOT NULL,
            updated_at TEXT NOT NULL
        )
        """
    )
    conn.execute(
        "CREATE INDEX IF NOT EXISTS idx_course_doc_packs_course "
        "ON course_doc_packs (course_id, teacher_id, status)"
    )
    conn.execute(
        "CREATE INDEX IF NOT EXISTS idx_course_doc_packs_teacher "
        "ON course_doc_packs (teacher_id, status, updated_at DESC)"
    )

    conn.execute(
        f"""
        CREATE TABLE IF NOT EXISTS course_doc_pack_lessons (
            {id_column},
            pack_id INTEGER NOT NULL,
            lesson_no INTEGER NOT NULL,
            gen_status TEXT NOT NULL DEFAULT 'pending',
            user_hint TEXT NOT NULL DEFAULT '',
            last_task_id INTEGER,
            warnings_json TEXT NOT NULL DEFAULT '[]',
            updated_at TEXT NOT NULL,
            UNIQUE (pack_id, lesson_no)
        )
        """
    )
    conn.execute(
        "CREATE INDEX IF NOT EXISTS idx_course_doc_pack_lessons_pack "
        "ON course_doc_pack_lessons (pack_id, lesson_no)"
    )
    _SCHEMA_READY = True


def reset_schema_ready_for_tests() -> None:
    """单测夹具用:跨套件手搓 schema 时重置 ensure 守卫."""
    global _SCHEMA_READY
    _SCHEMA_READY = False
