"""Runtime schema for editor snapshots, retry receipts and reusable elements.

Receipts are separate from history: a successful retry must not create a revision
or require a large duplicate of the document. All tables are scoped by pack/owner.
"""

from .connection import get_configured_db_engine

_SCHEMA_READY = False


def ensure_lessondoc_editor_schema(conn):
    if _SCHEMA_READY:
        return
    identity = "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY" if get_configured_db_engine() == "postgres" else "INTEGER PRIMARY KEY AUTOINCREMENT"
    conn.execute(f"""CREATE TABLE IF NOT EXISTS lessondoc_doc_revisions (
        id {identity}, pack_id INTEGER NOT NULL, lesson_no INTEGER NOT NULL DEFAULT 0,
        file_hash TEXT NOT NULL, model_json TEXT NOT NULL, source TEXT NOT NULL,
        author_id INTEGER NOT NULL, created_at TEXT NOT NULL
    )""")
    conn.execute("CREATE INDEX IF NOT EXISTS idx_lessondoc_revisions_document ON lessondoc_doc_revisions(pack_id, lesson_no, id DESC)")
    conn.execute(f"""CREATE TABLE IF NOT EXISTS lessondoc_save_operations (
        id {identity}, pack_id INTEGER NOT NULL, lesson_no INTEGER NOT NULL DEFAULT 0,
        operation_id TEXT NOT NULL, request_digest TEXT NOT NULL, result_revision TEXT NOT NULL,
        created_at TEXT NOT NULL, UNIQUE(pack_id, lesson_no, operation_id)
    )""")
    conn.execute("CREATE INDEX IF NOT EXISTS idx_lessondoc_operations_pack ON lessondoc_save_operations(pack_id, id DESC)")
    conn.execute(f"""CREATE TABLE IF NOT EXISTS lessondoc_custom_elements (
        id {identity}, teacher_id INTEGER NOT NULL, name TEXT NOT NULL,
        category TEXT NOT NULL DEFAULT 'custom', model_json TEXT NOT NULL,
        source_pack_id INTEGER NOT NULL, media_json TEXT NOT NULL DEFAULT '[]',
        thumbnail_svg TEXT NOT NULL DEFAULT '', created_at TEXT NOT NULL, updated_at TEXT NOT NULL
    )""")
    conn.execute("CREATE INDEX IF NOT EXISTS idx_lessondoc_elements_owner ON lessondoc_custom_elements(teacher_id, updated_at DESC, id DESC)")


def mark_schema_ready_after_commit():
    """Called only after startup DDL commits, never from a user transaction."""
    global _SCHEMA_READY
    _SCHEMA_READY = True


def reset_schema_ready_for_tests():
    global _SCHEMA_READY
    _SCHEMA_READY = False
