"""Schema for the student resume console (简历管理与优化控制台).

Student-facing résumé workbench. All tables are owned by ``student_id`` and use
the same engine-aware, idempotent, runtime-managed pattern as
``schema_career_path`` / ``schema_assessment_plans`` (``CREATE TABLE IF NOT
EXISTS`` on both SQLite and PostgreSQL), so they are ensured lazily at runtime
and do NOT enter the central SQLite->PostgreSQL migration / required-table
validation. Timestamps are ISO-8601 TEXT; booleans are INTEGER 0/1.

Tables:

* ``resume_personal_info``  — one row per student (the personal info form).
* ``resume_self_intros``    — many self-introductions per student (manual / AI).
* ``resume_certificates``   — certificates (with optional image attachments).
* ``resume_skills``         — skills (with optional image attachments).
* ``resume_experiences``    — project / competition experience.
* ``resume_educations``     — schooling history (high-school / university / training).
* ``resume_attachments``    — image attachments for cert/skill/experience items.
* ``resumes``               — assembled résumés (layout + render html + status).
"""

from __future__ import annotations

from typing import Any

from .connection import get_configured_db_engine

_SCHEMA_READY = False


def _add_column(conn: Any, table: str, column: str, definition: str, *, engine: str) -> None:
    """Idempotently add a column to an existing table on either engine."""
    if engine == "postgres":
        conn.execute(f"ALTER TABLE {table} ADD COLUMN IF NOT EXISTS {column} {definition}")
        return
    try:
        conn.execute(f"ALTER TABLE {table} ADD COLUMN {column} {definition}")
    except Exception:
        pass


def ensure_resume_schema(conn: Any) -> None:
    """Create all resume-console tables (sqlite + postgres), idempotently."""
    global _SCHEMA_READY
    if _SCHEMA_READY:
        return
    engine = get_configured_db_engine()
    id_column = (
        "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
        if engine == "postgres"
        else "id INTEGER PRIMARY KEY AUTOINCREMENT"
    )

    # One personal-info row per student.
    conn.execute(
        f"""
        CREATE TABLE IF NOT EXISTS resume_personal_info (
            {id_column},
            student_id INTEGER NOT NULL,
            name TEXT NOT NULL DEFAULT '',
            gender TEXT NOT NULL DEFAULT '',
            birthday TEXT NOT NULL DEFAULT '',
            phone TEXT NOT NULL DEFAULT '',
            email TEXT NOT NULL DEFAULT '',
            qq TEXT NOT NULL DEFAULT '',
            wechat TEXT NOT NULL DEFAULT '',
            address TEXT NOT NULL DEFAULT '',
            hometown TEXT NOT NULL DEFAULT '',
            id_card TEXT NOT NULL DEFAULT '',
            expected_position TEXT NOT NULL DEFAULT '',
            expected_industry TEXT NOT NULL DEFAULT '',
            expected_salary TEXT NOT NULL DEFAULT '',
            avatar_file_hash TEXT NOT NULL DEFAULT '',
            avatar_mime_type TEXT NOT NULL DEFAULT '',
            extra_json TEXT NOT NULL DEFAULT '{{}}',
            seeded INTEGER NOT NULL DEFAULT 0,
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            UNIQUE (student_id)
        )
        """
    )

    # Many self-introductions per student. status drives the placeholder card.
    conn.execute(
        f"""
        CREATE TABLE IF NOT EXISTS resume_self_intros (
            {id_column},
            student_id INTEGER NOT NULL,
            title TEXT NOT NULL DEFAULT '',
            content_md TEXT NOT NULL DEFAULT '',
            source TEXT NOT NULL DEFAULT 'manual',
            status TEXT NOT NULL DEFAULT 'ready',
            error_text TEXT NOT NULL DEFAULT '',
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
        )
        """
    )
    conn.execute(
        "CREATE INDEX IF NOT EXISTS idx_resume_self_intros_student "
        "ON resume_self_intros (student_id, created_at DESC, id DESC)"
    )

    # Certificates.
    conn.execute(
        f"""
        CREATE TABLE IF NOT EXISTS resume_certificates (
            {id_column},
            student_id INTEGER NOT NULL,
            name TEXT NOT NULL DEFAULT '',
            acquired_date TEXT NOT NULL DEFAULT '',
            expiry_date TEXT NOT NULL DEFAULT '',
            description TEXT NOT NULL DEFAULT '',
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
        )
        """
    )
    conn.execute(
        "CREATE INDEX IF NOT EXISTS idx_resume_certificates_student "
        "ON resume_certificates (student_id, created_at DESC, id DESC)"
    )

    # Skills.
    conn.execute(
        f"""
        CREATE TABLE IF NOT EXISTS resume_skills (
            {id_column},
            student_id INTEGER NOT NULL,
            name TEXT NOT NULL DEFAULT '',
            level TEXT NOT NULL DEFAULT '',
            acquired_date TEXT NOT NULL DEFAULT '',
            expiry_date TEXT NOT NULL DEFAULT '',
            description TEXT NOT NULL DEFAULT '',
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
        )
        """
    )
    conn.execute(
        "CREATE INDEX IF NOT EXISTS idx_resume_skills_student "
        "ON resume_skills (student_id, created_at DESC, id DESC)"
    )

    # Project / competition experience.
    conn.execute(
        f"""
        CREATE TABLE IF NOT EXISTS resume_experiences (
            {id_column},
            student_id INTEGER NOT NULL,
            kind TEXT NOT NULL DEFAULT 'project',
            title TEXT NOT NULL DEFAULT '',
            start_date TEXT NOT NULL DEFAULT '',
            end_date TEXT NOT NULL DEFAULT '',
            role TEXT NOT NULL DEFAULT '',
            content TEXT NOT NULL DEFAULT '',
            contribution TEXT NOT NULL DEFAULT '',
            achievement TEXT NOT NULL DEFAULT '',
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
        )
        """
    )
    conn.execute(
        "CREATE INDEX IF NOT EXISTS idx_resume_experiences_student "
        "ON resume_experiences (student_id, created_at DESC, id DESC)"
    )

    # Education history.
    conn.execute(
        f"""
        CREATE TABLE IF NOT EXISTS resume_educations (
            {id_column},
            student_id INTEGER NOT NULL,
            kind TEXT NOT NULL DEFAULT 'university',
            school TEXT NOT NULL DEFAULT '',
            college TEXT NOT NULL DEFAULT '',
            major TEXT NOT NULL DEFAULT '',
            start_date TEXT NOT NULL DEFAULT '',
            end_date TEXT NOT NULL DEFAULT '',
            content TEXT NOT NULL DEFAULT '',
            source TEXT NOT NULL DEFAULT 'manual',
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
        )
        """
    )
    conn.execute(
        "CREATE INDEX IF NOT EXISTS idx_resume_educations_student "
        "ON resume_educations (student_id, created_at DESC, id DESC)"
    )

    # Image attachments for cert / skill / experience items.
    conn.execute(
        f"""
        CREATE TABLE IF NOT EXISTS resume_attachments (
            {id_column},
            student_id INTEGER NOT NULL,
            owner_kind TEXT NOT NULL DEFAULT '',
            owner_id INTEGER NOT NULL,
            file_hash TEXT NOT NULL DEFAULT '',
            original_filename TEXT NOT NULL DEFAULT '',
            mime_type TEXT NOT NULL DEFAULT '',
            file_size INTEGER NOT NULL DEFAULT 0,
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
        )
        """
    )
    conn.execute(
        "CREATE INDEX IF NOT EXISTS idx_resume_attachments_owner "
        "ON resume_attachments (student_id, owner_kind, owner_id, id)"
    )

    # Assembled résumés.
    conn.execute(
        f"""
        CREATE TABLE IF NOT EXISTS resumes (
            {id_column},
            student_id INTEGER NOT NULL,
            title TEXT NOT NULL DEFAULT '我的简历',
            target_position TEXT NOT NULL DEFAULT '',
            template_key TEXT NOT NULL DEFAULT 'classic',
            layout_json TEXT NOT NULL DEFAULT '{{}}',
            tech_stack_json TEXT NOT NULL DEFAULT '[]',
            optimized_summary_md TEXT NOT NULL DEFAULT '',
            optimization_notes_json TEXT NOT NULL DEFAULT '{{}}',
            render_html TEXT NOT NULL DEFAULT '',
            status TEXT NOT NULL DEFAULT 'draft',
            error_text TEXT NOT NULL DEFAULT '',
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
        )
        """
    )
    conn.execute(
        "CREATE INDEX IF NOT EXISTS idx_resumes_student "
        "ON resumes (student_id, created_at DESC, id DESC)"
    )

    # Backfill columns for databases created before a column existed.
    _add_column(conn, "resume_personal_info", "seeded", "INTEGER NOT NULL DEFAULT 0", engine=engine)
    _add_column(conn, "resume_skills", "expiry_date", "TEXT NOT NULL DEFAULT ''", engine=engine)
    _add_column(conn, "resumes", "target_position", "TEXT NOT NULL DEFAULT ''", engine=engine)
    _add_column(conn, "resumes", "tech_stack_json", "TEXT NOT NULL DEFAULT '[]'", engine=engine)
    _add_column(conn, "resumes", "optimized_summary_md", "TEXT NOT NULL DEFAULT ''", engine=engine)
    _add_column(conn, "resumes", "optimization_notes_json", "TEXT NOT NULL DEFAULT '{}'", engine=engine)

    _SCHEMA_READY = True
