from __future__ import annotations

from typing import Any

from .connection import get_configured_db_engine


def ensure_cultivation_progress_schema(conn: Any, *, engine: str | None = None) -> None:
    """Ensure cached cultivation progress tables across SQLite and PostgreSQL."""
    db_engine = (engine or get_configured_db_engine()).strip().lower()
    if db_engine == "postgres":
        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS learning_progress_snapshots (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                class_offering_id INTEGER NOT NULL,
                student_id INTEGER NOT NULL,
                score DOUBLE PRECISION NOT NULL DEFAULT 0,
                progress_percent INTEGER NOT NULL DEFAULT 0,
                components_json TEXT NOT NULL DEFAULT '{}',
                metrics_json TEXT NOT NULL DEFAULT '{}',
                level_key TEXT NOT NULL DEFAULT 'mortal',
                next_stage_key TEXT,
                calculated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
                dirty INTEGER NOT NULL DEFAULT 0,
                dirty_at TEXT,
                metadata_json TEXT NOT NULL DEFAULT '{}'
            )
            """
        )
        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS cultivation_score_events (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                class_offering_id INTEGER NOT NULL,
                student_id INTEGER NOT NULL,
                event_type TEXT NOT NULL,
                delta DOUBLE PRECISION NOT NULL DEFAULT 0,
                component TEXT NOT NULL DEFAULT 'total',
                source_ref TEXT NOT NULL DEFAULT '',
                created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
                metadata_json TEXT NOT NULL DEFAULT '{}'
            )
            """
        )
        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS cultivation_score_event_archives (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                class_offering_id INTEGER NOT NULL,
                student_id INTEGER NOT NULL,
                archive_month TEXT NOT NULL,
                event_type TEXT NOT NULL,
                component TEXT NOT NULL DEFAULT 'total',
                event_count INTEGER NOT NULL DEFAULT 0,
                total_delta DOUBLE PRECISION NOT NULL DEFAULT 0,
                first_event_at TEXT NOT NULL,
                last_event_at TEXT NOT NULL,
                archived_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
                metadata_json TEXT NOT NULL DEFAULT '{}'
            )
            """
        )
        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS cultivation_weekly_snapshots (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                class_offering_id INTEGER NOT NULL,
                student_id INTEGER NOT NULL,
                week_start TEXT NOT NULL,
                week_end TEXT NOT NULL,
                score DOUBLE PRECISION NOT NULL DEFAULT 0,
                progress_percent INTEGER NOT NULL DEFAULT 0,
                components_json TEXT NOT NULL DEFAULT '{}',
                level_key TEXT NOT NULL DEFAULT 'mortal',
                snapshot_source TEXT NOT NULL DEFAULT 'scheduled',
                created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
                metadata_json TEXT NOT NULL DEFAULT '{}'
            )
            """
        )
        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS cultivation_alerts (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                class_offering_id INTEGER NOT NULL,
                student_id INTEGER NOT NULL,
                rule_key TEXT NOT NULL,
                severity TEXT NOT NULL DEFAULT 'L1',
                status TEXT NOT NULL DEFAULT 'active',
                title TEXT NOT NULL DEFAULT '',
                body TEXT NOT NULL DEFAULT '',
                evidence_json TEXT NOT NULL DEFAULT '{}',
                first_seen_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
                last_seen_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
                handled_at TEXT,
                handled_by_teacher_id INTEGER,
                snoozed_until TEXT,
                action_note TEXT NOT NULL DEFAULT '',
                metadata_json TEXT NOT NULL DEFAULT '{}'
            )
            """
        )
        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS ai_usage_log (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                task_type TEXT NOT NULL,
                priority TEXT NOT NULL DEFAULT 'P1',
                endpoint TEXT NOT NULL DEFAULT '',
                status TEXT NOT NULL DEFAULT 'unknown',
                status_code INTEGER,
                duration_ms INTEGER NOT NULL DEFAULT 0,
                prompt_tokens_estimate INTEGER NOT NULL DEFAULT 0,
                completion_tokens_estimate INTEGER NOT NULL DEFAULT 0,
                class_offering_id INTEGER,
                student_id INTEGER,
                teacher_id INTEGER,
                source_ref TEXT NOT NULL DEFAULT '',
                error_message TEXT NOT NULL DEFAULT '',
                metadata_json TEXT NOT NULL DEFAULT '{}',
                created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
            )
            """
        )
    else:
        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS learning_progress_snapshots (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                class_offering_id INTEGER NOT NULL,
                student_id INTEGER NOT NULL,
                score REAL NOT NULL DEFAULT 0,
                progress_percent INTEGER NOT NULL DEFAULT 0,
                components_json TEXT NOT NULL DEFAULT '{}',
                metrics_json TEXT NOT NULL DEFAULT '{}',
                level_key TEXT NOT NULL DEFAULT 'mortal',
                next_stage_key TEXT,
                calculated_at TEXT DEFAULT CURRENT_TIMESTAMP,
                dirty INTEGER NOT NULL DEFAULT 0,
                dirty_at TEXT,
                metadata_json TEXT NOT NULL DEFAULT '{}',
                FOREIGN KEY (class_offering_id) REFERENCES class_offerings (id) ON DELETE CASCADE,
                FOREIGN KEY (student_id) REFERENCES students (id) ON DELETE CASCADE,
                UNIQUE (class_offering_id, student_id)
            )
            """
        )
        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS cultivation_score_events (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                class_offering_id INTEGER NOT NULL,
                student_id INTEGER NOT NULL,
                event_type TEXT NOT NULL,
                delta REAL NOT NULL DEFAULT 0,
                component TEXT NOT NULL DEFAULT 'total',
                source_ref TEXT NOT NULL DEFAULT '',
                created_at TEXT DEFAULT CURRENT_TIMESTAMP,
                metadata_json TEXT NOT NULL DEFAULT '{}',
                FOREIGN KEY (class_offering_id) REFERENCES class_offerings (id) ON DELETE CASCADE,
                FOREIGN KEY (student_id) REFERENCES students (id) ON DELETE CASCADE
            )
            """
        )
        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS cultivation_score_event_archives (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                class_offering_id INTEGER NOT NULL,
                student_id INTEGER NOT NULL,
                archive_month TEXT NOT NULL,
                event_type TEXT NOT NULL,
                component TEXT NOT NULL DEFAULT 'total',
                event_count INTEGER NOT NULL DEFAULT 0,
                total_delta REAL NOT NULL DEFAULT 0,
                first_event_at TEXT NOT NULL,
                last_event_at TEXT NOT NULL,
                archived_at TEXT DEFAULT CURRENT_TIMESTAMP,
                metadata_json TEXT NOT NULL DEFAULT '{}',
                FOREIGN KEY (class_offering_id) REFERENCES class_offerings (id) ON DELETE CASCADE,
                FOREIGN KEY (student_id) REFERENCES students (id) ON DELETE CASCADE,
                UNIQUE (class_offering_id, student_id, archive_month, event_type, component)
            )
            """
        )
        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS cultivation_weekly_snapshots (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                class_offering_id INTEGER NOT NULL,
                student_id INTEGER NOT NULL,
                week_start TEXT NOT NULL,
                week_end TEXT NOT NULL,
                score REAL NOT NULL DEFAULT 0,
                progress_percent INTEGER NOT NULL DEFAULT 0,
                components_json TEXT NOT NULL DEFAULT '{}',
                level_key TEXT NOT NULL DEFAULT 'mortal',
                snapshot_source TEXT NOT NULL DEFAULT 'scheduled',
                created_at TEXT DEFAULT CURRENT_TIMESTAMP,
                metadata_json TEXT NOT NULL DEFAULT '{}',
                FOREIGN KEY (class_offering_id) REFERENCES class_offerings (id) ON DELETE CASCADE,
                FOREIGN KEY (student_id) REFERENCES students (id) ON DELETE CASCADE,
                UNIQUE (class_offering_id, student_id, week_start)
            )
            """
        )
        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS cultivation_alerts (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                class_offering_id INTEGER NOT NULL,
                student_id INTEGER NOT NULL,
                rule_key TEXT NOT NULL,
                severity TEXT NOT NULL DEFAULT 'L1',
                status TEXT NOT NULL DEFAULT 'active',
                title TEXT NOT NULL DEFAULT '',
                body TEXT NOT NULL DEFAULT '',
                evidence_json TEXT NOT NULL DEFAULT '{}',
                first_seen_at TEXT DEFAULT CURRENT_TIMESTAMP,
                last_seen_at TEXT DEFAULT CURRENT_TIMESTAMP,
                handled_at TEXT,
                handled_by_teacher_id INTEGER,
                snoozed_until TEXT,
                action_note TEXT NOT NULL DEFAULT '',
                metadata_json TEXT NOT NULL DEFAULT '{}',
                FOREIGN KEY (class_offering_id) REFERENCES class_offerings (id) ON DELETE CASCADE,
                FOREIGN KEY (student_id) REFERENCES students (id) ON DELETE CASCADE
            )
            """
        )
        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS ai_usage_log (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                task_type TEXT NOT NULL,
                priority TEXT NOT NULL DEFAULT 'P1',
                endpoint TEXT NOT NULL DEFAULT '',
                status TEXT NOT NULL DEFAULT 'unknown',
                status_code INTEGER,
                duration_ms INTEGER NOT NULL DEFAULT 0,
                prompt_tokens_estimate INTEGER NOT NULL DEFAULT 0,
                completion_tokens_estimate INTEGER NOT NULL DEFAULT 0,
                class_offering_id INTEGER,
                student_id INTEGER,
                teacher_id INTEGER,
                source_ref TEXT NOT NULL DEFAULT '',
                error_message TEXT NOT NULL DEFAULT '',
                metadata_json TEXT NOT NULL DEFAULT '{}',
                created_at TEXT DEFAULT CURRENT_TIMESTAMP,
                FOREIGN KEY (class_offering_id) REFERENCES class_offerings (id) ON DELETE SET NULL,
                FOREIGN KEY (student_id) REFERENCES students (id) ON DELETE SET NULL
            )
            """
        )

    conn.execute(
        "CREATE UNIQUE INDEX IF NOT EXISTS idx_learning_progress_snapshots_unique_student "
        "ON learning_progress_snapshots (class_offering_id, student_id)"
    )
    conn.execute(
        "CREATE INDEX IF NOT EXISTS idx_learning_progress_snapshots_dirty "
        "ON learning_progress_snapshots (dirty, dirty_at, class_offering_id)"
    )
    conn.execute(
        "CREATE INDEX IF NOT EXISTS idx_learning_progress_snapshots_level "
        "ON learning_progress_snapshots (class_offering_id, level_key, score DESC)"
    )
    conn.execute(
        "CREATE INDEX IF NOT EXISTS idx_cultivation_score_events_student "
        "ON cultivation_score_events (class_offering_id, student_id, created_at DESC, id DESC)"
    )
    conn.execute(
        "CREATE INDEX IF NOT EXISTS idx_cultivation_score_events_component "
        "ON cultivation_score_events (class_offering_id, component, created_at DESC)"
    )
    conn.execute(
        "CREATE UNIQUE INDEX IF NOT EXISTS idx_cultivation_score_event_archives_unique_bucket "
        "ON cultivation_score_event_archives (class_offering_id, student_id, archive_month, event_type, component)"
    )
    conn.execute(
        "CREATE INDEX IF NOT EXISTS idx_cultivation_score_event_archives_student_month "
        "ON cultivation_score_event_archives (class_offering_id, student_id, archive_month DESC)"
    )
    conn.execute(
        "CREATE UNIQUE INDEX IF NOT EXISTS idx_cultivation_weekly_snapshots_unique_student_week "
        "ON cultivation_weekly_snapshots (class_offering_id, student_id, week_start)"
    )
    conn.execute(
        "CREATE INDEX IF NOT EXISTS idx_cultivation_weekly_snapshots_offering_week "
        "ON cultivation_weekly_snapshots (class_offering_id, week_start DESC)"
    )
    conn.execute(
        "CREATE INDEX IF NOT EXISTS idx_cultivation_weekly_snapshots_student_week "
        "ON cultivation_weekly_snapshots (student_id, week_start DESC)"
    )
    conn.execute(
        "CREATE INDEX IF NOT EXISTS idx_cultivation_alerts_active_offering "
        "ON cultivation_alerts (class_offering_id, status, severity, last_seen_at DESC)"
    )
    conn.execute(
        "CREATE INDEX IF NOT EXISTS idx_cultivation_alerts_student_rule "
        "ON cultivation_alerts (class_offering_id, student_id, rule_key, status)"
    )
    conn.execute(
        "CREATE INDEX IF NOT EXISTS idx_cultivation_alerts_snoozed "
        "ON cultivation_alerts (status, snoozed_until)"
    )
    conn.execute(
        "CREATE INDEX IF NOT EXISTS idx_ai_usage_log_task_created "
        "ON ai_usage_log (task_type, created_at DESC, id DESC)"
    )
    conn.execute(
        "CREATE INDEX IF NOT EXISTS idx_ai_usage_log_offering_created "
        "ON ai_usage_log (class_offering_id, created_at DESC, id DESC)"
    )
    conn.execute(
        "CREATE INDEX IF NOT EXISTS idx_ai_usage_log_priority_created "
        "ON ai_usage_log (priority, created_at DESC, id DESC)"
    )
