"""Schema for the combined-class offering merge wizard (合并向导, P4.0).

Two runtime tables, engine-aware and idempotent (mirroring ``schema_polls``):

* ``offering_merge_archives`` — full JSON snapshot of every source-offering row
  across all registered tables, captured in the same transaction right before
  migration. Restoration is a documented manual procedure, not a one-click
  rollback.
* ``offering_merge_logs`` — audit trail: who merged what into what, per-table
  row counts, duration and the archive reference.
"""

from __future__ import annotations

from typing import Any

from .connection import get_configured_db_engine

_SCHEMA_READY = False


def ensure_offering_merge_schema(conn: Any, *, force: bool = False, engine: str | None = None) -> None:
    global _SCHEMA_READY
    if _SCHEMA_READY and not force:
        return
    resolved_engine = engine or get_configured_db_engine()
    id_column = (
        "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
        if resolved_engine == "postgres"
        else "id INTEGER PRIMARY KEY AUTOINCREMENT"
    )

    conn.execute(
        f"""
        CREATE TABLE IF NOT EXISTS offering_merge_archives (
            {id_column},
            merge_token TEXT NOT NULL DEFAULT '',
            teacher_id INTEGER NOT NULL,
            target_offering_id INTEGER NOT NULL,
            source_offering_ids_json TEXT NOT NULL DEFAULT '[]',
            payload_json TEXT NOT NULL DEFAULT '{{}}',
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
        )
        """
    )
    conn.execute(
        "CREATE INDEX IF NOT EXISTS idx_offering_merge_archives_teacher "
        "ON offering_merge_archives (teacher_id, created_at DESC)"
    )

    conn.execute(
        f"""
        CREATE TABLE IF NOT EXISTS offering_merge_logs (
            {id_column},
            merge_token TEXT NOT NULL DEFAULT '',
            teacher_id INTEGER NOT NULL,
            target_offering_id INTEGER NOT NULL,
            source_offering_ids_json TEXT NOT NULL DEFAULT '[]',
            summary_json TEXT NOT NULL DEFAULT '{{}}',
            archive_id INTEGER,
            duration_ms INTEGER NOT NULL DEFAULT 0,
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
        )
        """
    )
    conn.execute(
        "CREATE INDEX IF NOT EXISTS idx_offering_merge_logs_teacher "
        "ON offering_merge_logs (teacher_id, created_at DESC)"
    )

    if not force:
        _SCHEMA_READY = True
