"""Schema for the 校园公文通 (official-document) teacher integration.

Teachers connect their unified-auth account; the platform logs into the school
公文通 (``doc.gxufl.com``) and syncs inbox documents. 公文 are **campus-scoped**
shared records — deduped per (school, system, remote_id), so each campus only
syncs a given document once. Visibility within a campus is governed by the
unified 归属 + 开放范围 model (``material_scope_service``): every document carries
``attr_school_code / attr_college / attr_department / attr_level / openness``.

Engine-aware, idempotent DDL (mirrors ``schema_scheduler``). Includes a one-time
migration from the original per-teacher shape to the campus-scoped shape: the
feature is new and all data is re-syncable, so an old-shape table is dropped and
recreated rather than risking a fragile in-place unique-index swap.
"""

from __future__ import annotations

from typing import Any

from .connection import get_configured_db_engine

_SCHEMA_READY = False


def _gongwen_documents_needs_recreate(conn: Any, engine: str) -> bool:
    """True when an old per-teacher ``gongwen_documents`` predates the campus
    scope (no ``attr_school_code`` column). Uses schema metadata (never a failing
    SELECT) so it is safe inside a PostgreSQL transaction."""
    if engine == "postgres":
        table_there = conn.execute(
            "SELECT 1 FROM information_schema.tables "
            "WHERE table_schema = 'public' AND table_name = 'gongwen_documents' LIMIT 1"
        ).fetchone() is not None
        if not table_there:
            return False
        col_there = conn.execute(
            "SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' "
            "AND table_name = 'gongwen_documents' AND column_name = 'attr_school_code' LIMIT 1"
        ).fetchone() is not None
        return not col_there
    # sqlite
    table_there = conn.execute(
        "SELECT 1 FROM sqlite_master WHERE type = 'table' AND name = 'gongwen_documents' LIMIT 1"
    ).fetchone() is not None
    if not table_there:
        return False
    info = conn.execute("PRAGMA table_info(gongwen_documents)").fetchall()
    return not any((row[1] if not hasattr(row, "keys") else row["name"]) == "attr_school_code" for row in info)


def ensure_gongwen_schema(conn: Any) -> None:
    """Create the 公文 integration tables if absent (sqlite + postgres)."""
    global _SCHEMA_READY
    if _SCHEMA_READY:
        return
    engine = get_configured_db_engine()
    id_column = (
        "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
        if engine == "postgres"
        else "id INTEGER PRIMARY KEY AUTOINCREMENT"
    )

    # --- Saved teacher credential (one row per teacher per system+auth) ---
    conn.execute(
        f"""
        CREATE TABLE IF NOT EXISTS teacher_gongwen_credentials (
            {id_column},
            teacher_id INTEGER NOT NULL,
            system_code TEXT NOT NULL,
            system_name TEXT NOT NULL,
            adapter_key TEXT NOT NULL,
            auth_method TEXT NOT NULL DEFAULT 'sso_captcha',
            base_url TEXT NOT NULL DEFAULT '',
            api_base_url TEXT NOT NULL DEFAULT '',
            sso_base_url TEXT NOT NULL DEFAULT '',
            login_url TEXT NOT NULL DEFAULT '',
            username TEXT NOT NULL,
            password_encrypted TEXT NOT NULL,
            display_name TEXT NOT NULL DEFAULT '',
            enabled INTEGER NOT NULL DEFAULT 1,
            last_status TEXT NOT NULL DEFAULT 'unchecked',
            last_status_at TEXT,
            last_error TEXT NOT NULL DEFAULT '',
            last_verified_at TEXT,
            access_method_json TEXT NOT NULL DEFAULT '{{}}',
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
        )
        """
    )
    conn.execute(
        "CREATE UNIQUE INDEX IF NOT EXISTS idx_gongwen_credentials_unique_auth "
        "ON teacher_gongwen_credentials (teacher_id, system_code, auth_method)"
    )
    conn.execute(
        "CREATE INDEX IF NOT EXISTS idx_gongwen_credentials_teacher "
        "ON teacher_gongwen_credentials (teacher_id, enabled, updated_at)"
    )

    # --- One-time migration of the legacy per-teacher documents table ---
    try:
        if _gongwen_documents_needs_recreate(conn, engine):
            conn.execute("DROP TABLE gongwen_documents")
    except Exception:
        # Detection/drop is best-effort; a fresh CREATE below still applies.
        pass

    # --- Campus-scoped synced inbox documents (归属 + 开放范围) ---
    conn.execute(
        f"""
        CREATE TABLE IF NOT EXISTS gongwen_documents (
            {id_column},
            system_code TEXT NOT NULL DEFAULT 'gxufl',
            remote_id TEXT NOT NULL,
            attr_school_code TEXT NOT NULL DEFAULT '',
            attr_school_name TEXT NOT NULL DEFAULT '',
            attr_college TEXT NOT NULL DEFAULT '',
            attr_department TEXT NOT NULL DEFAULT '',
            attr_level TEXT NOT NULL DEFAULT 'school',
            openness TEXT NOT NULL DEFAULT 'school',
            synced_by_teacher_id INTEGER,
            synced_by_credential_id INTEGER,
            sn TEXT NOT NULL DEFAULT '',
            title TEXT NOT NULL DEFAULT '',
            subhead TEXT NOT NULL DEFAULT '',
            author TEXT NOT NULL DEFAULT '',
            sender_name TEXT NOT NULL DEFAULT '',
            category_id TEXT NOT NULL DEFAULT '',
            category_name TEXT NOT NULL DEFAULT '',
            summary TEXT NOT NULL DEFAULT '',
            content_html TEXT NOT NULL DEFAULT '',
            content_text TEXT NOT NULL DEFAULT '',
            keywords TEXT NOT NULL DEFAULT '',
            tags TEXT NOT NULL DEFAULT '',
            source TEXT NOT NULL DEFAULT '',
            link TEXT NOT NULL DEFAULT '',
            source_link TEXT NOT NULL DEFAULT '',
            cover_url TEXT NOT NULL DEFAULT '',
            file_url TEXT NOT NULL DEFAULT '',
            attachment_url TEXT NOT NULL DEFAULT '',
            local_file_path TEXT NOT NULL DEFAULT '',
            local_attachment_path TEXT NOT NULL DEFAULT '',
            file_download_status TEXT NOT NULL DEFAULT 'idle',
            file_download_error TEXT NOT NULL DEFAULT '',
            is_read INTEGER NOT NULL DEFAULT 0,
            is_fav INTEGER NOT NULL DEFAULT 0,
            is_need_feedback INTEGER NOT NULL DEFAULT 0,
            publish_time TEXT NOT NULL DEFAULT '',
            remote_created_at TEXT NOT NULL DEFAULT '',
            remote_updated_at TEXT NOT NULL DEFAULT '',
            scope_overridden INTEGER NOT NULL DEFAULT 0,
            source_file_name TEXT NOT NULL DEFAULT '',
            source_file_type TEXT NOT NULL DEFAULT '',
            parsed_status TEXT NOT NULL DEFAULT 'pending',
            parse_attempts INTEGER NOT NULL DEFAULT 0,
            parse_error TEXT NOT NULL DEFAULT '',
            parsed_title TEXT NOT NULL DEFAULT '',
            parsed_summary TEXT NOT NULL DEFAULT '',
            parsed_signature TEXT NOT NULL DEFAULT '',
            parsed_keywords TEXT NOT NULL DEFAULT '',
            parsed_text TEXT NOT NULL DEFAULT '',
            parsed_payload_json TEXT NOT NULL DEFAULT '{{}}',
            parsed_at TEXT,
            reminder_status TEXT NOT NULL DEFAULT 'none',
            raw_json TEXT NOT NULL DEFAULT '{{}}',
            synced_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
        )
        """
    )
    conn.execute(
        "CREATE UNIQUE INDEX IF NOT EXISTS idx_gongwen_documents_unique_campus "
        "ON gongwen_documents (attr_school_code, system_code, remote_id)"
    )
    conn.execute(
        "CREATE INDEX IF NOT EXISTS idx_gongwen_documents_school_time "
        "ON gongwen_documents (attr_school_code, publish_time)"
    )
    conn.execute(
        "CREATE INDEX IF NOT EXISTS idx_gongwen_documents_school_open "
        "ON gongwen_documents (attr_school_code, openness, attr_college, attr_department)"
    )
    conn.execute(
        "CREATE INDEX IF NOT EXISTS idx_gongwen_documents_school_category "
        "ON gongwen_documents (attr_school_code, category_name)"
    )
    conn.execute(
        "CREATE INDEX IF NOT EXISTS idx_gongwen_documents_reminder "
        "ON gongwen_documents (attr_school_code, reminder_status)"
    )

    # Additively backfill parsed-content columns onto already-migrated
    # campus-shape tables (these post-date the campus migration).
    _ensure_columns(
        conn,
        engine,
        "gongwen_documents",
        (
            ("parsed_status", "TEXT NOT NULL DEFAULT 'pending'"),
            ("parsed_text", "TEXT NOT NULL DEFAULT ''"),
            ("parsed_payload_json", "TEXT NOT NULL DEFAULT '{}'"),
            ("parsed_at", "TEXT"),
            ("source_file_name", "TEXT NOT NULL DEFAULT ''"),
            ("source_file_type", "TEXT NOT NULL DEFAULT ''"),
            ("parse_attempts", "INTEGER NOT NULL DEFAULT 0"),
            ("parse_error", "TEXT NOT NULL DEFAULT ''"),
            ("parsed_title", "TEXT NOT NULL DEFAULT ''"),
            ("parsed_summary", "TEXT NOT NULL DEFAULT ''"),
            ("parsed_signature", "TEXT NOT NULL DEFAULT ''"),
            ("parsed_keywords", "TEXT NOT NULL DEFAULT ''"),
            ("reminder_status", "TEXT NOT NULL DEFAULT 'none'"),
        ),
    )
    conn.execute(
        "CREATE INDEX IF NOT EXISTS idx_gongwen_documents_parse_status "
        "ON gongwen_documents (parsed_status, parse_attempts)"
    )
    # Heal a legacy deployment where parsed_status defaulted to 'idle' (a value
    # the parse worker never claims) — docs ingested there sat unparsed forever.
    try:
        if engine == "postgres":
            conn.execute("ALTER TABLE gongwen_documents ALTER COLUMN parsed_status SET DEFAULT 'pending'")
        conn.execute("UPDATE gongwen_documents SET parsed_status = 'pending' WHERE parsed_status = 'idle'")
    except Exception:
        pass

    # --- Per-teacher 关注 settings (关注项目 = AI 语义匹配, 关键字 = 硬匹配) ---
    conn.execute(
        f"""
        CREATE TABLE IF NOT EXISTS teacher_gongwen_follow_settings (
            {id_column},
            teacher_id INTEGER NOT NULL,
            follow_items_json TEXT NOT NULL DEFAULT '[]',
            follow_keywords_json TEXT NOT NULL DEFAULT '[]',
            enabled INTEGER NOT NULL DEFAULT 1,
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
        )
        """
    )
    conn.execute(
        "CREATE UNIQUE INDEX IF NOT EXISTS idx_gongwen_follow_settings_teacher "
        "ON teacher_gongwen_follow_settings (teacher_id)"
    )

    # --- 关注命中记录 (one row per teacher per document, dedupes notifications) ---
    conn.execute(
        f"""
        CREATE TABLE IF NOT EXISTS gongwen_follow_hits (
            {id_column},
            teacher_id INTEGER NOT NULL,
            document_id INTEGER NOT NULL,
            match_type TEXT NOT NULL DEFAULT 'keyword',
            matched_keywords_json TEXT NOT NULL DEFAULT '[]',
            matched_items_json TEXT NOT NULL DEFAULT '[]',
            ai_reason TEXT NOT NULL DEFAULT '',
            notified INTEGER NOT NULL DEFAULT 0,
            seen_at TEXT,
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
        )
        """
    )
    conn.execute(
        "CREATE UNIQUE INDEX IF NOT EXISTS idx_gongwen_follow_hits_unique "
        "ON gongwen_follow_hits (teacher_id, document_id)"
    )
    conn.execute(
        "CREATE INDEX IF NOT EXISTS idx_gongwen_follow_hits_teacher_seen "
        "ON gongwen_follow_hits (teacher_id, seen_at, created_at)"
    )
    _SCHEMA_READY = True


def _ensure_columns(conn: Any, engine: str, table: str, columns) -> None:
    for name, definition in columns:
        try:
            if engine == "postgres":
                conn.execute(f"ALTER TABLE {table} ADD COLUMN IF NOT EXISTS {name} {definition}")
            else:
                conn.execute(f"ALTER TABLE {table} ADD COLUMN {name} {definition}")
        except Exception:
            # Column already exists (sqlite raises) — safe to ignore.
            pass
