"""Schema for classroom retake/transfer-student management (重修插班生).

Retake students are marked per class offering: the academic office only
requires them to sit the final exam, so regular homework, quizzes and
attendance are exempt. The AI suggests candidates from student-number
prefixes; only the teacher's explicit confirmation activates the special
handling, with a per-student default ordinary score (70 unless set).

Engine-aware and idempotent, ensured lazily at runtime — mirroring
``schema_polls`` / ``schema_study_group_scheme``. Timestamps are ISO-8601
TEXT, consistent with the rest of the codebase.
"""

from __future__ import annotations

from typing import Any

from .connection import get_configured_db_engine

# 与 schema_polls / schema_scheduler 等 runtime schema 模块同一约定：
# 进程内只执行一次 DDL（热路径如投票/入组会频繁 ensure，PG 上反复 DDL 会争目录锁）。
# 测试里换新连接时按惯例重置 `_SCHEMA_READY = False`。
_SCHEMA_READY = False


def ensure_retake_schema(conn: Any) -> None:
    global _SCHEMA_READY
    if _SCHEMA_READY:
        return
    engine = get_configured_db_engine()
    id_column = (
        "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
        if engine == "postgres"
        else "id INTEGER PRIMARY KEY AUTOINCREMENT"
    )
    conn.execute(
        f"""
        CREATE TABLE IF NOT EXISTS classroom_retake_students (
            {id_column},
            class_offering_id INTEGER NOT NULL,
            student_id INTEGER NOT NULL,
            student_number TEXT NOT NULL DEFAULT '',
            student_name TEXT NOT NULL DEFAULT '',
            status TEXT NOT NULL DEFAULT 'suggested',
            default_ordinary_score REAL NOT NULL DEFAULT 70,
            suggested_reason TEXT NOT NULL DEFAULT '',
            confirmed_by_teacher_id INTEGER,
            confirmed_at TEXT,
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            UNIQUE (class_offering_id, student_id)
        )
        """
    )
    conn.execute(
        "CREATE INDEX IF NOT EXISTS idx_classroom_retake_students_offering "
        "ON classroom_retake_students (class_offering_id, status)"
    )
    _SCHEMA_READY = True
